alphagov/pay-frontend

app/views/charge.html
Added autocomplete attributes
Followed this as a guide — https://cloudfour.com/thinks/autofill-what-web-devs-should-know-but-dont/
=> PP-2475 - Added autofill attributes

package.json
=> PP-2507 - bumping release version to reflect docs link update

app/utils/views.js, app/views/includes/custom.html, app/views/includes/head.html, app/views/layout.html, test/charge_ui_tests.js
Moving things around to be neater and added in logic to enable custom branding when it's been set.
We had to reset the fonts it loads which sorta sucks but it's the only way around it as mustache doesn't let you write logic the other way around 🙄
=> PP-2502 - Finishing up the logic to enable custom branding

app/assets/javascripts/modules/form-input-confirm.js
Basically FF autofill doesnt recognise keyup or change
=> PP-1990 - using input for more robust event detection.

Gruntfile.js, app/services/charge_param_retriever.js, app/services/countries.js, app/services/environment.js, app/services/normalise_cards.js, build-local.sh, test/utils/charge_validation_fields/cardholder_name_field_validation_test.js
- removed unnecessary inner functions and implicitly invoked function wrapper
- applied prefer const/let
- whole file now in strict mode
- cleaned up code
- applied prefer const/let
- whole file now in strict mode
- now a one line export using an arrow function
- strict mode enabled in file
- cleaned up normalise cards
- update gruntfile to run all tests in `./test/**/*.js`
- added missing import in a test
- added npm rebuild and npm i to restore node deps after building docker image
=> Refactored services

app/views/errors/incorrect_state/session_expired.html
Add a css class to make it more testable for our end-to-end tests.
Previously we were checking the text displayed in the error message to differ one error from the other and we want to avoid that.
=> PP-2572 Add session-expired class to make it testable

app/controllers/charge_controller.js, package.json
Remove array.prototype.find and string from dependencies, 
as they are not used.
=> Remove unused dependencies

app/views/errors/charge_confirm_state_completed.html, app/views/errors/incorrect_state/charge_completed.html, package-lock.json
At the moment there's no easy way to test the message shown on some pages. We don't want to assert the text shown to avoid brittle tests, so in order to solve this a class name has been added to the header depending on the status of the payment.
=> PP-2747 Add class name to message to be able to test it from end2end tests

app/views/includes/merchant_details.html
- Remove 'Service' copy from merchant details
=> PP-2688 Remove 'Service' copy from merchant details

app/assets/sass/pages/card-details.scss, app/views/includes/merchant_details.html
Re-opened from https://github.com/alphagov/pay-frontend/pull/312
See https://github.com/alphagov/pay-frontend/pull/312 for more information
=> PP-2688 Merchant details CSS changes

Dockerfile, docker/build_and_test.Dockerfile
some minor security fixes, should also upgrade alpine base layer.
=> PP-2851 upgrade to node 6.12.0

.editorconfig
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles.
=> PP-1797 - Added an .editorconfig to keep things consistent

app/assets/sass/forms/_form-errors.scss
Borders were thinner than GOV.UK standard style 
Also fixed a bunch of styelint errors
=> PP-2915 - increased border width inline with GOV.UK style

.dockerignore, Dockerfile, build-local.sh, docker/build_and_test.sh
- Copied pattern used in all our other Node.js dockerfiles using a symlink for node_modules
=> PP-3004 Switch to standard npm dep install pattern

app/services/countries.js
Correctly initialise "country.entry.aliases" which is used in "data-aliases" html attribute on "Enter card details" page
=> PP-2992 Correctly "country.entry.aliases" initialise

Dockerfile, docker/build_and_test.Dockerfile, docker/upgrade-base.sh
References a newly created base image which is managed by GOV.UK Pay, that addresses CVEs not addressed by the Alpine 3.4 release without resorting to multiple package installs/update as well as the overhead of managing those.
=> PP-2967 Referenced new base image and cleaned up an unused shell script relating to Ubuntu/Aptitude

package.json
Updating to new product page with google analytics click events
=> Bumping product page version to one with click tracking

app/views/charge.njk, app/views/confirm.njk
Minor text changes requested to the charge and confirm pages so that the
title of the page matches the page heading.
Goes with https://github.com/alphagov/pay-accepttests/pull/195
@solo
=> PP-3241 Incorrect page titles on frontend

app/assets/javascripts/modules/analytics-track-click.js, app/utils/analytics.js, app/views/includes/analytics.njk, app/views/includes/scripts.njk, test/analytics_ui_tests.js, test/controllers/charge_controller_test.js, test/controllers/secure_controller_test.js, test/integration/charge_ft_tests.js, test/middleware/resolve_service_test.js, test/middleware/retrieve_charge_test.js
So we can get a better view of activity we are going to start sending GA transaction amount on submit
=> PP-3192 - added metric so we can log transaction amount on google analytics

app/controllers/charge_controller.js, app/controllers/return_controller.js, app/controllers/secure_controller.js, app/controllers/static_controller.js, app/middleware/csrf.js, app/middleware/resolve_service.js, app/middleware/retrieve_charge.js, app/middleware/state_enforcer.js, app/utils/views.js, test/utils/views_test.js
- Remove unnecessary inner functions and variables
- Prefer const
- Remove use of `views.create` in favour of directly accessing and exported `views` object
=> PP-3266 refactor views

Jenkinsfile
- also deploy to ecs 
- run tests on ecs deploy as this is now default
=> PP-3091 Deploy to ECS also 

app/views/error.njk
So automated tests etc. can look for it
=> Add class “general-error” to error.njk page

Jenkinsfile
=> BAU: Fix Jenkinsfile deploy target

package.json
Update the version number of the pay-product-page with documentation url
updated to service url
solo @belindac
=> PP-3379 Change documentation link in header and footer

app/controllers/charge_controller.js, app/services/normalise_charge.js, app/views/auth_3ds_required_in.njk, app/views/auth_3ds_required_out.njk, test/integration/charge_ft_tests.js, test/test_helpers/test_helpers.js, test/utils/normalise_test.js
- Enable 3DS for SmartPay
- Added MD field to the form
- This extra field is required by SmartPay 3DS
=> PP-3528 Enable 3DS for SmartPay

package.json
@tillwirth and @katiebates have been busy
=> BAU - new prod page copy

app/controllers/charge_controller.js, app/router.js, app/utils/ab_test.js, app/utils/analytics.js, app/utils/cookies.js, app/utils/views.js, app/views/confirm_variant.njk, app/views/includes/analytics.njk, test/controllers/charge_controller_test.js
- Added middleware to split traffic between two routes
- Added analytics so we can measure which one they used
- Amended tests and set up env vars and query params so we can disable if we want to
=> PP-3579 - AB testing - Firebreak

package.json
**Users will see responsive payment pages**
Designed to meet user needs, the payment pages give helpful inline error messages and work great on mobile.
**Designed to meet user needs**
The payment pages give helpful inline error messages and are responsive across devices
=> PP-3687 - copy update

app/utils/email_tools.js
=> BAU - mailcheck didnt think gov.uk was legit which is bad

package-lock.json, package.json
BAU: Bump pay-product-page version
=> BAU: Bump pay-product-page version

app/utils/email_tools.js
Correct mailcheck preference for .org domains
Contributed by @soniaturcotte
=> Correct mailcheck preference for .org domains

package-lock.json, package.json
=> BAU - bump product page to include new date

app/assets/sass/helpers/_panels.scss, app/views/includes/privacy_notice.njk, app/views/layout.njk
Highlighting changes to the privacy notice by moving it up and calling it out
=> BAU - another round of tweaks to privacy notice link copy

Dockerfile, docker/build_and_test.Dockerfile
This should fix the build failures
@oswaldquek
=> bau: Use newer Node image that has wget updated

.snyk, package-lock.json, package.json, test/utils/ab_test.js
Removes the 'forever' module.
Also added missing ab_test tests which were failing NYC coverage thresholds
=> PP-3905 Remove 'forever'

app/router.js, server.js, test/integration/404_tests.js
#432 raised via alphagov github so pr builder works
=> PP-3133: Route unknown pages on public facing apps to standard gov.uk/404

locales/cy.json, locales/en.json
All strings translated by DVLA
=> PP-4097 - Welsh strings JSON file 🏴󠁧󠁢󠁷󠁬󠁳󠁿

app/views/confirm.njk
=> bau- name somehow got dropped in translation migration

app/router.js
Language was bypassed by state enforcer
=> PP-4098 - add language middleware to error pages

app/controllers/charge_controller.js, app/models/card.js, app/utils/charge_validation_backend.js, config/i18n.js, locales/cy.json, locales/en.json, server.js
Using i18n to get strings from appropriate JSON file for error messages from CardID
Also put the i18n config in it’s own file so we can use in app setup and controller config
=> PP-4098 - CardID messages need to be translatable too

Jenkinsfile, app/utils/add_proxy.js, app/utils/base_client.js, app/utils/base_client2.js, package-lock.json, test/unit/base_client_test.js, test/utils/add_proxy_test.js
As we will be sending requests to the nginx forward proxy, nginx will need
information about where to forward the request to. This will be got from the
host header.
@oswaldquek
=> PP-4213: Set the host header and redirect to forward proxy

Jenkinsfile
This should get the pay-frontend master build further ahead (it's failing at the moment).
@oswaldquek
=> PP-4213: Zap tests should run on a pay-scripts branch for now

Jenkinsfile, app/controllers/healthcheck_controller.js, app/router.js, app/utils/add_proxy.js, app/utils/base_client.js, app/utils/base_client2.js, package-lock.json, test/unit/base_client_test.js, test/utils/add_proxy_test.js
This puts back the forward proxy functionalities back into master as we think we have a working forward proxy nginx container now.
=> Pp 4213 revert the revert

Jenkinsfile, app/utils/add_proxy.js, app/utils/base_client2.js, test/utils/add_proxy_test.js
=> PP-4213: Set proxied protocol to http

.editorconfig, app/assets/javascripts/modules/form-card-type.js, app/assets/javascripts/modules/form-validation.js, app/controllers/charge_controller.js, app/views/charge.njk, locales/cy.json, locales/en.json, package-lock.json, test/controllers/charge_controller_test.js
This PR adds corporate surcharge client side javascript which dynamically displays surcharge information.
- Add corporate cards surcharge information to `/check_card` endpoint
- Add corporate cards surcharge messages to the card details client side JavaScript
- Fix `locales/*.json` formatting and add EditorConfig rule to ignore locale files
- Regenerate package-lock.json
with @danworth
=> PP-4124 Corporate surcharge client side JavaScript

package-lock.json, package.json
Removing Stratford-upon-Avon District Council logo
=> BAU - bump product page

Gruntfile.js, server.js
- Fixed the grunt file to just regenerate CSS
- Updated the css/js paths for development to not used staticify versions
=> PP-4253 - Live reloading of css wasnt working

app/assets/javascripts/modules/form-validation.js, app/controllers/charge_controller.js, app/services/normalise_charge.js, app/views/confirm.njk, app/views/includes/scripts.njk, test/test_helpers/test_helpers.js
- Refactor connector consumer to use corporate_card_surcharge
=> PP-4306 Refactor to use corporate_card_surcharge

package-lock.json, package.json
=> PP-4331 - Badge should be capitalised

app/services/clients/base_client/wrapper.js
Puts the hard work for proxy configuration back in, that I accidentally nuked when I copied over the new base client and wrapper.
=> PP-4361 Restores forward proxy capability which was accidentally wiped by the base client unification

package-lock.json, package.json
new product page release including roadmap updates https://github.com/alphagov/pay-product-page/releases/tag/2.1.56
=> BAU - new product page release including roadmap updates

package-lock.json, package.json
No more event-stream
https://github.com/remy/nodemon/commit/21e052eddf144b27a7c0eb9c603236707003d75d
=> BAU - Upgrade nodemon to remove malicious dependency event-stream@3.3.6

package-lock.json, package.json
releasing this - https://github.com/alphagov/pay-product-page/pull/97
=> BAU - release product page version 2.1.58

package-lock.json, package.json
releasing https://github.com/alphagov/pay-product-page/pull/98
=> BAU - release copy changes to roadmap

app/controllers/three_d_secure_controller.js, app/middleware/state_enforcer.js
- Added logging for state enforcer and 3dsAuthHandler to debug the Stripe payment failing issues
=> PP-4651 Logging for 3DS Controller & State enforcer

app/assets/sass/custom/north-yorkshire-county-council.scss
=> BAU - set max width on logo to stop it stretching

package-lock.json, package.json
A few updates have been made to copy on the product page, this bumps to that release.
=> BAU - bumping product page version

Jenkinsfile
- Check pact compatibility and tag pact (test) during master build
=> PP-4806 Check pact compatibility and tag pact during build

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/index.js, app/views/includes/scripts.njk, package.json, test/cypress/integration/web-payments/apple-pay.spec.js, test/test.env
Fairly similar to the Google Pay one, but `ApplePaySesssion` is a class so had to construct mock class to replicate behaviour client-side JS expects
=> PP-4816 - Apple Pay Cypress tests

test/fixtures/payment_fixtures.js
=> PP-4870 Remove `allowWebPayments`

app/assets/javascripts/browsered/web-payments/apple-pay.js
add in temporary debugging lines and removed duplicate complete call
=> PP-4914 apple temporary debugging

app/controllers/charge_controller.js, app/controllers/return_controller.js, app/utils/cookies.js, locales/en.json, test/unit/cookies_test.js
Deletes session[key] for all valid sessions, based on existence of encryption key, and the existence of relevant cookie on the request
=> PP-4394 Cookie deletion after capture/cancel

app/assets/javascripts/browsered/web-payments/apple-pay.js
- If auth fails with connector
- If auth fails to push to frontend controller
=> PP-4917 - Adding GA events for Apple Pay errors

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/assets/javascripts/browsered/web-payments/index.js, package.json
Fixed all warnings
Would recommend viewing without whitespace changes — https://github.com/alphagov/pay-frontend/pull/710/files?w=1
=> PP-4904 lint browser javascripts too

app/assets/javascripts/browsered/web-payments/google-pay.js, app/controllers/web-payments/handle-auth-response-controller.js, app/controllers/web-payments/payment-auth-request-controller.js
Logs on client and server side when Google Payment goes well, as server side we use same controllers for Apple and Google, these logs will partly resolve PP-4917 too
=> PP-4916 success monitoring for google pay

server.js
This should have never have been changed 🙈
I think Silvia and I were just making it easier to debug but shouldn’t
have ever shipped to production 🤦‍♂️
=> BAU - use minified JS

app/views/layout.njk
Same as https://github.com/alphagov/pay-products-ui/pull/257
=> PP-4972 -  remove unused ie8 boilerplate stuff

package-lock.json, package.json
Bump the product page version to pick up Katie's latest changes.
=> BAU bump product page

test/fixtures/wallet_payment_fixtures.js, test/unit/clients/connector_client_apple_authentication_tests.js, test/unit/clients/connector_client_google_authentication_tests.js
Test for authorisation success.
=> PP-4961: Pact test for Apple Pay

Gruntfile.js, app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/assets/javascripts/browsered/web-payments/index.js, app/assets/sass/modules/_payment-request.scss, app/views/charge.njk, app/views/includes/scripts.njk
Moving the check to see if Apple Pay is available to inline, this way it happens quicker so there is a less of a flash of things jumping around
=> PP-4917 performance improvements for apple pay

app/views/charge.njk
The if statement on the outside of a block doesnt effect what happens in
the block
=> PP-4917 - Apple pay check was happening all the time

test/unit/clients/adminusers_client_find_service_tests.js
Reference https://github.com/alphagov/pay-selfservice/pull/1272
TL;DR Pass method to Promise chain instead of immediately executing
=> PP-4970: Ensure function is passed to test promise

app/assets/javascripts/browsered/web-payments/apple-pay.js
Apple let users put anything in the email field, this makes sure its
legit.
I cant try this locally so I have no idea if it will work (and the docs
are rubbish) so would like to merge and try on test to see if it works.
Hence why I have left a log line because i imagine this wont work and
this will help me debug
=> PP-4917 - Validate users email to check its legit

app/utils/metrics.js, package-lock.json, package.json, server.js
Emit the Apple Pay merchant identity certificate's time-to-expiry (in
milliseconds) metric on server startup. 
There are few `logger.debug` lines which I will delete when I've verified it all works in the test environment.
=> PP-5023: Emit time to expiry metric

app/utils/metrics.js, package-lock.json, package.json, server.js
Reverts alphagov/pay-frontend#767
=> Revert "PP-5023: Emit time to expiry metric"

app/assets/javascripts/browsered/web-payments/apple-pay.js
https://stackoverflow.com/questions/49042645/in-applepay-js-need-to-display-an-error-message-on-the-paysheet
=> PP-4917 - need to pass the error into completePayment function

package.json
=> BAU — Release new 2.1.69 version of product page

package-lock.json, package.json, server.js
The idea is that an alert will be set up in splunk based on this log.
=> PP-5023: Log time till the Apple Pay Merchant Identity Cert expires

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/index.js, app/views/charge.njk
So we can better understand how digital wallet payments are performing
we are adding logging lines so that we can tell what they were presented
with and what they chose.
=> PP-4917 add more digital wallet logging

app/views/charge.njk, locales/cy.json, locales/en.json
Welsh translations pending, using english placeholders for now, no
service has welsh and web payments enabled so we’re fine for now.
=> PP-5078 - strings should come from json files so we can translate them

test/cypress/integration/card/payment.spec.js, test/cypress/integration/web-payments/apple-pay.spec.js, test/cypress/integration/web-payments/google-pay.spec.js, test/cypress/utils/apple-pay-js-api-stubs.js, test/cypress/utils/payment-request-api-stub.js
After review increasing test coverage
=> PP-5072 more digital wallet payment tests

locales/cy.json
=> PP-5078 Add Welsh translations for web payments

locales/cy.json
=> PP-5078 Fix apostrophes in Welsh translations

app/assets/javascripts/browsered/web-payments/format-card-types.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/assets/javascripts/browsered/web-payments/index.js, app/controllers/charge_controller.js, app/utils/google-pay-check-request.js, app/views/charge.njk
Move Google Pay check inline so it executes a lot earlier, eliminating the flash/reflow
=> PP-5146 - make google pay check quicker

app/services/countries.js, app/services/normalise_charge.js, app/views/charge.njk, test/cypress/integration/card/payment.spec.js, test/cypress/plugins/stubs.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment_fixtures.js
- refactor normalise_charge to add prefilled cardholder details
- add countryISO check and default to countries
- add cypress tests
with @nimalank7
=> PP-5087 refactor normalise charge to add prefilled card details

app/views/charge.njk
Google Pay async check :: 
* Currently checks if(Promise) -- this will always be true 
* Update to use Promise.then
Before merging/ testing: 
* This will introduce a wait before we know if Google Pay is available -- the user experience should be validated
=> BAU (pending ticket): Fix async Google pay check

Jenkinsfile
After extensive consultation it has been decided this is for the best.
=> PP-5191 Default run e2e tests to false on PR

app/controllers/charge_controller.js, app/controllers/return_controller.js, app/controllers/secure_controller.js, app/controllers/three_d_secure_controller.js, app/controllers/web-payments/handle-auth-response-controller.js, app/middleware/csrf.js, app/middleware/retrieve_charge.js, app/utils/logging.js
* Uniquely log all system errors with as much contextual information as possible 
* Correlation ID 
* Charge ID
* Logging pattern should make sense with existing methods 
* Pass all tests 
* Review logs in staging
=> PP-5190 Frontend system error logging

Gruntfile.js, app/assets/sass/application.scss, app/assets/sass/modules/_borders.scss, app/views/charge.njk, locales/cy.json, locales/en.json, package.json
=> PP-5226 - typographic heirarchy improvements

app/assets/sass/modules/_summary-panel.scss, app/views/charge.njk, app/views/confirm.njk
=> PP-5228 - update design of summary box

app/views/charge.njk, test/integration/charge_validation_ft_tests.js
=> PP-5247 - Use radios macro instead of hardcoded HTML

app/assets/sass/modules/_accepted-cards.scss, app/assets/sass/modules/_accessible-autocomplete.scss, app/assets/sass/modules/_button-reset.scss, app/views/charge.njk, app/views/confirm.njk, locales/cy.json
- Tweaking spacing and type sizes
- Also added screen reader text for apple/google pay buttons
=> PP-5225 - Design tweaks with Conor

app/assets/sass/modules/_button-reset.scss, app/views/charge.njk
Make CVV, month and year inputs the same width
=> PP-5225 even more design tweaks

package-lock.json, package.json
=> BAU Release product page with fixed link

package-lock.json, package.json
v2.1.76 wasn't built properly, so release next version which has intended change
=> BAU Release product page v2.1.77

package-lock.json, package.json
Releases https://github.com/alphagov/pay-product-page/pull/141 and https://github.com/alphagov/pay-product-page/pull/142
=> BAU - Thanks for everything Till.👏 Horray for new boss Katie 🙌

package-lock.json, package.json
Releasing https://github.com/alphagov/pay-product-page/pull/144
=> BAU - release digital wallet payment info pages

package-lock.json, package.json
Releases https://github.com/alphagov/pay-product-page/pull/148
=> BAU - release fix for enter spelling typo

package-lock.json, package.json
- Bump pay-js-commons to 2.9.0 from 2.6.0
=> Bump-pay-js-commons-to-2.9.0

package-lock.json, package.json
=> Bump-pay-js-commons-to-2.10.0

README.md
=> PP-5562: Document Worldpay DDC initiation URLs

test/integration/three_d_secure_ft_tests.js
- Adds logic to ensure the form is correctly configured relating to what
information is passed to it.
=> PP-5556 Add Test Logic For No Pares Param

test/cypress/test.env, test/test.env
=> Remove references to unused DISABLE_INTERNAL_HTTPS environment variable

package-lock.json, package.json
Release of updated content from https://github.com/alphagov/pay-product-page/pull/156
=> PP-5586 - bump product page version to 2.1.86

app/views/includes/analytics.njk, package-lock.json
See https://docs.google.com/document/d/1Scq-axCUknouQhKkf5ppqcqljeWSo62njL4p9qGcIjo/edit# to help verify this PR is correct.
=> bau: Send analytics to cross-gov Google Analytics

app/services/clients/connector_client.js, test/fixtures/payment_fixtures.js, test/unit/clients/connector_client_token_tests.js
=> PP-5620: Pact test for /v1/frontend/tokens/{tokenId} endpoint

app/controllers/secure_controller.js, app/models/token.js, app/paths.js, app/services/clients/connector_client.js, test/controllers/secure_controller_test.js, test/cypress/integration/card/email-typo.spec.js, test/cypress/integration/card/payment.spec.js, test/cypress/integration/web-payments/apple-pay.spec.js, test/cypress/integration/web-payments/google-pay.spec.js, test/cypress/plugins/stubs.js, test/cypress/utils/card-payment-stubs.js, test/models/token_test.js
=> PP-5620: Instead of deleting token, mark it as used

package-lock.json, package.json
In order to release this new page https://pay-product-page-test.cloudapps.digital/accessibility-statement/
=> PP-5653 - release 2.1.90 of product page

app/views/layout.njk
Must be deployed after https://github.com/alphagov/pay-product-page/pull/162
=> PP-5653 - add a link to statement in the footer

app/controllers/secure_controller.js, app/models/charge.js, test/controllers/secure_controller_test.js, test/cypress/integration/card/token-403.spec.js, test/cypress/plugins/stubs.js, test/cypress/utils/card-payment-stubs.js, test/models/charge_test.js
This will break the e2e test https://github.com/alphagov/pay-endtoend/blob/db0567f1ca5dcd67ce15a483adf2ddbe93fc9351/src/test/java/uk/gov/pay/endtoend/tests/publicapi/ProtectAgainstReplayAttackIT.java#L38-L43. Merge this PR first into master, then I'll raise a PR to fix the endtoend test.
=> Pp 5620 scenario3

.github/workflows/product-page.yml
The github-script thing wasn't working and it's easier to just do this.
=> REP: Use bash to update package.json in product page action

.github/workflows/product-page.yml
Fixes peter-evans/create-pull-request#36
=> REP: Update create pull request action

app/controllers/secure_controller.js, app/utils/logging.js
We've had some instances where the secure URL have been fetched more than once;
however we currently don't log the gateway account information which would be
useful to do some analysis on.
=> PP-5646: Extra information on system error logs

package-lock.json, package.json
This is an automatic PR triggered by a new pay-product-page release
=> ACTION: Update pay-product-page

package.json
_ applies custom branding for `The Coal Authority`
https://github.com/alphagov/pay-js-commons/pull/137
=> ZD#3812200 Bump pay-js-commons to v2.12.0

test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.spec.js, test/cypress/plugins/stubs.js
Fix flakey test which was going funny due to flawed logic in statement
that resolved to `false || true`
=> PP-5548 - Fix status logic in stub

app/utils/charge_validation_backend.js
This is entirely BAU, and just means that the card type is disabled for a gateway account. Log it as debug level as it isn't useful information to see in the logs.
=> PP-5758 Don't log error for card not supported

test/test_helpers/supress-logs.js
=> BAU Fix log suppress for unit tests

README.md, app/middleware/csp.js, app/routes.js, package-lock.json, package.json, test/middleware/csp_test.js
* introduce feature flags for csp behaviour switches
* apply csp if configured to environment is configured for it
=> PP-5846 Add CSP structure for card payment page

app/utils/cookies.js
=> PP-5851 Log when session variable deleted from cookie

app/middleware/csrf.js
Often this happens because the session cookie isn't present, rather than an issue with the CSRF. In this case, log a different line at info level.
In the case that the CSRF secret is actually missing, log the charge id and the url and referrer so we can more easily determine patterns around when this happens.
=> PP-5851 Log more info when CSRF secret missing

app/middleware/csp.js
- add some extra directives to card details page (ones we want to be specifically strict about)
- remove http google analytics exceptions
- add centinelapi exception to frame source
- sync child source to be that of frame source
=> PP-5882 add some extra directives to card details page

app/middleware/csp.js
- fix Worldpay test account url
=> PP-5884 fix WP test url

app/middleware/csp.js
- Added directive `defaultSrc` to Worldpay 3DS Flex CSP
- Removes directives that fallback to default-src if not defined.
=> PP-5930 Add defaultSrc for Worldpay3DSFlex iframe CSP

app/controllers/secure_controller.js
Add logging fields to the request in the secure controller and pass
these to the logger when we do logging.
=> PP-5762 Add logging fields for secure controller

package-lock.json, package.json
See https://github.com/alphagov/pay-product-page/commit/112535e4ffb6305e0a0547398067530a094da41b
=> PP-5950 Release new version of product page

package-lock.json, package.json
=> zd3873417: Update pay-js-commons

package-lock.json, package.json
Changes formatting of logo for Torbay and South Devon NHS Foundation
Trust
=> ZD-3873417 Bump pay-js-commons to 2.20.1

package-lock.json, package.json
Description:
- Pay product pages have been updated to 4.0.1 which removes information regarding Google Analytics cookies
=> PP-5977 Deploy pay product pages for removing cookie information

package-lock.json, package.json
Description:
- This updates pay product page to 4.0.2 to fix the pay product banner
=> BAU-Fix-pay-product-banner

package-lock.json, package.json
Relates to:
https://github.com/alphagov/pay-frontend/pull/1278
https://github.com/alphagov/pay-frontend/pull/1276
Incomplete zip issue, bump to latest.
=> BAU Bump product page to complete zip

.travis.yml
Adds a simple .travis.yml build configuration for running CI node build tasks. Also includes cypress tests.
=> Run builds on travis

manifest.yml
Adds a Cloud Foundry manifest.yml file to provide application runtime configuration
=> Add CF manifest.yml to run on PaaS

test/cypress/integration/card/payment-cancellation.spec.js, test/cypress/plugins/stubs.js, test/cypress/utils/card-payment-stubs.js
=> PP-6007: Cancel payment from card details page cypress test

test/cypress/integration/card/email-typo.spec.js, test/cypress/integration/card/enforce-views-to-state.spec.js, test/cypress/integration/card/payment.spec.js, test/cypress/integration/card/token-reuse.spec.js, test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.spec.js, test/cypress/utils/card-payment-stubs.js
=> PP-6007: Extract common functions to card-payment-stubs

test/cypress/integration/card/email-collection.spec.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment_fixtures.js
Added a mandatory email collection test too to cover our bases
=> PP-6007: Test for optional email collection

test/cypress/integration/card/email-collection.spec.js
=> PP-6007: Test for email collection mode OFF

test/cypress/integration/card/awaiting-auth.spec.js, test/cypress/plugins/stubs.js
=> PP-6007: Awaiting auth test

test/cypress/integration/card/card-details-page-validation.spec.js
=> PP-6007: Card details page validation test

app/utils/charge_validation_fields.js, test/utils/charge_validation_fields/email_field_test.js
- Relaxes the email validation to allow noncensecutive 11 digit emails
to pay
=> BAU Relax Email Validation

package-lock.json, package.json
- Updated to include latest Product Page release with the Support Text changes
=> PP-6191 Support Text Changes

package-lock.json, package.json
- Product Pages - update version to include missing Stripe copy
=> PP-6191 Product Pages - Update version

package-lock.json, package.json
=> BAU Bump pay-js-commons to 2.24.0

package-lock.json, package.json
=> PP-6181 Release new version of product page

package-lock.json, package.json
v4.1.0 had accidentally been released using out of date code.
=> PP-6181 use version 4.1.2 of the product page

package-lock.json, package.json
=> zd3927646: Update pay-js-commons

app/views/charge.njk
* Add <fieldset> and <legend> tags
=> PP-6083 Add Accessibility Tags to Expiry Date

app/assets/sass/modules/_input-confirm.scss, app/views/charge.njk
* Add 'word-break: break-all' CSS to break long e-mails onto multiple lines
=> PP-6230 Accessibility Issue with Email

app/controllers/charge_controller.js, app/controllers/return_controller.js, app/controllers/secure_controller.js, app/controllers/three_d_secure_controller.js, app/controllers/web-payments/handle-auth-response-controller.js, app/middleware/csrf.js, app/middleware/error_handlers.js, app/middleware/retrieve_charge.js, app/utils/logging.js, app/utils/response_router.js
Description:
- We want to be able to search in Splunk for when an error page has rendered and the reason why it has
- Logging message and error has been moved into the error response methods
Co-authored-by: nimalank7 <nimalan.kirubakaran@gmail.com>
=> PP-6240 Log common line when rendering error page

app/controllers/web-payments/payment-auth-request-controller.js, app/middleware/retrieve_charge.js, test/controllers/web-payments/payment-auth-request-controller.test.js, test/middleware/retrieve_charge_test.js
=> PP-5805: Remove aws xray from frontend

.dependabot/config.yml
* bump Javascript dependencies daily
* bump Docker dependencies weekly
=> BAU Dependabot configuration file

package-lock.json, package.json
Contains CSS change to remove horizontal scrollbar when cookie banner is shown
=> PP-6115 Use new version of product page

package-lock.json, package.json
=> PP-6246 Release version 4.2.0 of the product page

app/services/normalise_charge.js, test/integration/card_details_send_epdq_3ds2_data_ft_tests.js
Description:
- This PR sends the extra browser details required for ePDQ 3DS2 to Connector
with @nimalank7
=> PP-6361 Send ePDQ 3DS2 data to connector

app/controllers/three_d_secure_controller.js
Description:
- We want to log the information we send to the card issuer as well as Worldpay so that we can diagnose 3DS retries.
=> PP-6380 - Log more information for Worldpay 3DS

package-lock.json, package.json
- Bumps pay-product-page to v4.3.0 which enables cookie banner on product pages
=> PP-6271 Bump pay-product-page version to 4.3.0

package-lock.json, package.json
=> PP-6443 Bump Product Page version

package-lock.json, package.json
=> PP-6443 - Bump Product page

app/views/charge.njk, app/views/confirm.njk
- Update charge & confirm template
=> PP-6231 ASIDE tag - move out of the MAIN tag

package-lock.json, package.json
=> PP-6243 Bump Product Page to 4.3.4

app/assets/sass/modules/_web-payments.scss, app/views/charge.njk
- Update SCSS Styling to toggle when to show Apple/Google Pay headings & buttons
- Update charge.njk to use new styles
=> PP-6388 Fix styling when showing Apple Pay and/or Google Pay buttons

package-lock.json, package.json
=> BAU Bump JS commons to 2.29.0

package-lock.json, package.json
=> BAU Bump Pay JS commons to 2.30.0

package-lock.json, package.json
=> BAU Bump Pay JS commons to 2.32.0

package-lock.json, package.json
Contains a page with information about what being a responsible person means
=> PP-6665 Release version 4.4.0 of pay-product-page

package.json
- update product pages to the new release version
=> PP-6678 update product pages version

Gruntfile.js, app/assets/robots.txt
- stop crawlers collecting our payment page urls
=> PP-6694 stop crawlers

test/fixtures/wallet_payment_fixtures.js, test/unit/clients/connector_client_apple_authentication_tests.js
Description:
- Pact test to ensure that the integration between Frontend and Connector is not broken
=> PP-6614 - Pact test for Apple Pay normalised last four digits

test/fixtures/wallet_payment_fixtures.js, test/unit/clients/connector_client_google_authentication_tests.js
Description:
- Pact test to ensure that the integration between Frontend and Connector is not broken
=> PP-6614 - Pact test for Google Pay normalised last four digits

app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js
Description:
- If the displayName is less than four characters then map the last four digits to an empty string.
- If the last four characters of the displayName are not numeric then map the last four digits to an empty string.
=> PP-6614 Normalise the last four digits for Google Pay

package-lock.json, package.json
- update product page to latest release.
=> PP-6805 update product page to 4.5.0

package-lock.json, package.json
- release the minor update of product pages
=> PP-6805 release product page 4.5.1

package-lock.json, package.json
- upgrade product page to 4.6.0
=> PP-6821 upgrade product pages

package-lock.json, package.json
- upgrade pages to new version
=> PP-6821 upgrade product pages to 4.6.1

package-lock.json, package.json
For Planning and Building Services Edinburgh.
=> zd4186401: Custom branding

package-lock.json, package.json
=> zd4195581: Custom branding for Adur & Worthing Council

.secrets.baseline, app/services/clients/connector_client.js, package-lock.json, package.json
Reverts alphagov/pay-frontend#1736.
=> Revert "Revert "PP-4733: Spike sending metric to HG""

app/services/clients/connector_client.js, package-lock.json, package.json
Reverting as we've proved the spike in staging.
Reverts alphagov/pay-frontend#1744
=> Revert "PP-4733: Spike sending metrics to hosted graphite"

package-lock.json, package.json
=> PP-6992: Amend FCO logo to the FCDO logo

.secrets.baseline, app/metrics/graphite_reporter.js, app/services/clients/connector_client.js, package-lock.json, package.json, test/metrics/graphite_reporter_test.js
Add graphite reporter. Only counters are envisaged for now.
=> PP-6995: Add graphite reporter

app/services/clients/connector_client.js
* no need to return an implicit Promise
* get rid of anonymous functions
=> PP-6995: Simplify connector client

app/services/clients/adminusers_client.js
=> PP-6995: Fix build

app/models/card.js, app/services/clients/adminusers_client.js, app/services/clients/connector_client.js
Emit metrics for all status codes to make it easier to have confidence in what is going on.
=> PP-6995: Log all status codes

package-lock.json, package.json
=> PP-7089 Update product page to version 4.6.3

package-lock.json, package.json
=> PP-7088 Update Product Pages to version 4.6.4

app/routes.js
Description:
- Added middlewareStackFor3dsWithSessionValidation in order to  clean up the code in readiness for removing session check from 3ds iframe posts.
=> PP-7118 normalise middleware

package-lock.json, package.json
Version 4.6.7 of the product page updates the Google site verification.
=> BAU — Update the product page to 4.6.7

package-lock.json, package.json
- Includes accessibility statement updates
https://github.com/alphagov/pay-product-page/pull/274
=> BAU - Bump product page to 4.7.0

test/unit/session_test.js
Description:
- Missed lint ignore on one of the tests.
=> PP-7118 move session cookie validation lint fix

app/routes.js, test/integration/three_d_secure_ft_tests.js, test/test_helpers/test_helpers.js
Description:
- Remove session cookie validation for /card_details/:chargeId/3ds_required_in & /card_details/:chargeId/3ds_required_in requests
=> PP 7118 remove 3ds in cookie validation

package-lock.json, package.json
=> BAU Bump product pages to 4.7.1

package-lock.json, package.json
=> Bump pay-js-commons to 2.39.0

package-lock.json, package.json
=> Bump pay-js-commons to 2.40.0

package-lock.json, package.json
=> BAU Release product page version 4.7.2

app/assets/javascripts/browsered/web-payments/helpers.js, app/utils/google-pay-check-request.js
Reverts alphagov/pay-frontend#1837
=> Revert "PP-7192: Disable PAN_ONLY Google transactions"

Dockerfile
Reverts alphagov/pay-frontend#1863
=> Revert "Bump node from 12.19.0-alpine3.12 to 15.0.1-alpine3.12"

package-lock.json, package.json
=> BAU Update Product Pages

app/controllers/web-payments/payment-auth-request-controller.js
This is for testing PP-7351. Unfortunately I've spent a couple of hours trying
to get the Google Pay stuff to show in a local docker environment, so I'm just
going to see the logs in the test-12 environment. This will not be deployed to
staging/prod.
=> bau: Temporarily log things

app/controllers/web-payments/payment-auth-request-controller.js
Reverts alphagov/pay-frontend#1893
=> Revert "bau: Temporarily log things"

package-lock.json, package.json
=> BAU Bump Product Page to 4.7.5

Dockerfile, docker/build_and_test.Dockerfile
=> PP-7602 fix upgrade to node 12.20.1

app/controllers/charge_controller.js, test/cypress/integration/web-payments/apple-pay.spec.js
Temporarily enabling this to test the new certificate works.
=> PP-7614: Temporarily only enable Apple Pay for our live account

app/controllers/charge_controller.js, test/cypress/integration/web-payments/apple-pay.spec.js
Reverts alphagov/pay-frontend#1988
=> Revert "PP-7614: Temporarily only enable Apple Pay for our live account"

package-lock.json, package.json
Reverts alphagov/pay-frontend#1960
=> Revert "Bump envfile from 5.1.0 to 6.14.0"

package-lock.json, package.json
=> PP-7701 Update `pay-product-pages` to 4.7.9

package-lock.json, package.json
Reverts alphagov/pay-frontend#2018
=> Revert "Bump nunjucks from 3.2.2 to 3.2.3"

package-lock.json, package.json
- Bumps product page to latest version https://github.com/alphagov/pay-product-page/compare/4.7.9...4.8.0
=> PP-7766 Bump pay-product-page from 4.7.9 to 4.8.0

package-lock.json, package.json
This will include the custom branding for Rushmoor. 3.0.7 -> 3.0.8
=> BAU Bump JS Commons

package-lock.json, package.json
- upgrade to new version of pay-product-page
=> PP-7725 upgrade product page to 4.8.1

package-lock.json, package.json
- upgrade to new version of pay-product-page
=> PP-7725 upgrade product page to 4.8.2

package-lock.json, package.json
=> PP-7923 Release new version of product pages

package-lock.json, package.json
=> PP-7844 Update product page

.env.example, .gitignore, .vscode/launch.json, README.md, package.json, start-dev.js
=> PP-7965 Add files for debugging locally

README.md
=> PP-7965 Small README change

package-lock.json, package.json
=> PP-7931 Bump Product Page to 4.8.5

package-lock.json, package.json
Related changes
- https://github.com/alphagov/pay-product-page/pull/312
- https://github.com/alphagov/pay-product-page/pull/313
=> PP-8008 Bump product page version from 4.8.5 to 4.8.7

package-lock.json, package.json
=> PP-7931 Bump product page to 4.8.8

package-lock.json, package.json
=> PP-8015 Update product-pages to 4.8.10

package-lock.json, package.json
- Updates performance page https://github.com/alphagov/pay-product-page/compare/4.8.10...4.8.11
=> Bump pay-product-page from 4.8.10 to 4.8.11

package-lock.json, package.json
Description:
- pay-product-page has been updated to 4.18.3 here https://github.com/alphagov/pay-product-page/commit/15a951ee47f8d3f1ef132eb29caf137fae7b11d1
- PR updates frontend to deploy this version
=> PP-8089 - Update product page to release cost benefit analysis page

package-lock.json, package.json
- upgrade to latest product page to show latest performance report
=> BAU upgrade product page version to 4.8.14

app/controllers/charge.controller.js
Inconsequential change for the mere purpose of creating a new frontend build.
No valid dependabot PRs at the moment.
=> PP-8110: Create new frontend build

package-lock.json, package.json
- update product page dependency to latest release
=> BAU update product page to 4.8.15

package-lock.json, package.json
- update product page dependency to latest release
=> BAU update product page to 4.8.16

package-lock.json, package.json
Description:
- Corresponds to https://github.com/alphagov/pay-product-page/pull/332 for content change
=> PP-8101 - Deploy product page version 4.8.17

package-lock.json, package.json
=> BAU Update product page

package-lock.json, package.json
- upgrade product page to 4.8.19
=> BAU upgrade product page

package-lock.json, package.json
=> BAU update product page to 4.8.20

package-lock.json, package.json
=> BAU update product page to 4.8.21

package-lock.json, package.json
=> BAU update performance report 22 06 21

package-lock.json, package.json
- upgrade product page to latest
=> BAU upgrade product page to 4.8.23

package-lock.json, package.json
=> BAU update product page to 4.8.24

package-lock.json, package.json
- update product page to 4.8.25
=> BAU update product page to 4.8.25

package-lock.json, package.json
=> BAU update product page to 4.8.26

package-lock.json, package.json
Description:
- Deploys pay product page with content change
=> PP-8010 - Update pay product page to version 4.8.27

package-lock.json, package.json
- BAU update product page to 4.8.28
=> BAU update product page to 4.8.28

.github/workflows/run-tests.yml
=> PP-8224 Pin github action versions

package-lock.json, package.json
- update product page to 4.8.29
=> BAU update product page to 4.8.29

package-lock.json, package.json
- update product page to 4.8.32
=> BAU update product page to 4.8.32

package-lock.json, package.json
- update product page to 4.8.33
=> BAU update product page to 4.8.33

package-lock.json, package.json
- update product page to 4.8.34
=> BAU update product page to 4.8.34

package-lock.json, package.json
- update product page to 4.8.35
=> BAU update product page to 4.8.35

package-lock.json, package.json, test/test-helpers/pact/pact-base.js, test/unit/clients/adminusers-client-find-service.pact.test.js, test/unit/clients/connector-client-apple-authentication.pact.test.js, test/unit/clients/connector-client-charge.pact.test.js, test/unit/clients/connector-client-google-authentication.pact.test.js, test/unit/clients/connector-client-token.pact.test.js, test/unit/clients/connector-client-worldpay-3ds-flex.pact.test.js
- removes pact@4.3.2 package which is deprecated https://www.npmjs.com/package/pact
- Added new dependency of pact `@pact-foundation/pact`
- and related changes
=> PP-8575 Update pact dependency

package-lock.json, package.json
- BAU update product page to 4.8.36
=> BAU update product page to 4.8.36

package-lock.json, package.json
- https://github.com/alphagov/pay-product-page/pull/383
- commit https://github.com/alphagov/pay-product-page/commit/b557eeed04fb9a3f62f67c4888e8afce12e18076
=> PP-8691 Bump pay-product-page to 4.8.37

package-lock.json, package.json
- BAU update product page to 4.8.38
=> BAU update product page to 4.8.38

package-lock.json, package.json
- BAU update product page to 4.8.39
=> BAU update product page to 4.8.39

package-lock.json, package.json
- update product page to 4.9.5
=> BAU update product page to 4.9.5

package-lock.json
Reverts alphagov/pay-frontend#2491
=> Revert "Bump sinon from 12.0.0 to 12.0.1"

app/assets/javascripts/browsered/form-validation.js, app/controllers/charge.controller.js, app/views/includes/scripts.njk, test/fixtures/payment.fixtures.js
Description:
- Removes prepaidCredit option for corporate surcharge
- Doesn't look like any tests need to be modified
=> PP-8785 - Remove prepaid corporate credit

package-lock.json, package.json
- update product page to 4.9.7
=> BAU update product page to 4.9.7

package-lock.json, package.json
- update product page to 4.9.8
=> BAU update product page to 4.9.8

Dockerfile
`s/npm install/npm ci/`
```docker build .```
=> PP-8901 Use `npm ci` in dockerfiles

package-lock.json, package.json
- update product page to 4.9.10
=> BAU update product page to 4.9.10

package-lock.json, package.json
- update product page to 4.9.11
=> BAU update product page to 4.9.11

package-lock.json, package.json
- update product page to 4.9.12
=> BAU update product page to 4.9.12

package-lock.json, package.json
- update product page to 4.9.13
=> BAU update product page to 4.9.13

package-lock.json, package.json
- update product page to 4.9.14
=> BAU update product page to 4.9.14

package-lock.json, package.json
- update product page to 4.9.15
=> BAU update product page to 4.9.15

package-lock.json, package.json
- update product page to 4.9.20
=> BAU update product page to 4.9.20

package-lock.json, package.json
- update product page to 4.9.21
=> BAU update product page to 4.9.21

app/views/layout.njk, package-lock.json, package.json
Also release new version of product page with the same link fixed
=> PP-9092 Fix crown copyright link

package-lock.json, package.json
- update product page to 4.9.24
=> BAU update product page to 4.9.24

package-lock.json, package.json
- update product page to 4.9.25
=> BAU update product page to 4.9.25

package-lock.json, package.json
- update product page to 4.9.26
=> BAU update product page to 4.9.26

package-lock.json, package.json
- latest product pages include the changed SRO page
=> PP-9285 update to latest product page

package-lock.json, package.json
- update product page to 4.9.28
=> BAU update product page to 4.9.28

test/services/normalise-charge.test.js
Adds additional unit test.
(I couldn't figure out how to make this work as an integration test but let me know if someone wants to pair on this)
Tests should make sense and pass
=> PP-9314: added test for non-present headers

.github/workflows/post-merge.yml, .github/workflows/run-tests.yml, bin/publish-pacts.js, package.json
On a post merge to master:
- publish the pact
- run frontend as consumer pact test
**_NOTE: Whoever merges to master, please copy the above description ^ in the squash and merge commit message box._**
=> PP-9238: Frontend build post merge to master

package-lock.json, package.json
- update product page to 4.9.29
=> BAU update product page to 4.9.29

package-lock.json
Update the package lock file to enforce overrides
=> PP-9148 update the package lock file to enforce overrides

package-lock.json, package.json
- update product page to 4.9.31
=> BAU update product page to 4.9.31

package-lock.json, package.json
Reverts alphagov/pay-frontend#2779
=> Revert "Bump superagent from 7.1.1 to 7.1.2"

package-lock.json, package.json
- update product page to 4.9.32
=> BAU update product page to 4.9.32

package-lock.json, package.json
- update product page to 4.9.33
=> BAU update product page to 4.9.33

package-lock.json, package.json
- update product page to 4.9.34
=> BAU update product page to 4.9.34

package-lock.json, package.json
- update product page to 4.9.35
=> BAU update product page to 4.9.35

app/services/normalise-charge.js, app/views/charge.njk, test/utils/normalise.test.js
front end changes to display agreement details on payment screen
agreement description for recurring card payment (TBD
=> PP 9333 content changes for setting up payment instrument during payment

package-lock.json, package.json
- update product page to 4.9.36
=> BAU update product page to 4.9.36

package-lock.json, package.json
- update product page to 4.9.39
=> BAU update product page to 4.9.39

package-lock.json, package.json
- update product page to 4.9.41
=> BAU update product page to 4.9.41

package-lock.json, package.json
- update product page to 4.9.42
=> BAU update product page to 4.9.42

package-lock.json, package.json
- update product page to 4.9.43
=> BAU update product page to 4.9.43

package-lock.json, package.json
- update product page to 4.9.45
=> BAU update product page to 4.9.45

package-lock.json, package.json
- update product page to 4.9.46
=> BAU update product page to 4.9.46

package-lock.json, package.json
- update product page to 4.9.47
=> BAU update product page to 4.9.47

package-lock.json, package.json
- update product page to 4.9.48
=> BAU update product page to 4.9.48

package-lock.json, package.json
- updating product page to the latest version.
=> PP-9744 update product page version

package-lock.json, package.json
- update product page to 4.10.2
=> BAU update product page to 4.10.2

package-lock.json, package.json
=> BAU bump pay-js-commons -> 3.6.2

package-lock.json, package.json
- update product page to 4.10.3
=> BAU update product page to 4.10.3

package-lock.json, package.json
- update product page to 4.10.4
=> BAU update product page to 4.10.4

package-lock.json, package.json
- update product page to 4.10.5
=> BAU update product page to 4.10.5

package-lock.json, package.json
- deploy product page for new payment link journey (PP-9985)
=> PP-8971 deploy product page

package-lock.json, package.json
- update product page to 4.10.7
=> BAU update product page to 4.10.7

package-lock.json, package.json
- update product page to 4.10.9
=> BAU update product page to 4.10.9

package-lock.json, package.json
- update product page to 4.10.10
=> BAU update product page to 4.10.10

package-lock.json, package.json
- update product page to 4.10.11
=> BAU update product page to 4.10.11

package-lock.json, package.json
- update product page to 4.10.12
=> BAU update product page to 4.10.12

package-lock.json, package.json
- update product page to 4.11.1
=> BAU update product page to 4.11.1

package-lock.json, package.json
- Updates product page for missing SRO info https://github.com/alphagov/pay-product-page/commit/3cc5733f5a05e26bf90f7fdbf989dbbd1557d542
=> PP-10083 update product page to 4.11.2

package-lock.json, package.json
- update product page to 4.11.3
=> BAU update product page to 4.11.3

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js
- check source when handling event message
=> PP-10077 add condition for ebent listener

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js
Reverts alphagov/pay-frontend#3106
=> Revert "PP-10077 add condition for ebent listener"

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js
Reverts alphagov/pay-frontend#3107
=> Revert "Revert "PP-10077 add condition for event listener""

app/utils/response-router.js, test/utils/response-router.test.js
Hopefully this one will get picked up by Concourse 😸
=> PP-10204: Salute to David Heath

app/assets/javascripts/browsered/web-payments/google-pay.js
If appropriate, perform Worldpay 3DS Flex device data collection for Google Pay payments.
with @SandorArpa and @iqbalgds
=> PP-10077 Perform 3DS Flex device data collection for Google Pay

package-lock.json, package.json
- update product page to 4.11.4
=> BAU update product page to 4.11.4

package-lock.json, package.json, test/cypress/integration/web-payments/apple-pay.cy.test.js
- upgrading cypress due to functionality that only exist in v7 for intercepting multiple times
- update breaking changes
=> PP-10077 upgrade cypress to 7.7

package-lock.json, package.json
- update product page to 4.11.5
=> BAU update product page to 4.11.5

app/assets/javascripts/browsered/web-payments/google-pay.js, test/cypress/integration/web-payments/google-pay.cy.test.js
Remove the overcomplicated heroics that try to recreate the Worldpay 3DS Flex device data collection iframe for Google Pay if both device data collection and the Google Pay authorisation Ajax fetch fail first time. On subsequent attempts, just try the authorisation without a device data collection result.
It seems this never actually worked and it’s way too much code and maintenace effort for an edge case where we’re already in a failure mode.
We now store the device data collection status on the global `Charge` object and use its presence to determine if we have already tried to perform device data collection. We no longer check if the device data collection iframe has been navigated away to another origin as this should be now unnecessary. If the stored device data collection status and …
=> PP-10077 Do not try DDC again if Google Pay auth fetch call fails

package-lock.json, package.json
- bump pay-js-commons that contains custom branding for Neath Port Talbot Council
=> ZD-5110969 bump pay-js-commons to 3.8.2

package-lock.json, package.json
- update product page to 4.12.2
=> BAU update product page to 4.12.2

.secrets.baseline, app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js, test/controllers/web-payments/apple-pay/normalise-apple-pay-payload.test.js
- Used lodash to pick required properties
- Updated tests for logging
=> PP10278 Apple Pay: Simplify logging properties

package-lock.json, package.json
- update product page to 4.12.4
=> BAU update product page to 4.12.4

package-lock.json, package.json
- update product page to 4.12.5
=>  BAU update product page to 4.12.5

package-lock.json, package.json
- update product page to 4.12.6
=> BAU update product page to 4.12.6

package-lock.json, package.json
- update product page to 4.12.7
=> BAU update product page to 4.12.7

package-lock.json, package.json
- update product page to 4.12.9
=> BAU update product page to 4.12.9

package-lock.json, package.json
- update product page to 4.12.10
=> BAU update product page to 4.12.10

package-lock.json, package.json
- update product page to 4.12.11
=> BAU update product page to 4.12.11

package-lock.json, package.json
- update product page to 4.12.12
=> BAU update product page to 4.12.12

package-lock.json, package.json
- update product page to 4.12.14
=> BAU update product page to 4.12.14

package-lock.json, package.json
- update product page to 4.12.15
=> BAU update product page to 4.12.15

package-lock.json, package.json
- update product page to 4.12.16
=> BAU update product page to 4.12.16

package-lock.json, package.json
- Pick up new Privacy page updates.
=> PP-10242 Product page - bump to 4.12.18

package-lock.json, package.json
- update product page to 4.12.19
=> BAU update product page to 4.12.19

package-lock.json, package.json
- update product page to 4.12.20
=> BAU update product page to 4.12.20

.github/workflows/run-tests.yml
Located and replaced all usages of set-output commands in our workflows
=> PP-10675:replaced all usages of set-output

package-lock.json, package.json
- update product page to 4.12.26
=> BAU update product page to 4.12.26

package-lock.json, package.json
- update product page to 4.12.28
=> BAU update product page to 4.12.28

package-lock.json, package.json
=> BAU bump `pay-js-commons` -> 3.8.7

package-lock.json, package.json
- update product page to 4.12.30
=> BAU update product page to 4.12.30

package-lock.json, package.json
- update product page to 4.12.33
=> BAU update product page to 4.12.33

package-lock.json, package.json
- update product page to 4.12.43
=> BAU update product page to 4.12.43

package-lock.json, package.json
- update product page to 4.12.46
=> BAU update product page to 4.12.46

package-lock.json, package.json
=> ZD-5313486 wealden custom branding

package-lock.json, package.json
- update product page to 4.12.55
=> BAU update product page to 4.12.55

package-lock.json, package.json
- update product page to 4.12.59
=> BAU update product page to 4.12.59

package-lock.json, package.json
This contains custom branding for Runnymede Borough Council.
=> ZD-532159 Update to pay-js-commons version 3.8.10

.env.example, README.md, app/controllers/charge.controller.js, app/controllers/web-payments/apple-pay/merchant-validation.controller.js, package-lock.json, test/controllers/charge.controller.test.js, test/cypress/test.env, test/unit/charge.controller.test.js
- added ability to toggle wallet payment functions via environment variable
=> PP-10944 wallet payments environment toggle

package-lock.json, package.json
=> ZD-5357596: Bump pay-js-commons to 3.9.0

test/cypress/integration/card/email-typo.cy.test.js
=> PP-10904 Make email typo Cypress tests standalone

test/cypress/integration/card/enforce-views-to-state.cy.test.js
=> PP-10904 Make enforce views to state Cypress tests standalone

test/cypress/integration/card/token-reuse.cy.test.js
=> PP-10904 Make token reuse Cypress tests standalone

test/cypress/integration/web-payments/google-pay.cy.test.js
=> PP-10904 Make Google pay Cypress tests standalone

package-lock.json, package.json
-  Bump pay-js-commons to 3.10.0
=> zd-5365276-bump-js-commons

package-lock.json, package.json, test/test-helpers/test-env.js
One less dev dependency to deal with, and a simpler setup.
See equivalent PRs for Products UI https://github.com/alphagov/pay-products-ui/pull/2072 and Selfservice https://github.com/alphagov/pay-selfservice/pull/4029
=> BAU: Replace envfile with dotenv

package-lock.json, package.json
This version contains custom branding for Oswestry Town Council.
=> ZD-5424472 Update Pay JS Commons version to 3.11.2

.github/dependabot.yml
This format really does make it more obvious how many major versions behind we are...
=> BAU: Iterate dependabot.yml with more ignored versions

app/views/charge.njk, package-lock.json, package.json
- Update NPM module
- Minor updates to the hint text used on the charge page.
=> PP-10847 Upgrade to DSv4

app/controllers/web-payments/payment-auth-request.controller.js, app/services/clients/connector.client.js, test/controllers/web-payments/payment-auth-request.controller.test.js, test/unit/clients/connector-client-apple-authentication.pact.test.js, test/unit/clients/connector-client-google-authentication.pact.test.js
Fix payment-auth-request.controller.js so that it is successfully able to get the payment provider, in order to construct the URL correctly for Google Pay payments
=> PP-11494 Fix Google Pay authorisation

test/unit/clients/connector-client-apple-authentication.pact.test.js, test/unit/clients/connector-client-google-authentication.pact.test.js
- update wallet pact test to check for return of 402 for an auth error
- re-enable pact tests
=> PP-11470 re-enable and update pact tests

package-lock.json, package.json
- Pick up the latest updates to custom branding
=> PP-11040 Bump pay-js-commons

test/unit/clients/connector-client-sandbox-google-pay-authentication.pact.test.js
Add Pact test that checks a 400 response code is returned with a request body containing "error_identifier"="AUTHORISATION_REJECTED" for a declined Google Pay payment
=> PP-11578 Add pact test for declined Google Pay payment

package-lock.json, package.json, test/test-helpers/pact/pact-proxy.js
- Upgrades pact JS library to the latest
- Replace pact-node library with pact-core
=> PP-12027 Upgrade pact library

bin/publish-pacts.js
- Use pact-core to publish pacts
=> PP-12027 Fix publishing pacts

package-lock.json, package.json
To release service custom branding
=> ZD-5604893 Bump pay-js-commons to version 4.0.13

app/middleware/csp.js, app/routes.js, package-lock.json, package.json, server.js, test/middleware/csp.test.js
Update csp.js to include a JSON object containing csp endoint info as per the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to).
=> Add endpoint JSON info

app/services/normalise-charge.js, app/views/charge.njk, test/cypress/integration/web-payments/apple-pay.test.cy.js, test/cypress/integration/web-payments/google-pay.test.cy.js
- If service is moto, do not show wallet payment options
=> PP-12084 Do not show wallet options for moto payments

app/middleware/csp.js
=> PP-11850 enclose reporting endpoint url in quotes

app/middleware/csp.js, app/routes.js, test/middleware/csp.test.js
- support chrome reporting api for csp violations
=> PP-11850 update csp middleware

app/middleware/csp.js, test/middleware/csp.test.js
- updated csp middleware to support csp level 3 directives
=> PP-11850 support csp level 3

app/controllers/healthcheck.controller.js, app/services/clients/base/config.js, app/services/clients/base/config.test.js, app/services/clients/base/request-context.js, app/services/clients/base/request-logger.js, package-lock.json, package.json, server.js
- Uses the Axios base client from `pay-js-commons`.
=> PP-11683 Update healthcheck controller to use Axios

app/models/card.js, app/services/clients/cardid.client.js
https://payments-platform.atlassian.net/browse/PP-11682
- Add axios-base-client from latest pay-js-commons.
- Import config files.
- Remove ‘base.client’ reference.
- All automated tests should pass preferably without the need to be amended.
- Existing functionality should remain unaffected.
=> PP-11682 Replace 'request' package with 'axios' for 'cardid.client'.

app/services/clients/adminusers.client.js
- Update to use the `axios base client` from `pay-js-commons`.
- Ensured all existing tests are working.
=> PP-11682 Update `admin users client` to use axios base client

test/unit/clients/connector-axios-client-charge.pact.test.js
- Updated the test to work with the connector Axios client.
=> PP-11682 Add connector charge pact for the new Axios connector client

test/unit/clients/connector-axios-client-stripe-google-pay-authorisation.pact.test.js
- Update the existing pact test to work with the new connector Axios client
=> PP-11682 Add Stripe Google pay pact test for new connector Axios client

test/unit/clients/connector-axios-client-token.pact.test.js
- Update the existing pact test to work with the new connector Axios client
=> PP-11682 Add tokens pact test for new connector Axios client

test/unit/clients/connector-axios-client-worldpay-3ds-flex.pact.test.js
- Update the existing pact test to work with the new connector Axios client
=> PP-11682 Add Worldpay flex pact test for new connector Axios client

test/unit/clients/connector-axios-client-worldpay-google-pay-authorisation.pact.test.js
- Update the existing pact test to work with the new connector Axios client
=> PP-11682 Add Worldpay Google pay pact test for new connector Axios client

app/controllers/web-payments/payment-auth-request.controller.js, test/controllers/web-payments/payment-auth-request.controller.test.js
- Update to use the new connector axios client.
=> PP-11682 Update `update payment auth request controller`

app/controllers/web-payments/payment-auth-request.controller.js
- Update to use the new Axios connector client.
=> PP-11682 Update payment auth controller

app/controllers/three-d-secure.controller.js
- Update the controller to use Axios connector client.
=> PP-11682 Update 3D secure controller

app/models/token.js, test/models/token.test.js
- So that it uses the new connector axios client.
- Removing the test for the correlation id in the headers, this is something that will be update as part of: https://payments-platform.atlassian.net/browse/PP-12833
=> PP-11682 - Update token model

app/models/charge.js, test/integration/charge-status.ft.test.js
- Update to use the axios base client from pay-js-commons
=> PP-11682 Update charge model to use axios connector client

app/controllers/charge.controller.js, test/controllers/charge-controller-create.test.js
- Update controller to use the axios base client
- Update tests
=> PP11682 Update charge controller - axios

test/controllers/charge.controller.test.js
- Fix reference to proxy require
- Update to use `connector-axios.client`
=> PP-11682 - Update charge controller test

app/controllers/return.controller.js, app/utils/session.js, test/integration/card-details-errors.ft.test.js
=> PP-12546 remove any remaining compatibility code

package-lock.json, package.json
update pay-js-commons to 6.0.14
=> ZD-5942688 update pay-js-commons

package-lock.json, package.json
- This will use the updated aria fields and fix a issue detected by an accessibility audit.
=> PP-13173 Bump the `country autocomplets`

package-lock.json, package.json, test/cypress/plugins/index.js
Added the integration enabled by https://github.com/alphagov/pay-run-amock/pull/8
=> PP-13236: Added debugger integration.

package-lock.json, package.json
-  Needed for Custom branding
- https://govuk.zendesk.com/agent/tickets/5983194
=> ZD-5983194 Update Pay js commons

package-lock.json, package.json
- Required for custom branding
- Scottish gov payments
- Health Services Safety Investigations Body (HSSIB)
=> ZD-6032459 & ZD-6017555 - bump pay js commons

package-lock.json, package.json
- point to latest pay-js-commons to pick up image and scss for custom branding request.
=> ZD-6053016 point to latest pay-js-commons

package-lock.json, package.json
https://govuk.zendesk.com/agent/tickets/6061195
=> ZD-6061195 Use latest Pay-JS-commons

package-lock.json, package.json
Updating to use latest pay-js-commons after custom branding update.
=> Update to use latest js commons

package-lock.json, package.json
Needed for new custom branding, new version of pay-js-commons
=> ZD-6099831: Bump pay-js-commons

package-lock.json, package.json
- Pick up the latest branding updates.
=> PP-13898 Bump govuk-frontend from the design system

package-lock.json, package.json
- Pick up the latests custom branding CSS changes needed for the new branding.
=> PP-13898 Bump pay-js-commons

package-lock.json, package.json
- bump pay-js-commons to version 7.0.13
=> ZD-6181131 Bump pay-js-commons

package-lock.json, package.json
=> Bump js-commons to v 7.0.15

package-lock.json, package.json
New version of pay-js-commons.
=> ZD-6208926 Custom Branding for Surrey County Council
