app/assets/javascripts/modules/form-card-type.js, app/views/charge.html
Added in a couple of functions to set how the length of number allowed in the CVC/CVV input depending on which card type is detected. 
`input[type="number"]` is not compatible with the `maxlength` atrribute so I wrote a function to polyfill this. For older browsers that ignore `input[type="number"]` and fallback to `input[type="text"]` the `maxlength` property will work as expected
=> PP-2367 - Added JS to switch how many digits are allowed in CVC depending on card type

app/utils/accessible-autocomplete.js
Wrapped JS in check for element
so that it doesn’t error when element doesn’t exist
=> PP-2508 - wrapped JS in check for element 

app/models/Service.class.js, test/fixtures/service_fixtures.js, test/unit/clients/adminusers_client_find_service_tests.js
For now, we are expecting/forcing to use only the following properties (`image_url` and `css_url`).
This is as per discussion with @jonheslop, where its better to have multiple attributes, than having everything loaded in one CSS. This allows us to expand to more customisations (e.g. two images) in future.
=> PP-2453 Make `customBranding` to expect/store JSON.

Jenkinsfile
- reverts the jenkins library branch to master (cleaning up backward compat fix in #265 )
=> PP-2497 Revert jenkins library branch to master

app/browsered.js
- Not selecting the option value in the target HTML select element. So failing on postcode validation when selecting a country other than United Kingdom (default). This is not working in the example provided by them.
See: https://alphagov.github.io/accessible-autocomplete/examples/
`Progressive enhancement` example
- Selecting by clicking does not work.
=> PP-2533 Disable temporary accessible-autocomplete

docker/build_and_test.Dockerfile, docker/build_and_test.sh, package.json
Updated product page with cookie message, this includes it in next build.
Max and I keep leaving in `.only` in unit tests so Max built a thing to check and fail builds if it’s present
=> Bumping pay-product-page and adding check for .only in tests

app/views/errors/incorrect_state/system_cancelled.html, app/views/user_cancelled.html
- Add css classes `user-cancel` and `system-cancel` to User cancelled and System cancelled pages respectively.
- This is to ease testing not relying in text displayed to the users (approach not recommended).
=> PP-2572 Add cancel pages discriminators to ease testing

app/views/errors/system_error.html
There is no easy way to detect if we're showing the error page when we run our end-to-end tests. To solve this problem a 'system-error' class has been added to the message shown on that page.
=> PP-2572 Add system error class to error page to be able to easily detect

package.json
Snyk is reporting a vulnerability in `fresh`
included through `serve-favicon`
https://snyk.io/vuln/npm:fresh:20170908
Upgrading to 2.4.5 fixes this.
=> PP-2712 Upgrade serve-favicon

app/data/countries.json, app/services/countries.js
- Add new territories in countries.json
- Clean up list of countries. The original file is a JSON file copied from the registry, since we are not using all fields and we need to include manually other territories, is not needed to keep the original format and just include needed fields.
- Removed countries with `end-date` as they are not recognised ones and We don't display them anyway.
=> Pp 2758 add other territories

app/services/countries.js, locales/en.json, test/services/countries_test.js
- Order alphabetically. Somehow the order was reversed and we can't find reasons why.
-  User 'Country or territory' in favour of just 'Country' as label in Enter card details.
=> PP-2798 Order territories alphabetically

app/data/countries.json, test/services/countries_test.js
In the country and territories list, change “Aland Islands” to “Åland Islands” (note the “Å”)
See https://territory.register.gov.uk/record/AX
=> PP-2758 Change “Aland Islands” to “Åland Islands” (note “Å”)

.snyk
As specified in the ticket, after investigation we can tell that we have no exposure for the issue found for the dependency 'npm:timespan:20170907'.
We don't want to keep the alert to avoid that another person on support wastes time investigating the issue again. Considering that there's no fix for this issue yet, we decided to ignore the issue for a given period of time and the revisit to check if it applies.
In order to ignore the issue the snyk client has to be installed and the ignore the desired dependency by running:
```
snyk ignore --id=npm:timespan:20170907 --expiry='2018-01-20' --reason='No exposure. Transitive dependency pulled from forever dependency.'
```
That will modify the existing .snyk file in the repo to tell Snyk to ignore that issue.
=> PP-2687 Ignore snyk issue

app/assets/sass/custom/disclosure-scotland.scss
The logo was stretched out of proportion and was massive, so I've used simpler CSS works the same for modern browsers and looks good in IE
=> PP-2819 - IE fixes for disclosure scotland logo

package.json
pay-product-page 2.0.12 was corrupt so I just made a new clean on and marked it 2.0.13
=> 2.0.12 release tarball was corrupt generated a new clean one

app/models/Service.class.js, app/services/clients/adminusers_client.js, app/utils/views.js, app/views/includes/merchant_details.html, app/views/includes/privacy_policy.html, app/views/layout.html, test/fixtures/service_fixtures.js, test/models/service_test.js, test/services/countries_test.js, test/unit/clients/adminusers_client_find_service_tests.js, test/utils/views_test.js
- Add merchant details above privacy info in footer area.
- Extract privacy info into a separated template.
- Add merchant details to Service object class **when available.** Added _isEmpty_ method to check whether merchant details exist so it is backward compatible (current services do not include merchant details, a test account might not have them but live account must have merchant details available).
=> PP-2688 Add merchant details

app/views/charge.html, app/views/errors/charge_confirm_state_completed.html, app/views/errors/incorrect_state/charge_completed.html, app/views/errors/system_error.html
Thanks to @quis for spotting this.
> “Smart quotes,” the correct quotation marks and apostrophes, are curly
> or sloped. "Dumb quotes," or straight quotes, are a vestigial
> constraint from typewriters when using one key for two different marks
> helped save space on a keyboard. Unfortunately, many improper marks
> make their way onto websites because of dumb defaults in applications
> and CMSs.
– http://smartquotesforsmartpeople.com/
This commit replaces an instance of a straight single quote used as
an apostrophe `'` with the unicode character for a proper typographic
apostrophe `’`.
=> PP-2932 - Use proper typographic apostrophes not primes

app/assets/javascripts/modules/form-validation.js, app/assets/javascripts/modules/stop-double-submission.js, app/views/confirm.html, app/views/includes/scripts.html
If a user double clicks either of the submit buttons on
pay-frontend (the continue button and confirm button)
then they get an error as the server freaks out about a
double charge, so I’ve made a GOV.UK JS Module thing that
stops this it can be applied with `data-module="stop-double-submit"`
The charge page has its own complex validation which hijacks the
submit event so rather than use the component I added in a line
to disable it if a form is validated successfully.
=> PP-2867 - Disable submit on first click to stop errors

package.json
Minor copy tweaks
Updated pay-product-page version to include:
Case fix for "Get Started" to "Get started" — https://github.com/alphagov/pay-product-page/commit/ae9600e886ec1b287c9d0b274faa177aad43a46e
Add `&nbsp;`’s to stop GOV.UK Pay splitting across two lines — https://github.com/alphagov/pay-product-page/commit/18871fa985d372e914034f646589f255a09ce8bb
=> Bumping version to correct incorrect case

test/nightwatch/tests/charge_validation_form_group.js
- Update card expiry date for test data. It was set for
`11/17` and today is `12/17`
- Updated to 11/21
=> PP-3020 Fix failing e2e

app/views/charge.html
Whilst it’s valid to wrap `input` or `select` within a `label` it causes issues for
screen reader uses on PC. The when focusing the label element it will read out
everything within the label and so will read the entire select box, in our case
this is a list of 200+ countries which means users probably wont listen to the
end and find that its a combo box that can be accessed.
So I've moved the inputs/selects outside of the labels across the whole page.
=> PP-3022 - Wrapping input/selects in their label element causes accessibility issues

Jenkinsfile
- According to https://issues.jenkins-ci.org/browse/JENKINS-11752 the ansicolor plugin exaggerates log files's size by an order of magnitude.
- Currently, the plugin is disabled and we want to remove it from Jenkinsfile
=> PP-2992 Remove color output from logs in jenkins

app/middleware/resolve_service.js, app/utils/views.js, app/views/includes/custom.njk, app/views/includes/head.njk, app/views/includes/merchant_details.njk, app/views/layout.njk, test/charge_ui_tests.js, test/middleware/resolve_service_test.js, test/utils/views_test.js
- Altered `middleware/resolve_service` so to only log an error if call to adminusers fails
- Updated `utils/views.js` and views depending on `service` to use `res.locals` rather than set explicit property
=> PP-3066 graceful fail on adminusers error

app/views/layout.njk, package.json
We were double loading the fonts but didnt notice because syntax was wrong on custom [govuk_template](https://github.com/jonheslop/govuk_template/commit/e7488c3af27cc68d847f881ea520164ac3529e4b) fixed on this [release](https://github.com/jonheslop/govuk_template/releases/tag/v0.22.5)
=> We were double loading the fonts but didnt notice because syntax was wrong

package.json
Contact becomes support and this bumps the product page version to release it
=> PP-3057 - Contact becomes support and this bumps the product page v.

package.json
Bumps the release number for the pay-product-page being referenced from 2.0.18 to 2.0.19. The new release updates the footer link and main page link to the new statuspage.io page which was recently created.
=> PP-3119 Bumped pay-product-page release from 2.0.18 to 2.0.19 which includes status page link fixes

package.json
Bumping dependency to include new version of product page with [updated cookies link](https://github.com/alphagov/pay-product-page/pull/35/files)
=> BAU - bumping product page version with better cookies info page

app/views/includes/analytics.njk
This will one day be the default when more browsers support it,
but we are setting it now as it may help increase the accuracy
of successful payment journey counts.
We don’t have a content security policy [yet](https://payments-platform.atlassian.net/browse/PP-3131)! But when we do we'll need to add GA to the policy:
```
script-src 'self' *.google-analytics.com;
connect-src 'self' *.google-analytics.com;
img-src 'self' *.google-analytics.com;
```
Example of Notify’s
```
Content-Security-Policy:default-src 'self' 'unsafe-inline';script-src 'self' *.google-analytics.com 'unsafe-inline' 'unsafe-eval' data:;connect-src 'self' *.google-analytics.com;object-src 'self';font-src 'self' data:;img-src 'self' *.google-analytics.com *.notifications.service.gov.uk …
```
=> PP-3132 - Set GA to use navigator.sendBeacon for better accuracy

app/browsered.js, app/controllers/return_controller.js, app/controllers/secure_controller.js, app/middleware/action_name.js, app/paths.js, app/router.js, app/utils/base_client.js, app/utils/base_client2.js, app/utils/correlation_header.js, test/fixtures/pact_interaction_builder.js
* 0b2a151 - Usage of `module.exports.<property-name>` removed in favour of `exports.<property-name>`. 
*  044b9af - Usage of `require(path.join(__dirname, '<file-path>'))` removed in favour of `require('<file-path>')`
* The variable `exports`, when a module is instantiated is a shorthand reference to the `exports` property of the module. i.e. `exports = module.exports = {}`
* `require()` in Node.js handles relative file loading by default so using `path.join(__dirname, '<file-path>') is unnecessary.
* It's generally considered better practice to:
* use `exports.<property-name>` when assigning a property to be exported
* use `module.exports = <Object | Function>` when exporting a single export.
* Using `require(path.join(__dirname, '<file-path>'))` in JetBrains IDEs breaks automatic …
=> PP-3266 refactor exports and imports

app/views/confirm.njk
This change makes the table more accessible to screenreaders.
for example the row.
```html
<tr>
<th>Card brand:</th>
<td>Visa</td>
</tr>
```
When the screenreader focuses on the table it jumps though the `td` but says "Card brand, Visa"
Whereas before it would say "Visa", this makes it clear what the value being read represents
=> PP-3240 - Used <th> so that screen readers labels the field when it reads it out

app/utils/views.js, app/views/error.njk, app/views/error_with_return_url.njk, app/views/errors/charge_confirm_state_completed.njk, app/views/errors/incorrect_state/auth_3ds_required.njk, app/views/errors/incorrect_state/auth_failure.njk, app/views/errors/incorrect_state/auth_success.njk, app/views/errors/incorrect_state/capture_failure.njk, app/views/errors/incorrect_state/capture_waiting.njk, app/views/errors/incorrect_state/session_expired.njk, app/views/errors/incorrect_state/system_cancelled.njk, app/views/errors/system_error.njk, app/views/static/privacy.njk, app/views/user_cancelled.njk, test/middleware/csrf_test.js, test/middleware/resolve_service_test.js, test/middleware/retrieve_charge_test.js
When error 403 "unauthorised" we were using system error, when this sort of error is likely an expired session, we have a template and messaging for that, so I just switched it out.
Also I noticed all the pages on Frontend don’t have “- GOV.UK Pay” on the end of the page title
So I added it to all of them for consistency
=> PP-2766 friendly message for expired sessions

app/controllers/return_controller.js, app/controllers/secure_controller.js, app/controllers/static_controller.js
In the secure, return and static controllers:
- removed unnecessary inner functions in secure controller
- removed unnecessary variables in return controller
- implemented 'prefer-const' style for variable declarations
In the secure controller:
- fixed line 20 (old line 28) where the success path would be executed even if the token destroy failed.
- fixed line 20 (old line 28) where the error would be lost to the ether if token destroy failed.
=> PP-3266 refactor return secure and static controllers

app/utils/custom_certificate.js, run-with-chamber.sh
Adds NPM start script to allow the execution of the application using the Chamber binary to fetch secrets and add as environment variables. This allows the application to be used via ECS and our associated secrets management pattern.
In addition, changes to the certificate management code have been made to be tolerant of sub directories in the existing certificate directory which may be present when volume mounting.
=> PP-3091 Modify pay-frontend to support ECS based deployments

app/middleware/action_name.js, app/middleware/csrf.js, app/middleware/resolve_service.js, app/middleware/retrieve_charge.js, app/middleware/state_enforcer.js, test/middleware/action_name_test.js, test/middleware/csrf_test.js
Refactor middleware to:
- use strict
- prefer const
- eliminate unnecessary inner functions and variables
- to use `exports.<property-name>` over `module.exports.<property-name>`
=> PP-3266 refactor middleware

app/utils/accessible-autocomplete.js, app/utils/analytics.js, app/utils/cardid_client.js, app/utils/charge_utils.js, app/utils/cookies.js, app/utils/correlation_header.js, app/utils/custom_certificate.js, app/utils/email_tools.js, app/utils/flattened_paths.js, app/utils/generate_route.js, app/utils/logging.js, app/utils/luhn.js, app/utils/metrics.js, app/utils/no_cache.js, app/utils/random.js, app/utils/request_logger.js, app/utils/response_converter.js, app/utils/session.js, test/integration/util_cookies_ft_tests.js, test/unit/cookies_test.js, test/unit/custom_certificate_tests.js
Refactoring  utils in frontend:
- to remove unnecessary inner functions and variables
- to remove unnecessary IIFEs
- to extract calls to `process.env` to constants
- to use `exports.<property-name>` over `module.exports.<property-name>`
=> PP-3266 refactor utils

app/middleware/resolve_service.js, app/router.js, app/utils/cookies.js, test/unit/cookies_test.js
with @maxcbc
Custom branding is configured by the service, to keep things
consistant we should show custom branding on error pages too.
Updated resolve_service:
- use cookie to store service info
- use cookie service info if available
- resolve_service middleware should be available to error pages
=> PP-3304 add service to charge session cookie

package.json
bumping product page version to include minor updates
[0c82a9c](https://github.com/alphagov/pay-product-page/commit/0c82a9c211113ffca80b2c2d0c22897a9bac4d52) - Fixing broken roadmap link
[5ee03e0](https://github.com/alphagov/pay-product-page/commit/5ee03e0d0afc2ea34f8798202dde523319dc21a5) - PP-2651 - adding guidance on how long an integration takes
[fa8f923](https://github.com/alphagov/pay-product-page/commit/fa8f923dfb0e4c14f55cdb84b5253b224d9f7d43) - Use ‘to’ not hyphens for date ranges
=> bumping product page version to include minor updates

app/controllers/charge_controller.js, app/paths.js, app/views/auth_3ds_required_out.njk
- We were using a env-var for the hostname in the 3ds in url, this switches to using req.protocol followed by req.hostname
=> PP-3092 Use req.hostname for 3ds IN url 

app/middleware/resolve_service.js, package.json, test/middleware/resolve_service_test.js
- use `memory-cache` to store service in cache rather than in cookie
=> PP-3395 Cache service in memory

package.json
Bump product page to this release https://github.com/alphagov/pay-product-page/releases/tag/2.1.6
To include these changes
https://github.com/alphagov/pay-product-page/commit/f6921c8a6ff1b2f3227b1b70f77892d894771248
https://github.com/alphagov/pay-product-page/commit/74603ce8922e056845f3f99cd56b542a25be0a58
=> BAU - bump product page version to publish Till’s copy changes

app/middleware/resolve_service.js
- Set service cache max age using the environment variable `SERVICE_CACHE_MAX_AGE`, but default it to 15 minutes
=> PP-3395 Set service cache max age by environment variable

app/controllers/charge_controller.js, app/services/normalise_charge.js, app/utils/views.js, app/views/auth_3ds_required_html_out.njk, test/integration/charge_ft_tests.js, test/test_helpers/test_helpers.js, test/utils/normalise_test.js
Displays different iframe contents based on the availability of `issuerUrl` and `paRequest` (for Worldpay) or `htmlOut` (in case of `epdq`).
Using `utf8` decoding of html as of now (need to verify with eqdq on this)
with @chrisgrimble
=> PP-3451 handling epdq auth 3ds out view

Jenkinsfile
This is a jenkinsfile update which:
- switches to using separate e2e, accept and zap test jobs
- runs each of these jobs in parallel
- switches each of these jobs on its own param for testing on pull requests
=> PP-3436 Run e2e, accept and zap separately in parallel

app/controllers/charge_controller.js, app/paths.js, app/router.js, app/views/auth_3ds_required_in.njk, test/integration/charge_ft_tests.js
- When receiving a response from the payment gateway, it will
send the user back inside the iframe. To get out from the iframe
we use a form with a target `_top` and at the same time we pass
any data we get from the payment provider as form fields to the
charge_controller. Because some of this data is specific to each
payment gateway, we will set it only if available. After setting this
data as hidden fields we then submit the form and send this data
to connector
- Added both POST and GET to the same path for EPDQ as they
use GET as a fall back when JS is deactivated. This callback url to us
will contain the EPDQ auth status as query param
- The status received from EPDQ is not reliable as this is
resubmitted as a hidden field, however we verify this status in connector
against EPDQ …
=> Pp 3453 handle epdq 3ds response

package.json
To release this update - https://github.com/alphagov/pay-product-page/pull/41
=> PP-3542 - bump prod page version with copy updates

app/router.js, app/utils/ab_test.js
A question for `pay-frontend` `ab_test.js:50` there is this line `const threshold = Math.floor(opts.threshold || 90)` and it looks like is returning 90 if no `threshold` is passed, also Math.floor seems like is not needed because you get in Integer anyway `const threshold = Math.floor(opts.threshold || 90)`
Toby Lorne [16:27]
defensive programming :open_mouth:
George Racu [16:27]
I think the Math.floor is not necessary
and also the threshold of 90 shouldn’t be 100?
Toby Lorne [16:28]
yeah so there are a couple of layers here
the environment variable passed in is specific to one single ab test
but the Math.floor bit is for all ab tests
so we could have a long running ab test that doesn’t take an environment variable etc
George Racu [16:29]
and the 90 shouldn’t be 100?
Toby Lorne [16:30] …
=> PP-3579 - more robust setup

Jenkinsfile
When converting staging deployments over to use the selenium tests we
decided only to run product smoke test for products and products-ui
solo @belindac
=> PP-3602 Remove Product smoke test

app/assets/javascripts/modules/form-input-confirm.js, app/assets/javascripts/modules/polyfills.js, app/assets/sass/helpers/_panels.scss, app/browsered.js, app/views/charge.njk, app/views/includes/scripts.njk
We’d like to reuse this input confirm function on pay-products-ui
and over there we dont use jQuery and write nodeJS that gets converted
by Browserify. So to keep things consistent I'm making it the same in
both places.
=> PP-3225 - Simplifying and removing jQuery from function

app/utils/email_tools.js
Unfortunately, mailcheck.js doesn’t know about some .uk second-level domains, which means it makes some erroneous suggestions:
- .ac.uk — suggests .co.uk
- .me.uk — suggests .me.uk
- .mod.uk — suggests .gov.uk
- .net.uk — suggests .net
Fix this by just adding all the active .uk second-level domains (see https://en.wikipedia.org/wiki/.uk#Active for a hopefully accurate list) to the mailcheck.js default top level domains list.
=> Add all .uk second-level domains to mailcheck.js default TLDs

app/controllers/charge_controller.js, app/utils/email_tools.js, test/integration/charge_validation_ft_tests.js
It’s overly sensitive and is flagging more false positives than actual
errors, need to roll back and work out how to make it less trigger
happy.
On the plus side, we were noticing it dropping the persons  email from
the form on error, this was not because of mailcheck but due do a
erroeous deletion during a rebase of the Node 8 upgrade. So that’s one
'bug' fixed :D
=> BAU - The email typo thing needs more work

app/router.js
The confirm variant replaced the old confirm page, however I neglected
to remove the switch statement, this would cause an internal server
error when attempting to confirm a payment (when using an ab test path).
The switch statement is removed so now neither the ab test query param
nor the ab test session state affect the payment journey.
solo @tlwr
=> PP-3819: Remove ab test switch statement

app/views/includes/cookie-message.njk, app/views/layout.njk
For some reason Frontend was missing the cookie banner text so it showed the banner but it was blank.
=> PP-3848 - Add cookie banner text

app/controllers/charge_controller.js, app/utils/email_tools.js, app/views/charge.njk, package.json, test/integration/charge_validation_ft_tests.js, test/utils/common-typos.test.js, test/utils/invalid-email-list.js
The previous iteration was too eager to correct people’s perfectly valid emails. I’ve trained it using 10,000 emails that used pay so it’s a lot less trigger happy now, e.g. it knows `.ae` domains are legit. 
Also, before, once invoked if you changed your original input it still preferred the radio buttons, this is no good, as we may have spotted an error but not suggested the right correction, so know if a user ammends the original input, we take that and run that through the validator again.
=> PP-3673 improve mailcheck accuracy

docker/build_and_test.Dockerfile
This was lost when the build and test image was split out from the main
dockerfile.
=> Add reason for installing glibc in the test image

app/utils/base_client.js, server.js, test/test.env
Added environment variable ```USE_HTTP_CLIENT``` to use http client instead of https for local testing purposes. Added environment variable ```DISABLE_APPMETRICS``` to ignore appmetric import for running locally.
=> Added environment variables to permit running locally via pay local tool.

package.json
Bumps the referenced pay-products page up to the newest version.
=> PP-3996 Version bump of products page to point at new release

Gruntfile.js, package-lock.json, package.json, server.js
Whilst looking at how our performance was improved by switching to GOV.UK Frontend, I noticed how huge our JS because it’s not minified/uglified.
So I’ve added a grunt task to do so and it comes out 3x smaller.
I still think it’s bundling an awful lot of stuff it can’t possibly need, so I'm going to do some further investigation but this is a quick win.
=> PP-3991 - Minifying JS

package-lock.json, package.json
There were two bullet points missing from the privacy notice, this adds them
https://github.com/alphagov/pay-product-page/pull/67
=> BAU - bump product page version with privacy additions

app/assets/javascripts/modules/form-validation.js
ZAP tests need to be able to submit a malformed post so that it can run
a bunch of pen tests on the post. But to do that, it needs to get
around our client-side validation JS. Before they could use jQuery to
kill all the eventListeners but we can’t do that without jQuery.
So I’ve put a breaker in the function that will supress the validation
if an element with the id `disable-for-zap` is present.
Then when the page is loaded in the ZAP test it will insert the element
before it does the submit and will be able to do the pen test.
=> PP-4090 - Switch to allow ZAP to disable JS validation

app/views/layout.njk
The new design system nunjucks macros require a link for the service name, I dropped in `/` without thinking about it.
Putting in `#` as thats less confusing for the user, although still not great.
We should either raise a PR with the design system to allow for a service name without a link.
OR come up with a way to determine what link we should put in there, but we’d have to communicate this with our partners
=> PP-4137 - remove link from service name

server.js
As part of the performance testing epic
(https://payments-platform.atlassian.net/browse/PP-4004) we have made some
changes to improve performance Some of these are:
- caching token requests in publicapi
- upgrading frontend's ec2 instances from m3.medium -> c4.large
It would be good to log the memory statistics for each server process in node
should we need to further improve performance (for example, by changing the
heap size, which would then affect when the garbage collection kicks in) for
frontend in the future. We currently have no easy way to know this.
@oswaldquek
=> bau: log memory stats

server.js
It was logging `process.memoryUsage: [object Object]` before.
@oswaldquek
=> bau: log memory stats correctly

app/middleware/resolve_language.js, app/router.js, app/utils/charge_validation.js, app/views/auth_3ds_required.njk, app/views/auth_3ds_required_in.njk, app/views/auth_3ds_required_out.njk, app/views/auth_waiting.njk, app/views/capture_waiting.njk, app/views/charge.njk, app/views/confirm.njk, app/views/error.njk, app/views/error_with_return_url.njk, app/views/errors/charge_confirm_state_completed.njk, app/views/errors/incorrect_state/auth_3ds_required.njk, app/views/errors/incorrect_state/auth_failure.njk, app/views/errors/incorrect_state/auth_success.njk, app/views/errors/incorrect_state/auth_waiting.njk, app/views/errors/incorrect_state/capture_failure.njk, app/views/errors/incorrect_state/capture_waiting.njk, app/views/errors/incorrect_state/charge_completed.njk, app/views/errors/incorrect_state/session_expired.njk, app/views/errors/incorrect_state/system_cancelled.njk, app/views/errors/system_error.njk, app/views/includes/scripts.njk, app/views/user_cancelled.njk, locales/en.json, server.js, test/test_helpers/html_assertions.js
Reconfigure app to use i18n in a way which means english isn’t hard coded.
This is also changes the way the strings are fed into the the templates which required switching to using `_("object.path")` syntax
Also added cy.json which contains the welsh strings
=> PP-4097 reconfigure app to use i18n dynamically

app/controllers/charge_controller.js, app/middleware/resolve_language.js, app/models/Service.class.js, app/router.js, app/views/includes/custom.njk, app/views/layout.njk, test/integration/charge_ft_tests.js, test/middleware/resolve_language_test.js
- Retrieve language from charge object
- Previously we were getting the service name from the gateway account
object now getting it from the service object (which comes from
adminusers).
- Pass the language to the template and use that to get the correct
service name translation.
=> PP-4098 get language from charge

app/services/environment.js
The consensus in node land is that you should have one node process
per cpu core. This commit uses the built in os module to configure that.
=> Match worker count to number of cpus

app/utils/views.js, test/enforce_status_views_tests.js
- Made frontend aware of the status `AWAITING CAPTURE REQUEST`
- This new status will map the functionality of `CAPTURED`, as long as the
user is concerned the payment was successful
- Made the view enforcer return success page when a charge with this state
is retrieved from connector, on urls: `/chargeid` and `/chargeid/confirm`
with @danworth
=> PP-4108 Add status `AWAITING CAPTURE REQUEST`

app/services/state_service.js, test/enforce_status_views_tests.js
* Renamed status in tests to make it explicit that this status is not allowed and is not possible to exist. The existing status name was similar to `CAPTURE READY` vs `READY FOR CAPTURE` and was creating confusion if is a reference to the `CAPTURE READY` or is some other state
* Replaced `var` with `const`
=> Bau rename status in test

app/controllers/charge_controller.js, app/models/card.js, app/utils/charge_validation_backend.js, test/controllers/charge_controller_test.js, test/models/card_test.js
- Added `corporate` and `type` to the response if existing `accepted` is true.
- Modified related tests.
- Reformatted code.
with @DanailMinchev and @brid
=> PP-4124 Updated /check_card endpoint to return corporate information

app/views/errors/incorrect_state/auth_failure.njk, app/views/errors/incorrect_state/session_expired.njk, app/views/errors/incorrect_state/system_cancelled.njk, app/views/user_cancelled.njk, locales/cy.json, locales/en.json
Improves the unsuccessful payment screens by changing anchor links into 'button' styled links, as well as improving copy, and associated Welsh language translations.
=> PP-4201 Improve unsuccessful payment screens

app/controllers/charge_controller.js, app/services/normalise_charge.js, app/utils/charge_validation_backend.js, test/integration/charge_ft_tests.js
- Added the whole `card` object (which includes `brand`, `type` and
`corporate` properties) to be returned from `charge_validation_backend`
module instead of only `brand`
- include 'corporate_card' and 'card_type' properties in request body
when calling v1/frontend/charges/CHARGE_ID/cards. These values come
from call to card id
- updated existing tests for confirming the patch to
/v1/frontend/charges/ and the post to
/v1/frontend/charges/{CHARGE_ID}/cards to expect these new properties
to be included
- added new tests to check the combinations of card type and
corporate/non-corporate
- Renamed `defaultCardId` to `mockSuccessCardIdResponse` within `charge_ft_tests.js` for clarity. 
Note that the card number previously being passed to `defaultCardId` was not being used.
with @stephencdaly …
=> PP-4196 Include properties for corporate surcharge in cardAuth call

app/services/normalise_charge.js, app/views/charge.njk, app/views/confirm.njk, test/integration/charge_ft_tests.js, test/test_helpers/test_helpers.js
- Added `charge.corporate_surcharge` which is corporate card fee and can be present or not to the `confirm.njk` template.
- Added `charge.total_amount` which is total amount of the charge and can be present or not to the `confirm.njk` template.
- Added UI test with connector mock.
with @stephencdaly
=> PP-4196 Corporate card information on confirmation page

app/assets/javascripts/modules/form-validation.js
The error was related to the inline validation on the expiry date,
because there are two inputs within one form group it got confused
and raised an error in the console. it didnt negatively impact the
process but just looks unprofessional.
=> PP-4320 - fix JS error appearing in console

app/models/Service.class.js, test/fixtures/service_fixtures.js, test/middleware/resolve_service_test.js, test/models/service_test.js
- Use new 'redirect_to_service_immediately_on_terminal_state' property returned by adminusers GET service call when resolving the service in middleware.
- Modified service test fixture to expect new property.
- Made some minor alterations to some tests:
- The happy path test in resolve_service_test now asserts on something that will prove the resolve was successful.
- Use the service fixture to construct the input JSON in service_test.
with @DanailMinchev
=> PP-4205 Use direct redirect property

app/controllers/charge_controller.js, app/controllers/return_controller.js, app/controllers/secure_controller.js, app/controllers/static_controller.js, app/middleware/csrf.js, app/middleware/resolve_service.js, app/middleware/retrieve_charge.js, app/middleware/state_enforcer.js, app/models/Service.class.js, app/models/charge.js, app/utils/response_router.js, app/utils/views.js, test/fixtures/service_fixtures.js, test/integration/charge_ft_tests.js, test/middleware/retrieve_charge_test.js, test/test_helpers/test_helpers.js, test/utils/response_router_test.js, test/utils/views_test.js
- Move the `redirectToServiceImmediatelyOnTerminalState` property on the `Service` model to correct place
- Perform a redirect to the return URL when a terminal state in the payment flow is reached, rather than show our pages
- Modified `views.js` to add an additional `terminalView` property on action objects to determine whether a view is a terminal state
- In `views.display`, if the action has the `terminalView` set to `true` and `redirect_to_service_immediately_on_terminal_state` is set to `true` on the `Service`, perform a redirect to the return URL
- Added tests to test the new logic introduced to `views.display`
- Originally we were attempting to cancel the charge before the redirect if an error occurred leaving it in a cancellable state. However after discussion we reverted this …
=> PP-4205 Implement redirect to service

app/models/charge.js, app/services/clients/connector_client.js
Further migration so any calls to Connector are done via a Connector client, and not using the base client directly. This reduces logging code, facilitates debugging and testing, and generally cleans up things into a direction we want to be going in.
=> PP-4347 Map charge.js calls to Connector client instead of base client

app/models/token.js, app/services/clients/connector_client.js
All token actions exposed by token.js now call a connector base client that abstracts base_client calls to connector, rather than having these handled inside the module.
This reduces repeated code, consolidates logging and cleans things up along the same lines as self-service.
=> PP-4347 token.js now makes connector calls via a Connector client, rather than directly to base_client

app/controllers/healthcheck_controller.js, app/models/card.js, app/services/clients/adminusers_client.js, app/services/clients/base_client/base_client.js, app/services/clients/cardid_client.js, app/services/clients/connector_client.js, test/unit/base_client_test.js
The service client and base clients are now located in the same path that self-services uses. This reduces cognitive overload in trying to learn both applications and where various things are located.
=> PP-4347 service and base clients now mirror the same location structure as self-service

test/cypress/test.env
Otherwise Jenkins gets sad. Frontend tries to use all 36 cores, with hilarious consequences.
=> PP-4347 Set NODE_WORKER_COUNT in cypress tests

package-lock.json, package.json
Bumps the product page version to include updates to the Blue badge
page.
Solo: @ejrowley
=> BAU bump product page version

app/controllers/charge_controller.js, app/controllers/three_d_secure_controller.js, app/routes.js
Separates out 3DS controller from charge controller, as its
a fairly self contained unit. I have not made any other changes
other than lifting and shifting, and amending the necessary routes.
=> PP-4373 Separate 3DS controller

app/views/errors/incorrect_state/auth_failure.njk, app/views/errors/incorrect_state/system_cancelled.njk, app/views/user_cancelled.njk
Updates failure page button text to simply 'Continue' rather than what was there before
=> PP-4349 Changes button text on unsuccessful payment screens for auth failure/system_cancelled/user_cancelled to 'Continue'

app/controllers/three_d_secure_controller.js, test/integration/three_d_secure_ft_tests.js
Stripe's 3ds flow is different from any of the other providers we
support. From frontend's point of view, it is much simpler -
connector passes up an issuerUrl, and frontend needs to redirect
to that page and then handle the return.
This commit just adds the 'out' part of that - it takes the issuerUrl
and does a redirect. This is obvs not a complete journey, but given this
is not used I don't think that matters.
Potentially we could look at tidying up the frontend logic around deciding
what it needs to do with 3ds stuff, but I will look at that in a separate PR.
See https://stripe.com/docs/payments/3d-secure
=> PP-3473 Add stripe 3ds 'out' path

Gruntfile.js, package-lock.json, package.json
Live reload for client side JS as well as Sass.
Also added ignore rules so nodemon isn’t too trigger happy
=> BAU - Live reload for client side JS

app/assets/javascripts/modules/form-validation.js, app/controllers/charge_controller.js, app/models/card.js, app/views/includes/scripts.njk, test/controllers/charge_controller_test.js, test/models/card_test.js
- Obtain the prepaid status from the card id check card
endpoint.
- Obtain the prepaid debit and prepaid credit surcharge amounts on the
gateway account.
- Use these values in the browser-side javascript to decide whether to
display a corporate surcharge, and calculate it if so.
=> PP-4291 Display surcharge for prepaid corporate cards on card details page

app/views/confirm.njk, test/charge_ui_tests.js, test/integration/charge_billing_address_ft_tests.js, test/test_helpers/test_helpers.js
Show billing address on confirmation page depending on the charge `cardDetails.billingAddress` value and not depending on the service `collectBillingAddress` setting as the service object is cached and the results can be different on different nodes
=> PP-4161 Show billing address on confirmation page depending on the charge value

config/charge_controller.js, test/integration/charge_ft_tests.js
If you have JS disabled and make an error you have to re-enter the four
card fields again. This is annoying and I am not sure if it’s necessary.
=> PP-4515 - preserve fields on reload

app/assets/sass/modules/_payment-request.scss, app/views/charge.njk
Error summary and email typo suggestion were hidden erroneously. All good now
=> PP-4517 fix email typo error messaging

package-lock.json, package.json
Because of https://www.npmjs.com/advisories/720
interestingly both modules have just dropped Cryptiles rather than
update to non vulnerable version
=> PP-4563 - Updating packages that depended on cryptiles

server.js
This doesn't do what we think it does ™️
If any environment variable is set for `DIABLE_APP_METRICS` it will
result in `false`, this is because any defined string in JavaScript
converted to Boolean (`!`) will result in `true` - negating this will
always be false.
The current behaviour will disable app metrics if any value is set for
this environment variable (even if it's explicitly false).
Suggestion for extracting core functionality into shared modules made for upcoming work.
Note: This should be checked carefully before pushing to production - it may alter the way environments interpret or set flags
=> PP-4564: Fix app metrics disabled flag equality

app/middleware/state_enforcer.js, test/middleware/state_enforcer_test.js, test/test_helpers/test_helpers.js
- Allow AUTH_3DS_READY state when payment provider is stripe
=> PP-4651 State enforcer - Allow AUTH_3DS_READY for Stripe

app/utils/request_logger.js
it seems useful to log this as well as request completion. It can help
debugging in cases where something goes wrong before the response is received.
=> BAU log request start at info level

app/assets/javascripts/browsered/web-payments/helpers.js, app/browsered.js
This stops it causing errors further down the line.
Noticed becuase the JS wasn’t firing that creates a pseudo pageview we use to count successful transactions
=> PP-4747 - JS error blocking rest of scripts

Jenkinsfile
Cleanup code exists in the Cypress groovy jenkins library to clean up
docker-compose, however it looks like this is never run, meaning that
Docker containers and networks are left hanging after job completion.
=> BAU Invoke cleanup script from Jenkins library

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/assets/javascripts/browsered/web-payments/index.js, app/views/charge.njk, app/views/includes/scripts.njk, locales/en.json, server.js, test/browsered/payment-request.test.js, test/test.env
Previously google pay was really just a vanilla payment request API call.
Refactored to use Google Pay as the payment method using - https://developers.google.com/pay/api/web/guides/paymentrequest/tutorial
Extended helper.js to build the Google request and moved out the common bits to keep things DRY
I’ve gone as far as initiating an Google Pay payment and getting auth and a token back from Google but I haven’t done anything with yet
Also tidied up a few things in the markup to make the definition between
google and apple clearer.
=> PP-4641 - Integrate Google Pay with Payment Request API 

app/assets/javascripts/browsered/form-input-confirm.js, app/assets/javascripts/browsered/web-payments/index.js, app/browsered.js, app/controllers/charge_controller.js, app/views/charge.njk, app/views/includes/scripts.njk, test/browsered/payment-request.test.js
a7eb620 - PP-4784 - Put scripts into window so can conditionally trigger
4febb7c - PP-4784 - introduce concept of enabling Apple / Google Pay individually
* Using allowApplePay and allowGooglePay so we can toggle individually. This hasn’t been done in connector so fudging with change in charge_controller.js
* Split up the initalisation of web payments into different functions and toggling only if browser has the capability.
=> PP-4784 init Google / Apple Pay only if configured

test/middleware/action_name_test.js, test/middleware/csrf_test.js, test/models/charge_test.js, test/models/token_test.js, test/services/charge_param_retriever_test.js
`assert.strict` [strict mode](https://nodejs.org/api/assert.html#assert_strict_mode) was introduced in Node v9.9.0. 
The Node version for this repository is
pinned behind this so new features shouldn't be used until this is updated.
=> BAU: Fix reliance on assert.strict

.gitignore, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/assets/javascripts/browsered/web-payments/index.js, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, locales/en.json, test/cypress/integration/web payment/google-pay.spec.js, test/fixtures/payment_fixtures.js
Stubbed out PaymentRequest and Fetch so that I can intercept the native browser methods and return what I expect from them. 
Whilst stubbing PaymentRequest API is neccessary perhaps could it might be nice to not stub fetch and then stub the connector calls the controllers make. But it [turns out you cannot use Cypress’s `route()` method to intercept fetch calls](https://docs.cypress.io/api/commands/route.html) so doing so would be tricky. As unit tests exist for the controllers perhaps the stub is ok after all.
Also made Google Pay specific fixtures editable
=> PP-4824 - Cypress tests for Google Pay

app/views/charge.njk
On the card details page, change the autocomplete attribute for the first address line from `street-address` to `address-line1`.
Currently, we have `street-address` for the first line of the address and `address-line2` for the second line of the address. This can make Google Chrome duplicate data when auto-filling (e.g. putting “1 Foo Street, Barton” in the first address line and “Barton” in the second address line).
=> PP-4876 Make address line 1 autocomplete be “address-line1”

app/models/charge.js
The return controller was attempting to cancel charges that are in the CAPTURE_READY state. As far as frontend is concerned, this is a terminal state so it should never attempt to cancel charges in this state.
with @cobainc0
=> PP-4921 Don't attempt to cancel CAPTURE_READY charges

package-lock.json
Dependency chain:
pay-frontend@0.0.1 › nunjucks@3.1.7 › chokidar@2.0.4 › fsevents@1.2.4 › node-pre-gyp@0.10.0 › tar@4.4.1 › chownr@1.0.1
updating chokidar pulls in a newer version of chownr without the vulnerability
=> PP-4928 Force chokidar update

test/cypress/plugins/index.js, test/cypress/support/index.js
As per Cypress best practices we should clear up stubs state runners
before running tests rather than after. Ref:
https://docs.cypress.io/guides/references/best-practices.html#Using-after-or-afterEach-hooks
=> BAU: Cleanup stubs before instead of after specs

app/controllers/charge_controller.js, app/services/normalise_charge.js, test/integration/charge_ft_tests.js, test/test_helpers/test_helpers.js
Sometimes a card cannot be auth’d immediately, in this case 202/409 is return and [we wait](https://github.com/alphagov/pay-frontend/blob/master/app/views/auth_waiting.njk#L27).
Once the auth is complete the flow went back to non Apple/Google Pay flow which meant users would see the confirm page, which we dont want.
This adds logic to check if it’s a digital wallet payment and if so immediately does the auth and then redirects to the service’s returnURL
=> PP-4927 - maintain web payments flow after auth waiting

app/controllers/web-payments/apple-pay/merchant-validation-controller.js
Due to limitations with our current infra set up all secrets need to be
single line.
However Apple requires multiline serts and keys to be able to validate
us as merchant.
Whilst we’re working on making multiline secrets poosible we’re
manipulating the secrets in the controller to get around the problem.
=> PP-4914 - Apple need multiline certs

app/assets/javascripts/browsered/web-payments/apple-pay.js
When merchant validation fails under certain cicumstances the Apple Pay dialog didnt disappear, this is confusing and a waste of time for the user. Added in a line to abort the session when this happens (which it shouldnt once we sort out the certs issue a la #697
=> PP-4914 - abort session when merchant validation fails

app/assets/javascripts/browsered/web-payments/index.js
We have seen intermitant behaviour where Google Pay fails to check if
it’s available, this seems related to this
`Unable to download payment manifest
"https://pay.google.com/gp/p/payment_method_manifest.json"`
So going to log to Google Anayltics to we can see how often this
happens, Google have given us no indication why this happens except to
tell us that we should use their 3rd party API (which adds at least 10
tracking scripts to the page)  as opposed to the open
standard payment request API.
=> PP-4901 - Log error when Google Pay availablity check fails

package-lock.json, package.json
Not everyone has linter plugins installed in their chosen editors, this means PRs fail on Jenkins for silly things like curly bracket spacing or identation.
This PR adds [Husky](https://github.com/typicode/husky) a git hooks tool and [lint-staged](https://github.com/okonet/lint-staged) which make it easy to automatically lint all JS changes that have been staged for commit. If it spots errors it can fix it does or throws an error detailing what needs changing.
This will help improve the quality of code we’re shipping.
=> PP-4904 lint on pre commit hook

app/models/Service.class.js, app/views/layout.njk, test/charge_ui_tests.js, test/cypress/integration/card/footer.spec.js, test/cypress/integration/card/payment.spec.js, test/cypress/plugins/stubs.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment_fixtures.js, test/fixtures/service_fixtures.js, test/models/service_test.js
- It is possible to set individual elements of the merchant details
- Previously service model was assuming that if the merchant_details field was present in the get service response, it had a full address and so attempted to resolve the country from the country code without checking whether it was present. This commit fixes this.
- Handle the case where there is an organisation name but no address or an incomplete address by displaying just the organisation name in the footer of the payment pages.
Co-authored-by: Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk>
=> PP-4939 Fix error when service has organisation name but not address

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js
When normalising an Apple Pay payload, if the card brand doesn’t match one of the ones we recognise, log what what it was in the error message.
=> PP-4917 Log unrecognised Apple Pay card brand in error message

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js
Apple have docs about how to declare which card types you want to accept, but not how it labels those card types coming out, basically it capitalises them, so adding `toLowerCase()` to account for this.
=> PP-4917 - Make card brand normalisation independent of case

app/middleware/resolve_service.js, app/services/clients/adminusers_client.js
Service middleware admin users base client resolves a callback method
that doesn't handle errors - ensure that errors are thrown correctly in
a Promise chain when the callback is resolved.
Should follow after PP-4939 checking to see if properties on service exists.
=> PP-4939 Propagate service middleware errors

app/views/auth_3ds_required.njk, app/views/auth_3ds_required_in.njk, app/views/auth_3ds_required_out.njk, app/views/auth_waiting.njk, app/views/capture_waiting.njk, app/views/charge.njk, app/views/confirm.njk, app/views/error.njk, app/views/error_with_return_url.njk, app/views/errors/charge_confirm_state_completed.njk, app/views/errors/incorrect_state/auth_3ds_required.njk, app/views/errors/incorrect_state/auth_failure.njk, app/views/errors/incorrect_state/auth_success.njk, app/views/errors/incorrect_state/auth_waiting.njk, app/views/errors/incorrect_state/capture_failure.njk, app/views/errors/incorrect_state/capture_waiting.njk, app/views/errors/incorrect_state/charge_completed.njk, app/views/errors/incorrect_state/session_expired.njk, app/views/errors/incorrect_state/system_cancelled.njk, app/views/errors/system_error.njk, app/views/user_cancelled.njk, config/pay-translation.js, server.js, test/test_helpers/html_assertions.js
i18n’s built in translation function `__()` returns the key
if it can’t find a translation. This is problematic as we show
something gross like 'cardDetails.title' to the user.
So this is a custom function that will check that the string
doesn’t equal the key. And if it does throw an error so the
template fails to render but with a nice helpful error message.
The error looks like this:
Which is how all the other Nunjucks errors look and it would mean you could never get your PR through tests
=> PP-5015 - add new custom translation function

app/views/charge.njk, test/cypress/integration/web-payments/apple-pay.spec.js
So check if browser supports v4 before enabling Apple Pay
=> PP-4917 - Only Apple Pay v4 supports Maestro

app/assets/javascripts/browsered/web-payments/index.js, app/assets/sass/modules/_payment-request.scss, test/cypress/integration/web-payments/apple-pay.spec.js, test/cypress/integration/web-payments/google-pay.spec.js
Using .hidden doesn’t work as the CSS is more specific, need to set
inline style attribute instead
Added tests to check this so we can’t ship this broken going forward.
Verified it by running new Cypress tests on master which failed as we would expect them to
=> PP-4917 - Because we display with CSS need to override inline

app/assets/javascripts/browsered/web-payments/apple-pay.js, package.json, test/cypress/integration/web-payments/apple-pay.spec.js
I tried to validate the email before payment authorisation but Apple
won’t hand over any personally identifiable information before
authorisation, will only give things like contry and postcode.
So we have to do this after authorisation. I have refactored the test so
that we can construct an Apple Pay Session that returns a bad email
Have written test to confirm this behaviour
=> PP-4917 - Validate email after payment authorised

Jenkinsfile
This is needed as frontend runs java pact provider tests for selfservice and
adminusers
=> bau: set JAVA_HOME to 11

app/controllers/charge_controller.js, test/cypress/integration/card/email-typo.spec.js
The patch which sends the email was moved above the code that corrected
typos, meaning the uncorrected email was sent.
=> PP-5062 - Make sure corrected email gets sent to connector

app/assets/javascripts/modules/form-card-type.js, app/models/card.js, test/cypress/integration/card/footer.spec.js, test/cypress/integration/card/payment.spec.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment_fixtures.js
- This change stops posting for a card check to card id when the card number is less than 11 digits thus stopping card_id throwing RuntimeException which result in a 500 error.
with @jonheslop
=> PP-5057 do not post to card_id when card no is less than 11 digits

package.json
Me and a few others have got caught out spinning up Cypress and there
being issues because the JS/CSS are out of date (or missing altogether).
This makes sure that doesn’t happen by running it just before.
=> BAU - Generate assets before running Cypress

package.json
Sometimes people forget to do this which causes issues when running
locally. I added the script to cypress:server but this penalises people
who run this often so moving to prepare
Tried it out by running `rm -rf node_modules && npm i` and can confirm it works
=> BAU - Generate static assets after install

test/fixtures/wallet_payment_fixtures.js, test/unit/clients/connector_client_apple_authentication_tests.js, test/unit/clients/connector_client_google_authentication_tests.js
The structure of error responses is changing so the message field will be an array. We should remove the field from the pact entirely as we don't consume it, so shouldn't be asserting on it.
=> PP-5142 Remove message from error response in Pact

app/assets/sass/modules/_cvc.scss, app/views/charge.njk
We have 3 scenearios here:
- Default - 3 digit CVC hint
- AmEx - 4 digit CVC hint
- No-js - both hints togother. With 'For American Express' clause to make it read better.
These spans were all siblings and we're smushed together with floats and margins, this is convoluted and cause the flow to break because the CVC input floated to the end.
We can do it more simlpy by nesting them and using `display:inline`. But because HTML will automatically put a space if there is a whitespace between spans, we have to smush it together in the markup so it‘s all one line.
=> PP-5205 - Nest spans so the clauses can sit together without CSS

app/views/charge.njk, locales/cy.json, locales/en.json
This is unlikely and has always been technically possible but
selfservice didn’t allow you to set it up, soon [it will](https://github.com/alphagov/pay-selfservice/pull/1453)
So this makes sure we have messaging for it.
I have winged the Welsh using my innate ability as 50% Welsh and the
fact it looks like the nouns and words around dont change, I tried it
out in Google Translate too 🏴󠁧󠁢󠁷󠁬󠁳󠁿
=> PP-5181 - Adding line for if service only accepts credit cards

app/services/state_service.js, test/services/state_service_test.js
With stripe 3ds authorisations, the actual authorisation is triggered by
a notification, so has nothing to do with what the browser is up to. For
this reason, if there is some network slowness you can end up with the
user being returned after the payment has been authorised. Currently
this ends up with the user having the 'payment in progress' screen
displayed, because the state enforcer did not like that combination of route
and status. This PR allows this combination.
=> PP-5191 Allow auth success for auth handler

app/assets/javascripts/browsered/form-input-confirm.js
`.after()` is not compatible with IE as described here - https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/after
so replacing with something more robust
=> PP-5212 - Replace .after() function for compatibility

app/views/charge.njk
The CVV defaulted to 100% width on mobile which pushed the card icon
down onto the line below which looks bad.
Also year should be wide enough for 4 digits as some people may enter
the full year and it makes it easier to read if that happens
=> PP-5259 - Use correct classes to size the CVV and expiry inputs

app/assets/sass/modules/_web-payments.scss
After a person submits a Apple/Google Pay payment we disabled the
button, we didn’t have any default styling so it went green. This
overrides it to match the styling better
=> PP-5225 - styling for disabled web payments button

app/assets/javascripts/browsered/web-payments/index.js, app/assets/sass/modules/_web-payments.scss, app/views/charge.njk
If both are available we had overrode the Apple Button with a Google one.
Now we make a separate form for each and use Javascript/CSS to determine which one to present to user.
Had to also rejig the JS to understand there are two forms on the page and it needs to set event listeners on both
=> PP-5279 - fix Apple Pay when Google Pay is also availabled

app/views/charge.njk
Whilst it makes the number pad show on older iOS devices also then show
native error pop ups if the users uses non whitelisted characters we
want to allow people to enter their card number with or without spaces.
Editing the regex to allow spaces stops it from showing the number pad
so it’s redundant to include it.
=> PP-5366 - pattern is problematic

Dockerfile
By having bash as PID 1, we have a problem. Signals sent to the container (e.g.
SIGTERM to shut it down) will not reach npm - bash will not pass them on. This
means that shutting the container down is done uncleanly. Once the SIGTERM is
ignored, the container orchestrator will then send a SIGKILL and forcibly exit
the process.
We could make npm PID 1 instead but this creates further problems - If npm
creates any child processes and those processes (or any of their children) die,
npm will be the parent of them and will not know to waitpid() on them, so they
will remain zombies forever.
tini solves these problems - it will correctly reparent orphaned child
processes and pass signals through to npm.
=> RED-116: Use tini in docker to run node

app/views/charge.njk
In some modern browsers when a pattern attribute is added a native
browser message pops up and blocks form submission. They’re not helpful
and just suppress our more helpful error messages.
Thanks @nickcolley for the tip https://github.com/alphagov/govuk-design-system/issues/941#issuecomment-506286337
=> PP-5366 - Suppress native browser validation

package-lock.json, package.json
Which includes this fix https://github.com/alphagov/pay-product-page/pull/149
=> BAU - bump to latest version of product page

app/views/confirm.njk, locales/cy.json, locales/en.json, test/charge_ui_tests.js
- Moved button back to bottom and changed it back to just say 'Confirm
payment'
- Added the summary panel on the right
- Removed the table that replaced the summary panel
=> PP-5406 - revert confirmation page design changes

package.json
=> BAU - Bump pay-js-commons from 2.5.0 to 2.6.0

package.json
- Bumps pay js commons to 2.7.0
=> Bump pay-js-commons to 2.7.0

app/assets/sass/application.scss, app/assets/sass/modules/_button-reset.scss, app/assets/sass/modules/_summary-panel.scss, app/views/charge.njk, app/views/confirm.njk, app/views/layout.njk, package-lock.json, package.json, server.js
Updated all templates to meet breaking changes as part of 3.0.0 release which are all detailed here — https://github.com/alphagov/govuk-frontend/releases/tag/v3.0.0
This 3.0 release includes numerous accessibility updates but most visually prominent is the all new colour scheme - https://designnotes.blog.gov.uk/2019/07/29/weve-made-the-gov-uk-design-system-more-accessible/
=> PP-5560 - govuk-frontend 3.0 upgrade

cypress.json
Videos add a time overhead to test runs and we never look at them.
Disable them to speed up ci builds.
=> BAU Disable cypress videos

test/cypress/plugins/stubs.js, test/fixtures/pact_base.js, test/fixtures/payment_fixtures.js, test/unit/clients/connector_client_charge_tests.js, test/unit/clients/connector_client_google_authentication_tests.js
Add pact test for GET charge connector endpoint. Include the new 'integration_version_3ds' property of the gateway account.
Modify pact_base so that it will add matchers for objects in nested arrays so that we can assert on the structure of 'card_types' entries.
Remove fields from charges fixture which are not used in frontend.
=> PP-5546 Add pact test for find charge

app/services/clients/connector_client.js, test/fixtures/worldpay_3ds_flex_fixtures.js, test/unit/clients/connector_client_worldpay_3ds_flex_tests.js
Add a method to connector client to call the connector endpoint to get a Worldpay 3DS Flex DDC JWT.
Add a pact test for this interaction.
=> PP-5546 Add client method to get JWT from connector

app/controllers/charge_controller.js, app/services/worldpay_3ds_flex_service.js, app/utils/logging.js, app/views/includes/scripts.njk, test/controllers/charge_controller_test.js, test/fixtures/worldpay_3ds_flex_fixtures.js, test/services/worldpay_3ds_flex_service_test.js
If a gateway account has payment provider "worldpay" and 3DS integration version of 2, call connector to get the JWT for DDC and store it on the window.Charge object.
Have added unit tests for worldpay_3ds_flex_service.js, but not integration tests as appropriate integration tests should be added when the device data collection is implemented.
=> PP-5546 Get Worldpay 3DS Flex JWT on card details page

test/cypress/plugins/stubs.js, test/fixtures/payment_fixtures.js, test/unit/clients/connector_client_charge_tests.js
This test is really to ensure `worldpay_3ds_flex_ddc_result` is a valid
property in the auth request to connector.
=> PP-5545: Pact test for authorising card

app/assets/javascripts/browsered/form-validation.js, app/browsered.js, app/views/charge.njk, app/views/includes/scripts.njk, package.json
For this story we need to augment form validation with a worldpay lookup.
We want to do this in a separate JS file/function but to do this we need to move form-validation.js so that we can require other JS files.
The PR does that. Once it’s moved our linting rules apply, so we did that too.
=> PP-5548 move form validation to browserify

app/assets/sass/application.scss, app/assets/sass/modules/_accessible-autocomplete.scss
The accessible autocomplete has yet to be moved to the design system as such some thing looks a little bit funky this fixes those things.
=> PP-5573 accessibility fixes for autocomplete

.github/workflows/product-page.yml
When a new release of product pages is generated (which should be done
automatically by the action in that repo) it will trigger this action to
update the package link and raise a PR for the change.
=> REP: Github action to update product page package

.github/workflows/product-page.yml
We don't want the GitHub action triggered by a product page release to
update every package, just pay-product-page
=> REP: Only automatically update product-page

test/fixtures/payment_fixtures.js, test/unit/clients/connector_client_worldpay_3ds_flex_tests.js
Add pact test to assert that the response to a call to /v1/frontend/charges/{CHARGE_ID} for a Worldpay payment with status AUTHORISATION 3DS REQUIRED and 3DS flex challenge details saved contains a worldpayChallengeJwt property.
=> PP-5554 Add pact test for challenge JWT

app/middleware/state_enforcer.js
Remove line break from within a log message string to help us find both
parts of the message in Splunk.
=> BAU Remove line break in log line

app/controllers/three_d_secure_controller.js, app/services/normalise_charge.js, app/views/auth_3ds_required_out.njk, test/fixtures/payment_fixtures.js, test/integration/three_d_secure_ft_tests.js, test/test.env, test/utils/normalise_test.js
Include a hidden field in the 3ds_required_out form for the Worldpay
challenge JWT if it is present, and post to the Worldpay challenge URL,
which differs depending on whether gateway account is a live or test
account.
In three_d_secure_ft_tests, add new test cases for 3DS flex and use the
payment fixtures rather than test_helper to construct the mocked
connector get charge response.
=> PP-5554 Include JWT in 3ds_required_out form

app/controllers/charge_controller.js, app/models/charge.js, test/integration/charge_ft_tests.js, test/integration/charge_validation_ft_tests.js
Writing a unit test for PP-5550 is complicated. Possible - but complicated.
This is because the charge_controller's "create" method is unwieldy, too big
and overly complicated. Shockingly there are no unit tests for the method.
Unsurprising given the complexity of the code.
In order to write a unit test for PP-5550 I've decided to make small
incremental simplifications and eventually move the validation code into its
own class. But for now, this method gets rid of the 'let userEmail' as its
result is never used.
I have also taken a decision - in conjunction with @mrlumbu and @sfount - to
get rid of some AWSXray code. It makes code look more complicated; and in
reality we use request ids and charge ids to trace a request through the
system.
_Steps …
=> PP-5550: Minor simplification of charge_controller

app/services/clients/base_client/base_client.js, app/utils/add_proxy.js, app/utils/flattened_paths.js, test/test_helpers/html_assertions.js, test/unit/clients/connector_client_charge_tests.js
- es-lint upgrade is stopping builds for a new rule that contrary to es-lint's setup is not being deprecated
=> BAU PR-1014 add lint ignore

Dockerfile
Snyk has a dependency that needs git and so the container needs git
available to it
=> BAU - snyk has a dependency that needs git installed

Dockerfile
This reverts commit 057694d8c3908efbb6420dff2085616146c4ce9c.
I think this was a red herring for some reason when changing
package.json something changed that borked NPM and made it try and
install a package with git. I think this isnt normal. So we dont need
git in the container.
=> Revert "BAU - snyk has a dependency that needs git installed"

package.json
We use `govuk-country-and-territory-autocomplete` which includes the
accessible-autocomplete as a dependency so we dont need to explicitly
call it ourselves
=> BAU - Do not need to include accessible-autocomplete

app/middleware/logging_middleware.js, package-lock.json, package.json, server.js
The middleware uses morgan to log requests in a JSON format using a format function from pay-java-commons which produces a log line as a JSON string.
We then parse this as JSON and give it to our custom logger, which uses winston to produce a structured log message which also includes all the global keys we log for all lines.
Outputs logs of the format:
```
{
"logger_name": "/app/app/middleware/logging_middleware.js",
"remote_address": "::ffff:172.18.0.1",
"method": "GET",
"url": "/assets/fonts/light-94a07e06a1-v2.woff2",
"http_version": "1.1",
"status_code": "200",
"content_length": 33382,
"referrer": "http://localhost:9000/stylesheets/application.min.css",
"user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 …
```
=> PP-5764 Add middleware to log requests in JSON format

app/utils/logger.js, package-lock.json, package.json
Add an 'environment' field to the logs, so that it is possible to filter
by environment using a Splunk text search. Splunk does currently extract
the environment from the source if it is explicitly searched on using
e.g. the term 'environment="production-2"', but some of our reports use
a text search so will not pick up on all log lines.
The text search continues to work for many logs where the environment is
included in some way in the log message, but not for others where it
isn't so it makes sense to get rid of this ambiguity.
=> PP-5764 Include environment field in logs

app/utils/logger.js, app/utils/sentry.js, package-lock.json, package.json, server.js
Send error level log messages to Sentry. Using the log level to
control when messages are sent to Sentry seems intuitive and since we now
require a common logger throughout the application it offers a
convenient point to add Sentry.
Unhandled exceptions will be caught by the Sentry error middleware added
within `server.js` as per the guidlines when using Sentry with Express.
When initialising Sentry a `beforeSend` filter is added to remove the
`request` element from the event if it exists. The `request` element contains the
data from a failed request and this can include sensitive information such
as card numbers. We may want to introduce more refined filtering to allow
non-sensitive information from a failed request to go to Sentry at a
later date.
`app/utils/sentry.js` and more elements …
=> PP-5754 Add Sentry

app/utils/sentry.js
When we enable Sentry we effectively override the original `error`
function on the logger so that we call `Sentry.captureException` before
proceeding to log the error by calling the original `error` function on
the logger. Since `logger.error` can be called with various arguments it
isn't sufficient to simple call `originalLogger.error(msg)` since this
can lose structured arguments of the form `logger.error( "some message",
{ key: "value" } )`. By passing the spread `arguments` that were
provided we should end up with the original log message had we not
inserted Sentry.
Futhermore, by creating the message for the `Error` we send to Sentry by
`JSON.stringify`'ing the arguments provided we capture richer
information than simplying taking only the message which would be
`arguments[0]`. Since …
=> PP-5754 Pass original logger.error arguments after Sentry call

app/middleware/state_enforcer.js
We log when the state enforcer decides that the charge is not in the correct state to access a route, and as a result render an appropriate page. This is business as usual, and part of the design of connector, so we shouldn't log this at ERROR level, instead log at INFO level.
Co-authored-by: Dan Worth <dan.worth@digital.cabinet-office.gov.uk>
=> PP-5758 Change state enforcer log line to log at INFO level

app/models/card.js
Card id responds with a 422 if frontend sends it an empty card number or a card number of the wrong length. Currently, this response is swallowed and nothing is displayed to the user. There is an issue with how we do this, as an unhandled error is thrown but this commit doesn't seek to resolve this.
This commit treats a 422 response as a validation error and displays an appropriate message to the user.
=> PP-5758 Handle 422 responses from card id

app/controllers/three_d_secure_controller.js
- We have few 3DS payments (1-2 payments/day) failing with error response (`error code: 1, error: Internal error`) from Worldpay.
Although the exact reason is not known, Worldpay has indicated we didn't send full paRes in payload for one of the payments.
Log paRes to ruleout/to find if it is cause of failure.
=> PP-5778 Temporarily log paRes post 3DS auth

app/controllers/three_d_secure_controller.js, package.json
- paRes received during authorisation can be upto 4kb, but docker truncates long log lines as it doesn't support more than 2kb.
- Only log the beginning and last of paRes so we can check if connector receives full paRes for failed payments
Related to https://github.com/alphagov/pay-frontend/pull/1141
=> PP-5778 Log part of paRes

package.json
- re-added `npm run lint` which got accidentally removed in https://github.com/alphagov/pay-frontend/pull/1143
=> BAU - Readd linting

app/controllers/static_controller.js
Frontend should assume that naxsi blocks are valid and therefore log at
INFO rather than ERROR.
=> PP-5806 Log naxsi rule blocks at INFO level

app/routes.js, app/views/auth_3ds_required_in.njk
* we cannot guarantee the behaviour for cookies being set on our 3ds
pages
* this seems to negatively impact payment journeys and doesn't defend
against a particular risk surface
=> PP-5822 Remove CSRF from 3ds iframe routes

app/controllers/three_d_secure_controller.js, app/models/card.js, app/models/charge.js, app/services/charge_param_retriever.js, app/services/clients/connector_client.js, app/utils/charge_validation_backend.js, app/utils/logging.js, app/utils/request_logger.js
These dashes were there previously because before we logged in JSON the
logger would concatenate the JSON object it was passed as a second
parameter into the line.
Now, however, the keys in this JSON object are merged into the top-level
JSON object for the logline, so there is a hanging dash on the end of
the message which makes it appear that the message is incomplete. Remove
these.
=> BAU - Remove trailing dashes in log lines

app/middleware/csp.js
* envrionment variables are case sensitive
* `environment` -> `ENVIRONMENT`
=> PP-5846 Fix CSP environment variable case

app/services/charge_param_retriever.js, app/utils/cookies.js, test/middleware/csrf_test.js, test/services/charge_param_retriever_test.js
- Log a different line if the session cookie is entirely missing as opposed to present, but the charge id is missing.
- Log the URL and the method for the request
- Log the referrer. Note, however, it seems that if the user clicks back in their browser, this will probably be the referrer for the initial request rather than the page they were on when they clicked back.
- If the cookie is present but the charge is not on it, log the other charge variables that are present on the cookie.
=> PP-5851 Add additional logging when session cookie not present

app/models/charge.js
Log charge id info when the `Calling connector cancel a charge failed` log
appears. This should also be logged at info level.
=> PP-5809: Log charge id 

app/services/charge_param_retriever.js
It has been determined that in the vast majority of cases, this line is logged when the user has completed their payment and then attempted to go back to a payment page after we have removed the session variable from their cookie.
Therefore this is creating a lot of noise in Sentry when it is mainly business as usual.
We might want to investigate whether we should be immediately removing the cookie when we return the user to the return_url. If we didn't we would be able to show the user a more meaningful page, which might be desirable as the user clicking back occurs a lot.
=> PP-5851 Log charge id missing from session at INFO level

app/views/charge.njk
* in order to avoid 'unsafe-inline' for our style
content-security-policy we can't have inline styles in our markup
* trusted javascript can still manipulate inline styles
* favour class instead of inline style for display: none
=> PP-5824 Remove inline styles from card payment page

app/middleware/csp.js
- Turn CSP protection on with report only option
- add required exceptions
- 'unsafe-inline' from scriptSrc shall be removed once [PP-5872](https://payments-platform.atlassian.net/browse/PP-5872) completed
with @sfount
=> PP-5873 turn CSP on with report only option

app/assets/javascripts/browsered/form-validation.js, app/assets/javascripts/browsered/helpers.js, app/browsered.js, app/views/charge.njk, app/views/includes/scripts.njk, package.json, test/cypress/integration/card/payment.spec.js, test/integration/charge_billing_address_ft_tests.js, test/integration/charge_ft_tests.js
- Externalise `address country` autocomplete & setting global charge ID scripts to helper.js, so we don't need to allow unsafe-line scripts as part of CSP
- Add exception for `openregisterLocationPicker` as linter complains it as 'not defined'. `openregisterLocationPicker` is defined in a script (`location-autocomplete.min.js`)  loaded separately
There is no visible impact (when running locally) on performance due to externalisation of these scripts
**Before the change**
**and After the change**
=> PP-5872 Browserify Card details page inline scripts

app/middleware/csp.js, app/views/charge.njk, app/views/includes/analytics.njk, app/views/includes/scripts.njk, server.js
A number of the inline scripts on the card payment page are dynamically
templated in based on various params that can change per journey. This
makes them complex to safely hash.
Use a `nonce` generated per request to remove the need for `unsafe-inline`.
Older browsers can't gaurantee consistent behaviour with the nonce CSP
rule (introduced in CSP 2). Adding 'unsafe-inline' will be rejected by
browsers that support `nonce` and executed by older browsers that do
not.
---
Completes the `nonce` implementation from https://github.com/alphagov/pay-frontend/pull/1199
=> PP-5883 Add nonces to non external scripts

app/middleware/csp.js
A number of the inline scripts on the card payment page are dynamically
templated in based on various params that can change per journey. This
makes them complex to safely hash.
Use a `nonce` generated per request to initially allow rejected
`unsafe-inline` policy.
---
As we extend the base design system `layout` template we inherit a
script to set a 'js-enabled' class on themain page.
We don't have control to add a nonce here and the script never changes
so allow this particular hash.
=> PP-5885 CSP exceptions for non-external scripts

app/middleware/csp.js, test/middleware/csp_test.js
Why?
When enabling csp in enforce mode for end2end tests, the zap tests are failing
because they try to inject the script into the frontend page (which csp is preventing
from doing).
It seems we're not allowed to simply disable javascript while running selenium tests,
so in order to workaround the issue with injectint the script we're going to allow it,
but only when specified in environment variable (it will be set only for end to end tests)
Changes:
* add hash to scriptSrc derective if it's set up in environment variable
* add test to cover the new scenario
=> [PP-5887] add zap test hash to csp depending on configuration

app/middleware/csp.js, test/middleware/csp_test.js
Why?
When enabling csp in enforce mode for end2end tests, the zap tests are failing
because they try to inject the script into the frontend page (which csp is preventing
from doing).
It seems we're not allowed to simply disable javascript while running selenium tests,
so in order to workaround the issue with injecting and evaluating the script we're going to allow it,
but only when specified in environment variable (it will be set only for end to end tests)
Changes:
* replace hash (which works only for inline scripts) with `unsafe-eval`
* update test
=> [PP-5887] allow unsafe-eval scripts when configured

app/middleware/csp.js, app/routes.js, server.js, test/middleware/csp_test.js
- add csp headers to worldpay 3ds flex ddc frame
- refactor csp.js to have separate methods for different csp settings
=> PP-5884 add csp restrictions to worldpay flex ddc initial iframe

app/middleware/csp.js
- Added `unsafe-inline`source to script-src directive to allow execution of inline scripts. This is required for browsers that only support CSP level 1 as nonce/hash is not supported in these browsers. Browsers that support CSP level 2, ignores `unsafe-inline` if nonce/hash is available.
=> PP-5885 Add unsafe-inline to script-src directive

app/middleware/csp.js
- https://www.gstatic.com/instantbuy/icons/ serves an image that required by GPay and thus we need to whitelist it.
=> PP-5902 add gstatic site to csp img-src directive

app/middleware/csp.js
The country autocomplete injects styles by replacing an elements `cssText` attribute. 
This evaluation is blocked on mobile browsers but allowed on modern Desktop. 
As we will be restricting the scripts that can execute at page load, allow this eval on mobile.
=> PP-5903 Allow eval of style for mobile browsers

app/middleware/csp.js
- remove the trailing slashes from urls for host sources. This is necessary as some old browsers with CSP V1 support will not understand it and thus going to ignore it (path was introduced in CSP V2)
=> PP-5901 remove trailing slashes from hosts

app/middleware/csp.js
Why?
We've introduced them thinking it's required for csp to work on apple pay.
When re-reading documentation (https://developer.apple.com/documentation/apple_pay_on_the_web/setting_up_your_server#3172427)
it seems we need to wihtelist the domains only for server talking to apple.
The frontend side of things talks only to backend, not to apple directly.
Changes:
* remove whitelisted apple-pay domains
=> [PP-5900] remove apple pay whitelisted hosts

app/controllers/charge_controller.js, app/middleware/retrieve_charge.js, app/models/charge.js, app/services/clients/connector_client.js, app/utils/logging_fields_helper.js, package-lock.json, test/middleware/retrieve_charge_test.js
Add common logging fields to an object on the request and retrieve them when we do logging to include them in the structured logs.
Added the `payment_external_id`, `gateway_account_id`, `gateway_account_type` and `provider` fields.
Included one example of getting these fields from the request object and passing them through to the logger.
=> PP-5762 Add common keys to logs

app/middleware/correlation_header.js, server.js
Add middleware to store the correlation on the commonLoggingFields object on the request so that it will be included in logs.
=> PP-5762 Add correlation id to logging

app/controllers/charge_controller.js, app/controllers/healthcheck_controller.js, app/controllers/return_controller.js, app/controllers/secure_controller.js, app/controllers/three_d_secure_controller.js, app/controllers/web-payments/apple-pay/merchant-validation-controller.js, app/controllers/web-payments/handle-auth-response-controller.js, app/controllers/web-payments/payment-auth-request-controller.js, app/middleware/csrf.js, app/middleware/resolve_service.js, app/middleware/retrieve_charge.js, app/middleware/state_enforcer.js, app/models/card.js, app/models/charge.js, app/models/token.js, app/services/charge_param_retriever.js, app/services/clients/adminusers_client.js, app/services/clients/connector_client.js, app/services/worldpay_3ds_flex_service.js, app/utils/ab_test.js, app/utils/charge_validation_backend.js, app/utils/logging.js, app/utils/request_logger.js, app/utils/response_converter.js, app/utils/response_router.js
In all places where we do logging, retrieve the logging fields that we've added to the request and pass them to the logger.
As part of doing this, have removed the `logging.systemError` method as the purpose of this was to log certain values in the error which are now added to the logging fields stored on the request.
=> PP-5762 Log fields added to request object

app/models/card.js, app/models/charge.js, app/services/clients/connector_client.js, app/utils/request_logger.js
The correlation id is now added as a structured argument. Remove it from log messages where it is in square brackets at the start of the message for consistency.
=> PP-5762 Remove correlation id from log message

app/controllers/charge_controller.js, app/controllers/healthcheck_controller.js, app/controllers/return_controller.js, app/controllers/web-payments/payment-auth-request-controller.js, app/middleware/resolve_service.js, app/middleware/retrieve_charge.js, app/models/charge.js, app/services/clients/connector_client.js, app/utils/logging.js, app/utils/request_logger.js, app/utils/response_converter.js
Add keys to log lines containing useful information, such as the error.
Make it so that when we log a http status code, we always use "status_code" as the key.
=> PP-5762 Add appropriate keys to log lines

app/middleware/logging_middleware.js, package-lock.json, package.json
The new version of pay-js-commons adds a field for the request id
extracted from the request header in `request-log-format`.
Use the new version of pay-js-commons and change how we require the log
format to use this.
=> PP-5762 Include correlation ID in incoming request logs

app/middleware/csp.js, app/routes.js
- redirect is blocked on some browsers when the site that we're redirecting to is redirecting to a different domain, eg on cancel we redirect the user to example.com/abc and that site redirects the user to example.org/abc. hence the need to use * for form action in case the redirectToServiceImmediatelyOnTerminalState flag is true
- if redirectToServiceImmediatelyOnTerminalState is false, we let the to be posted to self and products (when the user is coming from a payment link, the page automatically redirects the user back to products)
=> PP-5933 add form action covering direct redirect feature

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js
- When submitting card details to Worldpay flex, wallet options (google/apple pay) & any previous error messages were still shown
to users.
- Changes hides wallet options and error container if Worldpay 3DS flex payment is in progress
with @sandorarpa
=> PP-5940 Hide Wallet/Error containers during Worldpay 3DS flex payments

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js, app/views/charge.njk
- Refactor payment method divider on card details page - assigned IDs and used the same in 3DS flex javascript, instead of processing by class name which can break if more components are added with same class name
- Hide `or` element within divider
=> PP-5490 Hide payment method divider word and refactoring

app/controllers/charge_controller.js, app/models/card.js, locales/cy.json, locales/en.json, test/cypress/integration/card/payment.spec.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment_fixtures.js, test/models/card_test.js
* add error code key for prepaid cards (en)
* logic for blocking cards if the gateway account configuration is set
to block
* validate behaviour with cypress
=> PP-5937 Frontend blocks prepaid cards

app/middleware/csp.js
The country and territory autocomplete seems to require `'unsafe-inline'` to be listed as one of the sources for the `style-src` Content Security Policy directive.
We believe this is because the accessible autocomplete component upon which it is built tries to set the `style` attribute on an element when it detects it is running in an iOS browser.
We have filed an upstream issue: https://github.com/alphagov/accessible-autocomplete/issues/398
=> PP-5959 CSP: country autocomplete needs script-src 'unsafe-inline'

app/middleware/csp.js
Reverts alphagov/pay-frontend#1259 because ZAP tests fail in there’s a CSP with `style-src 'unsafe-inline'`.
=> Revert "PP-5959 CSP: country autocomplete needs script-src 'unsafe-inline'"

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js, app/views/charge.njk, test/cypress/integration/web-payments/apple-pay.spec.js, test/cypress/integration/web-payments/google-pay.spec.js
- Rename `payment-method-submit` to payment method specific as buttons for both apple/google pay uses same ID which is against HTML guidelines and interferes with using `document.getElementById` method.
with @sandorarpa
=> PP-5940 Rename payment-method-submit button

app/middleware/csp.js
Reverts alphagov/pay-frontend#1260 because hopefully frontend ZAP tests no longer check our CSPs.
=> Revert "Revert "PP-5959 CSP: country autocomplete needs script-src 'unsafe-inline'""

app/views/includes/analytics.njk, test/analytics_ui_tests.js
Description:
- Complying with ICO guidance around cookie consent we can't set non-essential cookies without consent being granted. In the short term then we have to disable Google Analytics as it stores cookies
- Uncomment when we have enabled opt-in and remove the empty ga() function
- Renable analytics_ui_tests.js when Google Analytics is enabled
=> PP-5977 Remove Google Analytics Front end

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js, app/views/charge.njk
- Move `or` separator to apple/google pay forms, so it is only displayed if payment methods are shown to users and not when the feature is enabled on gateway account
- rename spans to have unique IDs and hide both during 3DS flex journey
=> PP-5985 Fix `or` separator

app/middleware/csp.js
The `prefetch-src` directive was added to the CSP for the enter card details page in commit 65017dd4864b12c5ddddf753ad06fee6a9a62f9c because the ZAP CSP Scanner complains if it finds a CSP that has a lax `prefetch-src` (not specifying one allows prefetches from anywhere, so is considered lax).
However, we disabled the ZAP CSP Scanner because it was complaining about other directives we are not in a position to modify.
Therefore, we can now remove `prefetch-src` from the CSP for the enter card details page. It’s an experimental CSP3 directive and we decided not to support those yet. In addition, no browsers support it yet:
- https://caniuse.com/#search=prefetch-src
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src#Browser_compatibility …
=> PP-5987 Remove prefetch-src directive from enter card details CSP

test/cypress/integration/card/payment.spec.js
- Update payments specs to assert that the divider is not displayed apple/google pay is disabled for a service
=> PP-5895 Assert divider is not visibile on card details page

dev.yml, manifest.yml, package-lock.json, package.json
I've updated the Node version to 12.11.1 which is a supported PaaS
version. The Docker image builds successfully with this version.
I simplified the manifest, removing the proxy environment variables
because I think those should be set during the "infrastructure"
provisioning step globally for all apps. Also they're not needed in the
dev environments. I've added a `dev.yml` which just defines dummy values
for some of the variables.
Push this app to your dev environment (you may have to delete the existing app with `cf delete card-frontend`):
```
cf push \
--vars-file dev.yml \
--var space=dev-yourname \
--var card_frontend_url=pay-card-frontend-dev-yourname.london.cloudapps.digital
```
PaaS will take care of running `npm install`.
=> PP-6029: Update PaaS manifest

package.json
PaaS node buildpack no longer supports 12.11.1. To avoid having to keep
bumping the engine version whilst maintaining compatibility with our
existing docker image build process, this pins the major version whilst
accepting minor and pataches releases greater than 12.11.1.
=> PP-6031 Bump engine version

app/controllers/charge_controller.js, app/middleware/resolve_service.js, app/views/charge.njk, app/views/includes/scripts.njk, test/charge_ui_tests.js, test/cypress/integration/card/billing-address-collection.spec.js, test/cypress/integration/card/email-collection.spec.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment_fixtures.js
Currently, we don't show fields to collect the billing address on the card details page if billing address collection is disabled for the service.
Now, we also won't show these fields if a payment is a MOTO payment even if billing address collection is enabled for the service. Determine whether we should collect the address in the resolve_service middleware and add a field to res.locals so that we can access it in all templates
and controllers that need this value.
Add Cypress tests to test this and remove tests from charge_ui_tests which are now better covered by Cypress tests.
=> PP-6079 Don't collect billing address for moto payments

test/fixtures/payment_fixtures.js, test/unit/clients/connector_client_charge_tests.js
Add a frontend -> connector pact test to ensure that it is possible to
authorise a charge without sending a billing address.
=> PP-6079 Add pact test for authorisation without a billing address

env-map.yml, manifest.yml
Add a build pack that extracts values from within VCAP_SERVICES which is
where the credentials from bound services will be provided to the app
running on PaaS. Using this buildpack means we do not need to alter how
our app works, but rather provide a mapping from the VCAP_SERVICES var to its
current name.
Tested by pushing manually to staging and the correct vars are set.
```
GDS5062 > cf ssh card-frontend -c "/tmp/lifecycle/shell /home/vcap/app 'env | sort'" | grep URL
ADMINUSERS_URL=http://adminusers-stg.apps.internal:8080
FRONTEND_URL=https://card-frontend.staging.gdspay.uk
GDS5062 > cf ssh card-frontend -c "/tmp/lifecycle/shell /home/vcap/app 'env | sort'" | grep HOST
CARDID_HOST=http://cardid-stg.apps.internal:8080
CONNECTOR_HOST=http://card-connector-stg.apps.internal:8080
```
=> PP-6085 Add env-map buildpack

env-map.yml, manifest.yml
Env vars which are specific to card-frontend and differ by environment
are to be provided via the card-frontend-secret-service. The mapping
between these vars and their keys within the vars returned by
card-frontend-secret-service are defined within env-map.yml.
=> PP-6127 Add frontend secret service

package-lock.json, package.json
- Update Product Page module to use v4.0.6 which fixes the typo.
=> PP-6191 Product Pages - Fix typo in copy

package-lock.json, package.json
- Bump `pay-js-commons` from 2.24.0 -> 2.25.0
=> BAU Bump pay-js-commons

env-map.yml, manifest.yml
Set the `METRICS_HOST` and `METRICS_PORT` from the app-catalog to send
metrics to the carbon-relay app.
=> PP-6254: Add carbon relay config

app/controllers/three_d_secure_controller.js
We've noticed several ePDQ payments are dropping out when redirecting to the `3ds_required_out` route in frontend. There's nothing in the logs to suggest what might be happening here, so log an error when this happens.
If it is dropping out at this point it's probably because we aren't handling an authorisation response from ePDQ correctly (or maybe there's an issue on their end).
=> PP-6194 Log when there is an error redirecting to 3DS

app/controllers/three_d_secure_controller.js, test/integration/three_d_secure_ft_tests.js
When frontend calls connector to authorise a 3D Secure result with the payment gateway, redirect the user to the 3DS Secure page again if connector’s response indicates that this is required.
Connector indicates this by sending a response body of `{"status": "AUTHORISATION 3DS REQUIRED"}` when `/v1/frontend/charges/{chargeId}/3ds` is called (this isn’t actually implemented in connector yet but will be soon).
=> PP-6259 Make frontend send user to do 3DS again if necessary

app/utils/response_router.js, test/controllers/secure_controller_test.js, test/utils/response_router_test.js
Log all times we show either the "An error occurred" or
"We’re experiencing technical problems" pages.
This is to drive an SLI that will cover all times we display and error
to the user that will probably mean they can't complete their payment.
=> PP-6240 Log all times we show error page

app/services/clients/base_client/base_client.js, app/services/clients/cardid_client.js, app/services/clients/connector_client.js, test/controllers/web-payments/handle-auth-response-controller.test.js, test/integration/charge_billing_address_ft_tests.js, test/integration/charge_ft_tests.js, test/integration/charge_validation_ft_tests.js, test/integration/three_d_secure_ft_tests.js, test/unit/base_client_test.js
As part of this commit the following needed to be added to charge_ft_tests and
charge_validation_ft_tests
```
const app = proxyquire('../../server.js',
{
'memory-cache': {
get: function () {
return false
},
'@global': true
}
}).getApp()
```
This mocks out the memory-cache in the resolve_service (https://github.com/alphagov/pay-frontend/blob/master/app/middleware/resolve_service.js#L4).
It turns out:
- most of the tests across the project uses the same gatewayAccountId
- there is some test somewhere (I don't know where) that associates a service
to this gateway account which sets collectBillingAddress to false
This has a knock on effect on the rest of the tests where the billing address
needs to be collected and causes the following code in the charge_controller to
be executed …
=> PP-5805: Remove aws xray from base_client and tests

README.md, app/controllers/charge_controller.js, app/utils/google_pay_merchant_id_selector.js, config/google_merchant_id_to_gateway_account_id.js, test/utils/google_pay_merchant_id_test.js
This is so we can rotate the merchant id in a safe way and assign the usage of
a new merchant id to a specific gateway account to test it out in production.
=> PP-6330: Make frontend use two google pay merchant ids

app/controllers/charge_controller.js
This will help give us confidence during testing that a payment is using
GOOGLE_PAY_MERCHANT_ID_2.
=> PP-6328: Add logging if GOOGLE_PAY_MERCHANT_ID_2 is being used

app/assets/javascripts/browsered/epdq-3ds2.js, app/browsered.js, app/controllers/charge_controller.js, app/views/includes/scripts.njk, test/cypress/integration/epdq-3ds2/payment-with-epdq-3ds2.spec.js
Description:
- This adds extra browser information required for ePDQ 3DS2 which is read from the window object
- We decided to add the hidden input fields for this when the page is loaded as it is easier to test in Cypress
=> PP-6360 - Send additional ePDQ 3DS2 browser data from enter card details page

app/services/clients/connector_client.js
The `x-request-id` is already available to the logging context as this
uses the `getCommonLoggingFields` utility added during structured
logging.
This fixes an issue where `correlationId` is destructured into individual
characters in the logs.
=> PP-6368 Remove explicit correlation ID from get charge call 

test/integration/card_details_errors_ft_tests.js, test/integration/card_details_send_data_ft_tests.js, test/integration/charge_ft_tests.js, test/integration/charge_status_ft_tests.js
Split out `charge_status_ft_tests.js`, `card_details_send_data_ft_tests.js` and `card_details_errors_ft_tests.js` from `charge_ft_tests.js`.
No changes have been made to the tests: they’ve just been moved to different files.
with @nimalank7
=> PP-6361 Split charge_ft_tests.js some more

app/assets/javascripts/browsered/epdq-3ds2.js, test/cypress/integration/epdq-3ds2/payment-with-epdq-3ds2.spec.js
Correct the names of the hidden form fields that are added to the enter card details page if it’s an ePDQ 3DS2 payment: `jsScreenColorWidth` becomes `jsScreenWidth` and `jsScreenColorHeight` becomes `jsScreenHeight`.
=> PP-6360 Correct names of jsScreenWidth and jsScreenHeight params

app/controllers/three_d_secure_controller.js
The `paRes` received from the card issuer when the user has completed 3DS authentication can be very long. We were logging the `paRes` but unfortunately Docker splits lines that are longer than around 2,000 characters across several different lines. This breaks structured logging and makes anything on the second and subsequent lines very difficult to retrieve.
Work around this by splitting the `paRes` into segments of up to 1,000 characters each (number chosen so that it plus the characters on the rest of the line total less than 2,000) and logging a separate line for each segment. This preserves structured logging and keeps enough contextual information that we can reconstruct the full `paRes`.
=> PP-6380 Log 3DS paRes received across several lines

app/assets/javascripts/browsered/form-validation.js
- Consider pence for total amount calculation when applying corporate surchage on `entering card details page`
- Currently amount (from enter card details page) is treated as integer which is resulting in incorrect total amount on the page. There is no impact on the backend
=> ZD#4115502 Fix total amount calculation

locales/cy.json, locales/en.json, test/cypress/integration/card/token-reuse.spec.js
- Update text `Go back to try the payment again` to "Cancel and go back to try the payment again` on payment progress page to make the action clear to the users
=> ZD#4109437 Update text on payment in progress page

package.json
The highest version of 12.X node that pass build pack supports is 12.16.3 so
set the node engine version to use this or higher. This setting is only
used by PaaS buildpack at present since Jenkins Ci will reference .nvmrc
and the app is deployed to current infra in a container with node
version set via the docker image base.
**WHAT**
Current paas error
```
**ERROR** Unable to install node: no match found for ^12.18.1 in [10.19.0 10.20.1 12.16.2 12.16.3 13.12.0 13.14.0]
```
=> PP-6676 Set node version for concourse build packs

app/controllers/charge_controller.js, app/services/example_card_expiry_date.js, app/views/charge.njk, locales/cy.json, locales/en.json, package.json, test/controllers/charge_controller_test.js, test/cypress/integration/card/payment.spec.js, test/services/example_card_expiry_date_test.js
Make the example card expiry date on the enter card details page always use a year two years ahead of the current year in the UK.
When it’s 2020 in the UK, the example card expiry date will be 10/22. When it’s 2021 in the UK, the example card expiry date will be 10/23. When it’s 2022 in the UK, the example card expiry date will be 10/24. And so on. (The month always remains 10.)
This means that the example card expiry date will be between 1 year 10 months and 2 years 10 months in the future, which is appropriate given that most cards expire between 3 and 5 years after they are issued.
The example year will change just once each year at the midnight between New Year’s Eve and New Year’s Day in the UK.
=> PP-6706 Make example card expiry date always be in the future

.dependabot/config.yml
- add govuk-pay default label to repo so it shows up in the unified dependabot updates view
=> BAU add default label for dependabot updates 2

.dependabot/config.yml
- add dependencies default label to repo so it shows up in the unified dependabot updates view
=> BAU add more default label for dependabot updates

test/cypress/integration/card/payment.spec.js
The `cy.clock(…)` function only overrides what time the browser thinks it is, not what the time is on the server.
This means that when running the Cypress tests, the example expiry date shown on the enter card details page will always be two years out from the actual current year. Which will mean it will change from 10/22 to 10/23 on New Year’s Day, causing our Cypress test that looks for 10/22 to fail.
Not a great start to the new year.
Fix this by making the test instead just look for 10/_xx_ where _xx_ is any two digits.
We could try to calculate the current date at the time the test runs but this would have unreliable results around midnight on New Year’s Eve, when people are usually occupied by other things. We have unit tests that check the year is two years out, so just checking …
=> BAU — Stop Cypress tests breaking on New Year’s Day 🥳

app/assets/javascripts/browsered/web-payments/apple-pay.js, test/cypress/integration/web-payments/apple-pay.spec.js, test/cypress/utils/apple-pay-js-api-stubs.js, test/fixtures/wallet_payment_fixtures.js, test/unit/clients/connector_client_apple_authentication_tests.js
Fix Apple Pay when email collection is off by making it not try to validate an email address that isn’t there, which causes an error, which causes the Apple Pay authorisation process to hang for an uncomfortably long time before failing with an error.
=> PP-6611 Fix Apple Pay when email collection is off

package.json
Update to version 4.4.2 of the product page, which includes the Q2 2020–2021 roadmap
=> BAU — Update the roadmap for Q2 2020-21

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, app/controllers/web-payments/payment-auth-request-controller.js, app/utils/structured_logging_value_helper.js, test/controllers/web-payments/apple-pay/normalise-apple-pay-payload.test.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js, test/utils/structured_logging_value_helper_test.js
When we receive an Apple Pay or Google Pay payload, log some
selected properties like this (not a representative example):
```json
"message": "Received Apple Pay payload",
"selected_payload_properties": {
"token": {
"paymentMethod": {
"displayName": "Visa 1233",
"network": "visa",
"type": "debit"
}
},
"shippingContact": {
"givenName": "(empty string)",
"familyName": "(null)",
"emailAddress": "(redacted non-blank string)"
}
}
```
It’s not the complete payload, only some properties we manipulate before sending to connector. Properties with null values get removed somewhere in our logging pipeline, which is why values like `"(null)"` and `"(empty string)"` are used. Some property values may contain personally-identifiable information, so we don’t output the actual value there, instead using …
=> PP-6611 Log selected fields from Apple Pay or Google Pay payload

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js, test/controllers/web-payments/apple-pay/normalise-apple-pay-payload.test.js
Description:
- Apple Pay code which filters the supported card brands allows Discover, JCB, Maestro and Visa Electron for Apple Pay. However
when we normalise the card brand we only allow Visa, Mastercard or American Express which causes an error for users who try to pay with
Discover, JCB, Maestro or Visa Electron.
- This PR modifies the normalisation code to allow for these.
- A test has been added to check to see whether an exception is thrown when an unrecognizable card brand has been inputted. We decided against testing all the cards as testing a single card would be sufficient.
Paired with @narinderchana
=> PP-6613 - Allow all supported cards as normalised for Apple Pay

app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js
Description:
- Google Pay code which filters the supported card brands allows Discover, JCB, Maestro and Visa Electron for Google Pay. However
when we normalise the card brand we only allow Visa, Mastercard or American Express which causes an error for users who try to pay with
Discover, JCB, Maestro or Visa Electron.
- This PR modifies the normalisation code to allow for these.
- A test has been added to check to see whether an exception is thrown when an unrecognizable card brand has been inputted. We decided against testing all the cards as testing a single card would be sufficient.
=> PP-6613 - Allow all supported cards as normalised for Google Pay

app/controllers/web-payments/google-pay/normalise-google-pay-payload.js
Description:
- We don't allow Maestro when setting up Google Pay so we can remove it from the normalisation code to ensure consistency
=> PP-6613 - Disallow Maestro for Google Pay normalisation code

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js
- Extend the timeout of 3DS Flex queries to CC to increase potential
resolution and instances of the 3DS Flex check as opposed to a default
behaviour fallback.
=> BAU Extend 3DS Flex Timeout

app/utils/google_pay_merchant_id_selector.js, test/utils/google_pay_merchant_id_test.js
The environment variable that says which gateway account IDs should use `GOOGLE_PAY_MERCHANT_ID_2` rather than `GOOGLE_PAY_MERCHANT_ID` is a string containing space-separated IDs, which gets tokenised into an array of strings. The gateway account ID we look for in the array is a number, so it needs to be converted to a string first or we’ll never find a match.
=> PP-6328 Fix selecting Google Pay merchant ID by gateway account ID

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js, test/controllers/web-payments/apple-pay/normalise-apple-pay-payload.test.js
Description:
- If the displayName is less than four characters then map the last four digits to an empty string.
- If the last four characters of the displayName are not numeric then map the last four digits to an empty string.
=> PP-6614 Normalise the last four digits for Apple Pay

app/controllers/charge_controller.js
Only log `Using GOOGLE_PAY_MERCHANT_ID_2` if the Google Pay merchant ID matches `GOOGLE_PAY_MERCHANT_ID_2` and is not the same as `GOOGLE_PAY_MERCHANT_ID`.
Otherwise, if `GOOGLE_PAY_MERCHANT_ID` and `GOOGLE_PAY_MERCHANT_ID_2` are the same, we’ll log this message for every single payment (even when Google Pay isn’t available), which is just noise.
=> PP-6328 Don’t log “Using GOOGLE_PAY_MERCHANT_ID_2” so often

package-lock.json, package.json
- updates product pages to latest release
- uses https urls for npm repos in package-lock.json
=> BAU bump product pages from 4.4.2 to 4.4.3

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js, test/controllers/web-payments/apple-pay/normalise-apple-pay-payload.test.js
It is our understanding that if we receive an Apple Pay payload with an email address, we get a `shippingContact` object with an `emailAddress` property populated and other properties, such as `givenName` and `familyName`, set to empty strings (because we don’t actually request a shipping name when initiating Apple Pay). When there is no email address (because email address collection is switched off for the service), we believe we get no `shippingContact` object at all (though we would if we requested a shipping name).
Harden our code to remove the assumption that there’s always a `shippingContact` object.
=> PP-66611 Handle Apple Pay not having shipping contact better

app/views/includes/scripts.njk
We currently rely on the GOV.UK design system button behaviour of
`preventDoubleClick` "debouncing" form submission to prevent multiple
confirm submissions.
This debounce only lasts for 1 second so if a submission takes longer
then that (due to slow page load, slow Connector response, etc.) the
user could potentially press submit again. If submitted twice the second
submit is guaranteed to `403` as the first submit removes the users
session.
In order to maintain parity between the confirmation page and the
payments page, disable the form submission button after it has been
pressed. This `POST` request is terminal (it will either redirect or
render an error page) and so there is never a scenario where it needs to
respond to upstream events (i.e be clicked again).
Future PRs/ issues will …
=> PP-6857 Disable confirm payment button on submit

app/services/clients/connector_client.js, package-lock.json, package.json
Send metrics to port 8094 as we've configured telegraf to listen to TCP traffic
this port. This PR is meant to be a spike and will be reverted once we prove
metrics appear in hosted graphite.
=> PP-4733: Spike sending metrics to hosted graphite

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js, app/controllers/charge_controller.js, app/views/charge.njk, test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.spec.js
Add a hidden form field to the payment details form containing a status for the Device Data Collection (DDC) for Worldpay 3DS flex.
Update this status at various points in performing the DDC request. On the server side, log the value of this hidden status field so we can use this to determine at what point the DDC went wrong if we do not get a result to use.
Regenerate .secrets.baseline to ignore package.lock.json
=> PP-7075 Add logging for DDC request for Worldpay 3DS flex

app/models/card.js, app/services/clients/adminusers_client.js, app/services/clients/connector_client.js
The acceptance criteria on the story says 
```
Log a structured log line at error level with the message Error communicating with https://the-url-goes-here and a url key containing the URL and, if appropriate, a remote_http_status key containing the HTTP status code.
```
However some errors have already been logged with other messages. The important thing is that errors are being logged so I'm not too concerned about logging `Error communicating with https://the-url-goes-here`. 
`status_code` is already used in places so using this instead of `remote_http_status`.
=> PP-6995: Log downstream errors

app/controllers/charge_controller.js, app/services/normalise_charge.js, app/views/charge.njk, test/cypress/integration/card/moto-mask-payment.spec.js, test/cypress/utils/card-payment-stubs.js, test/utils/normalise_test.js
- Update `normalise_charge.js`, to pass the MOTO flag from the charge.
- Update Nunjucks template
- Use the MOTO value from the charge rather then the gateway account.
- General clean up of code
- Uppdate Cypress tests and payment stubs.
=> PP-6957 Fix MOTO Mask Frontend bug - to use the MOTO flag from the charge.

app/views/charge.njk
We had 2 labels for the `input` month element which causes accessibility issues.
=> PP-7113: Remove non-descriptive labelling

docker/build_and_test.Dockerfile
Previous upgrade to Node 12.8.4 accidentally moved to a non-apine base
image for the build and test Dockerfile. Revert to Node alpine.
=> PP-7195 Use node-alpine image for build Dockerfile (12.18.4)

docker/build_and_test.Dockerfile, package.json
This Dockerfile should be removed as soon as possible as it introduces
additional flake in the build/ update release process.
- Updated alpine `python` dependency doesn't resolve, specify that we
will be using the `python2` package
- Set the engines version to a paas compatible minimum until we can
patch that separately
=> PP-7195 Fix build and run Dockerfile alpine upgrade

test/middleware/enforce_session_cookie_test.js, test/middleware/retrieve_charge_test.js, test/unit/session_test.js
Description:
- Concourse CI build of the original PR did not catch the lint errors.
=> PP 7118 fix lint errors in move session cookie validation test

test/integration/three_d_secure_ft_tests.js
Description:
- Fix JS lint issues
- Users arrive at the 3DS required in page via a cross-site request and modern browsers treat cookies as SameSite=lax by default, which means we won’t sometimes won’t get sent the cookie when it’s a POST request. We’ll still require the cookie to continue further on the journey and actually process the 3DS result.
- Session cookie validation will not be required for /card_details/:chargeId/3ds_required_in & /card_details/:chargeId/3ds_required_in/epdq requests only.
=> PP-7118 Remove 3ds in cookie validation & lint fix

test/utils/charge_validation_fields/expiry_month_validation_test.js
Tidy up expiry date validation tests:
- Stub the current date to make the tests not rely on the actual current date, using 21 September 2020 (date picked to be far enough from the end of the month that different time zones are not going to cause issues)
- Don’t test multiple things in each test
No changes to anything apart from the tests. The test cases themselves are the equivalent to the old ones but some of the details differ to reflect the fact we’re stubbing the current date.
=> PP-7080 Tidy up expiry date validation tests

app/utils/charge_validation_fields.js, test/utils/charge_validation_fields/expiry_month_validation_test.js
Implement new expiry date validation algorithm, which takes a month and year (which have already had their whitespace stripped):
1. If _month_ is not exactly 1 or 2 digits, both in the range 0 to 9, return an `invalidMonth` error
2. If _month_ is 1 digit and that digit is 0, return an `invalidMonth` error
3. If _month_ is 2 digits and those two digits are not 10, 11 or 12, return an `invalidMonth` error
4. If _year_ is not exactly 2 or 4 digits, all in the range 0 to 9, return an `invalidYear` error
5. If _year_ is 4 digits and the first digit is 0, return an `invalidYear` error
6. If _year_ is 2 digits, prefix it with 20 (for example, 22 becomes 2022)
7. If _year_ is greater than 2099, return an `invalidYear` error
8. If _year_ is less than the current year, return an `inThePast` error …
=> PP-7080 Implement new expiry date validation algorithm

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js, test/cypress/integration/web-payments/google-pay.spec.js, test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.spec.js
Description:
- Currently when the service has Google/Apple Pay enabled and is using Worldpay 3DS Flex a paying user will see 'Pay with Google/Apple Pay' and 'Enter payment details' with a spinner. This is a bug because when the DDC is sent to Worldpay we hide most but not all of the elements on the card details page. This PR fixes this bug by hiding the elements which contain the above text.
- Since a user cannot click on 'Submit' and 'Pay with Apple/Google Pay' at the same time we can hide the entire container for Google/Apple Pay
- The confirmPaymentDetailsStubs was modified when being passed into 'DDC times out' test so this has been deep cloned so that subsequent tests won't be affected
- A further PR needs to be made conceptualising how we hide elements
- Cypress test indicates that …
=> PP-7116 - Remove text when DDC is sent to Worldpay

package-lock.json, package.json
- Bump the version of pay-js-commons from 2.40.0 to 2.42.0
=> ZD Bump pay-js-commons

app/utils/response_router.js, test/utils/response_router_test.js
Logging the fact we're rendering the error page isn't an error in itself.
=> PP-4329: Lower log level for rendering error response message

app/middleware/csrf.js
An error is a serious issue and represents the failure of something important
going on in the application. The ERROR level is not the appropriate level to
log csrf issues.
=> PP-4329: Use warn level for csrf issues

app/assets/javascripts/browsered/web-payments/helpers.js, app/utils/google-pay-check-request.js
We want to see what the payment page looks like when PAN_ONLY transactions are
disabled.
PAN_ONLY transactions are Google Pay transactions made on Chrome (usually on a
desktop).
CRYPTOGRAM_3DS transactions are Google Pay transactions made via the Google Pay
app. These transactions are "tokenized".
This PR is not meant to be deployed to prod and will be reverted promptly.
=> PP-7192: Disable PAN_ONLY Google transactions

app/assets/iframe/worldpay-3ds-flex-ddc.html, app/views/auth_waiting.njk, app/views/capture_waiting.njk, app/views/errors/incorrect_state/capture_waiting.njk, app/views/includes/iframe_head.njk, app/views/layout.njk
Add `<meta name="robots" content="noindex, nofollow">` to all card payment pages so search engines don’t index them.
This is the approach specified by:
https://www.gov.uk/service-manual/technology/get-a-domain-name#telling-search-engines-not-to-index-pages
This does not affect the GOV.UK product pages available on the same host.
=> PP-6869 Tell search engines not to index card payment pages

Gruntfile.js, app/assets/robots.txt
https://www.gov.uk/service-manual/technology/get-a-domain-name#telling-search-engines-not-to-index-pages says to use `<meta name="robots" content="noindex, nofollow">` to tell search engines not to index our pages. Additionally, it says not to use `robots.txt` to prevent crawling because this stops the `noindex` directive from being seen by search engines.
We added `<meta name="robots" content="noindex, nofollow">` in commit b1c97f1bb60461b06ee053eae4cc59310a2a4f67. This commit completes the work by removing the `robots.txt` file.
=> PP-6869 Remove robots.txt file

app/assets/javascripts/browsered/web-payments/google-pay.js
After the user has confirmed they want to make a payment using Google Pay, make it so that the JavaScript POST from the browser to frontend includes a `Accept-For-HTML` header whose value is the same as that of the `data-accept-header` attribute on the `body` element or `*/*` if it’s not there for some reason.
The `data-accept-header` attribute contains the HTTP `Accept` header that the browser sent when it loaded the enter card details page. This is likely to be different to the `Accept` header sent with the JavaScript-initiated POST.
This code isn’t currently very well tested but the change is simple enough and the Cypress tests ensure that adding the header doesn’t cause everything to blow up.
=> PP-7351 Accept-for-HTML header with Google Pay post to frontend

.secrets.baseline, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js, test/fixtures/wallet_payment_fixtures.js
When sending the request to connector to authorise a Google Pay payment, send the `Accept-For-HTML` header (which is the `Accept` header that was sent when the enter card details page was loaded), the `User-Agent` and the IP address because connector needs to send them to Worldpay for 3D Secure.
=> PP-7351 Google Pay: Accept, User-Agent, IP address go to connector

app/assets/javascripts/browsered/web-payments/helpers.js
Description:
- Some of the fields which are required for SCA compliance are already present in the PaymentRequest object.
- This PR adds the countryCode and assuranceDetailsRequired to the object. The documentation doesn't make it clear whether assuranceDetailsRequired is required for SCA compliance so I've included it in anyways. Since Worldpay haven't specified what fields to send in addition to the 3DS parameters we already send adding these fields into our current Google Pay integration shouldn't break anything as we aren't sending the newly added fields along
- See [here](https://developers.google.com/pay/api/android/guides/resources/sca) for the fields Google Pay want us to add
=> PP-7477 - Add JSON fields for Google Pay to be SCA compliance

server.js
- Add feature flag - NGINX_CACHING_ENABLED
- If flag = true then
- Add add cache headers to the Design System assets
- Want to see if adding this means we can cache assets from the Design system using NGINX.
- Will be testing this only on the Test env.
=> PP-7082 Frontend Design System asset caching

package-lock.json, package.json
This caused a frontend build failure.
Reverts alphagov/pay-frontend#1757
=> Revert "Bump envfile from 5.1.0 to 6.14.0"

package-lock.json, package.json
Pulls in the updates from https://github.com/alphagov/pay-product-page/pull/296
=> BAU: Bump product-page to 4.7.6

server.js
A no cache policy was set on card payments frontend in the past with
some work done on browser history back/forward behaviour.
The existing middleware stack sets this at the beginning which will apply
to both static routes (served through express middleware) and route
controllers responding to requests.
This commit moves the no cache reset below the definition for serving
static assets, this will apply the no cache header only to the actual
route controllers, continuing to respect the intended behaviour of
forcing browsers to request a new copy of route resources.
This allows upstream services (likely proxies) to set cache headers on
requests and cache commonly used assets.
Co-authored-by: Steven Fountain <steven.fountain@digital.cabinet-office.gov.uk>
=> PP-7082 Move no cache headers after static assets 

package-lock.json, package.json
Pulls in the changes from https://github.com/alphagov/pay-product-page/pull/297
=> BAU: Bump product page to v4.7.7

package-lock.json, package.json
Include the following product page content changes:
- update the public roadmap
- update 3DSecure page and guidance
=> BAU Bump product page to 4.7.8

app/controllers/charge_controller.js, test/cypress/integration/web-payments/apple-pay.spec.js
This is while we test the new merchant identity certificate works.
Exactement la même que https://github.com/alphagov/pay-frontend/pull/1988
=> PP-7618: Temporarily only enable Apple Pay for our live account

app/controllers/charge_controller.js, test/cypress/integration/web-payments/apple-pay.spec.js
Reverts alphagov/pay-frontend#1996
[Test payment in production](https://toolbox.payments.service.gov.uk/transactions/aord7u702kpa1bdmh9bucvuepc) was successful.
=> Revert "PP-7618: Temporarily only enable Apple Pay for our live account"

package-lock.json, package.json
This will pick up custom branding changes for MHRA and NIBSC reference
zen desk ticket https://govuk.zendesk.com/agent/tickets/4487202.
Note that release `3.1.0` was created in error about 10 days ago and was
subsequently corrected to `3.0.5` which I have confirmed with the
developer. It appears frontend wasn't updated with the corrected
version. This is not downgrading the version of `pay-js-commons`.
=> BAU Bump JS Commons

package-lock.json, package.json
- Bumps pay-js-commons to latest
=> Bump @govuk-pay/pay-js-commons from 3.0.9 to 3.0.10

test/cypress/plugins/index.js
We weren't returning a promise from the `setupStubs` task, causing test flakiness.
=> PP-7965 Fix Cypress test flakiness

app/controllers/charge.controller.js, app/middleware/state-enforcer.js, app/services/normalise-charge.js, app/services/worldpay-3ds-flex.service.js, app/utils/analytics.js, test/controllers/charge.controller.test.js, test/controllers/web-payments/handle-auth-response.controller.test.js, test/fixtures/payment.fixtures.js, test/integration/charge-status.ft.test.js, test/middleware/state-enforcer.test.js, test/services/worldpay-3ds-flex.service.test.js, test/utils/normalise.test.js
- We currently use gateway account payment_provider during payment journey where needed. Gateway account is going to support multiple payment providers (when PSP switching is supported), so use payment_provider available on charge
=> PP-8194 Use Charge paymentProvider instead of gateway account payment provider

app/views/charge.njk
- Update the Payment page with `Fieldset` tags as per Design system
guideline: https://design-system.service.gov.uk/components/fieldset/
- Update the `Billing Address` and `email` fields as follows:
- Wrap the fields in a `fieldset` tag.
- As DAC recommends, Add a `fieldset > aria-describedby` attribute which points to the `hint` text.
- Update the `legend` tag so that it only contains only the heading.
- Move the `hint` text so that it sits next to the `legend` tag.
See screenshot below:
=> PP-7864 Payment Pages - Add fieldset tags

app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js, app/assets/sass/modules/_summary-panel.scss, app/assets/sass/modules/_web-payments.scss, app/views/charge.njk, app/views/confirm.njk, test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.cy.test.js
- Update the `Charge` & `Confirm` page layouts based on findings from user research.
- Move the `Payment summary` to the middle and top of the page.
- Charge page:
- Move the `accepted card types` and card icons above the `card number` input. 
- Make sure the layout works correctly when Apple & Google pay is visible.
- Rename the classes
- `web-payment-button-button` -> `web-payment-button-section`
- `non-web-payment-button-button` -> `non-web-payment-button-section`
- Show the `payment-summary` in the correct sections depending if the `apple` or `google` pay buttons are visible.
=> Pp 7864 payment page update layout

app/assets/sass/modules/_web-payments.scss, app/views/charge.njk
- Google pay
- Make it use an inline image of the `Google pay` logo instead of a background image
- This is better for acessibility for users with High contrast needs.
- Fix the focus state
- The button becomes yellow when in focus state.  This would make the `Google Pay`
image difficult to see.
- Now the image inverts colours when in `focus` state using CSS.
- Hover state - make sure the image goes back to normal
- General styling cleanup
- Make the border radius consistent between the Apple and Google pay buttons
=> Pp 7864 payment page add transparent pixel for Google pay button

app/utils/charge-validation-fields.js, test/integration/charge-validation.ft.test.js, test/utils/charge-validation-fields/email-field.test.js
Consecutive numbers are rejected during email validation, this was
initially to prevent card numbers accidentally populating this field.
This has caused some confusion around what a valid email should be -- as
card numbers on their own fail RFC822/ domain checks remove this
explicit check.
=> PP-8279 Remove consecutive number check from email validation

package-lock.json, package.json
Bumps pay-js-commons to 3.2.3 to pick up custom branding changes (on an up-to-date branch this time!)
=> ZD-4632051: Bump pay-js-commons for custom branding

app/middleware/retrieve-charge.js, test/controllers/charge.controller.test.js, test/controllers/secure.controller.test.js, test/controllers/web-payments/handle-auth-response.controller.test.js, test/fixtures/payment.fixtures.js, test/integration/charge-status.ft.test.js, test/integration/confirm.ft.test.js, test/test-helpers/test-helpers.js, test/utils/normalise.test.js
- Remove `payment_provider` from gateway account payload in tests. Frontend is using payment_provider on charge everywhere.
- Also set payment_provider available on charge for logging when retrieving charge from connector
=> PP-8373 Remove payment_provider from gateway_account fixture

app/utils/email-validation.js
ZAP tests are failing, it appears due to PhantomJS not supporting String.prototype.includes.
This is also apparently not supported on IE 11.
=> PP-8256 Fix email validation for older browsers

README.md, app/routes.js
Make `/.well-known/security.txt` and `/security.txt` redirect to https://vdp.cabinetoffice.gov.uk/.well-known/security.txt.
Update `README.md` to reference the Cabinet Office CDIO Cyber Security vulnerability disclosure policy and security.txt file rather than the GOV.UK Pay security vulnerability email address.
=> PP-8095 Add security.txt file

package-lock.json, package.json
- update known vulnerabilities:
upgrade node-fetch to version 2.6.1
upgrade minimist to version 0.2.1, 1.2.3 or higher
upgrade glob-parent to version 5.1.2 or higher
=> PP-8427 address vulnerabilities

app/assets/javascripts/browsered/helpers.js
In the Chrome browser, if a service is configured to collect billing
address the tab order will "jump" back to the country selection when the
user blurs (moves on from) the final form input (currently users email).
This is because of a collision between the accessible autocomplete
library and Chrome's behaviour with the web standard `autocomplete=off`.
Instead of ignoring this input as described in
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocomple>
Chrome is using "off" as the autoselect key and providing the previous
values that have been entered for any input that sets this value. As the
browser autocomplete is also loaded, the input is not cleanly tabbed
away from which means it is the next in line to be selected once there
is nothing …
=> PP-8581 Fix tab selection jump to country autocomplete

.env.example, .gitignore, app/models/Service.class.js, app/services/countries.js, app/services/normalise-charge.js, app/views/charge.njk, test/cypress/integration/card/billing-address-collection.cy.test.js, test/fixtures/service.fixtures.js, test/utils/normalise.test.js
If a value is set for the `default_billing_address_country` on the
service, use this as the pre-filled value for the country select.
If no value is set, leave the field blank. This is achieved by adding an
option with the attributes `disabled selected value=""` to the select.
When the select control is converted into the country picker using
javascript from the `govuk-country-and-territory-autocomplete`
npm module, the field will be blank. When javascript is disabled, the
select has the disabled option "Pick a country or territory" selected
by default.
Ended up doing this in the template rather than in normalise-charge.js,
but removed an unused method from normalise-charge.js and improved the
unit tests to make it more understandable and robust.
=> PP-8445 Use default billing address country on service

app/data/countries-autocomplete-graph.json, app/data/countries.json, test/services/countries.test.js
Updates country list based on diff against CSV from https://data.gov.uk/dataset/0b412b57-6934-4f28-b495-640cdc7e8f7f/foreign-commonwealth-and-development-office-geographical-names-index (I wrote a [little python script](https://gist.github.com/gidsg/84e15fb65fe9eea159324369b33f2870) to compare the CSV against our current JSON.)
**Question** should we add the old names as synonyms for the new ones in the autocomplete graph?
Updated country names should appear in country picker on payment page e.g. North Macedonia.
=> PP-7216 update country list

package-lock.json, package.json
Following the [upgrade to nunjucks
3.2.3](https://github.com/alphagov/pay-frontend/pull/2435), the jenkins build
broke at the Browser Tests step with
```
UnhandledPromiseRejectionWarning: Error: watch requires chokidar to be installed
```
=> bau: Install chokidar

package-lock.json, package.json
- Made sure I used the version of Node as specified in Package.json - 12.22.7
- This means the package-lock.json had to be updated for some minor dependencies
that are specific for this version of Node.
=> PP-9099 Bump product pages to 4.9.16

package-lock.json
- minimist must be on version 1.2.5 or above due to vulnerability
=> PP-9099 revert minimist to a safe version

package-lock.json, package.json
https://www.payments.service.gov.uk/payment-service-provider/
Remove outdated text about PSP reprocurement, which mentions June 2021 as if it’s in the future.
=> ZD-4848316 Update Pay product page to version 4.9.19

.github/workflows/run-tests.yml
In our workflow for running tests on PRs, we cache Cypress so that it doesn't need to be downloaded and installed for each test run, as this takes a number of minutes. This cache is persisted between action runs.
We were caching with the key `Linux-cypress` not taking into account versioning. This means that if we tried to update our Cypress version, we would probably end up with multiple Cypress versions in the same cache due to restoring the existing version from the cache and then installing the new version when we run `npm install`.
To ensure that we only cache and restore the required version, retrieve the Cypress version number from the package.json file and append this to the cache key.
=> PP-9148 Cache Cypress with version in key

test/cypress/plugins/index.js
Before each Cypress test runs, we make a request to Mountebank to DELETE
the existing imposter, so a new imposter can be set up for the test.
On Jenkins we are seeing calls to DELETE the imposter happening after
POST requests to setup a new imposter for the test on occasion. When
this happens, the POST request fails as there is an existing imposter.
If looks like the task to clear the stubs isn't returning a promise, as
we are calling the `delete` method on the `request` library directly
without wrapping it in a promise. If we use the default method of
`request`, as we do for POSTing the imposter, this function is wrapped
in a promise using `util.promisify(request)`.
=> PP-9148 Fix "promisifying" request for Cypress setup

Dockerfile
- glibc no longer needed for Docker
=> PP-9187 remove appmetrics

.mocharc.js, test/mocha.opts
Fixes the the issues of PACT tests failing when run locally by setting a longer timeout in Mocha configuration
and switches to new Mocha configuration format which fixes the deprecation warning:
```
DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
```
All tests should pass when run locally e.g. `npm test -- --forbid-only --forbid-pending`
Above deprecation warning should not appear
=> PP-9153: Switch to new Mocha configuration format and set explicit longer timeout

app/services/normalise-charge.js, test/services/normalise-charge.test.js
Add `accept-language` header to payload, as this will be used by Connector as part of 3DS flow.
Couldn't find a good place to add a test for this, if you can think of one let me know!
=> PP-9314: add accept-language header to payload

package-lock.json, package.json
Switch to snyk hosted package
Fixes Deprecation warning
```
⚠ WARNING: Starting from 31 March 2022, the protect command will be removed.
Please use the @snyk/protect package instead.
For more info: https://snyk.co/ueln7
```
build should still pass
=> PP-9375: switch to snyk hosted package

.github/workflows/run-tests.yml
Make use of the `outputs` and `needs` links between jobs to share the
Node version parsed from the nvmrc file.
=> BAU Replace version parsing with shared output

package-lock.json, package.json
Override `minimist` to `1.2.5` to prevent security warnings
=> PP-9148 override minimist to 1.2.5

app/views/charge.njk, test/cypress/integration/card/payment.cy.test.js, test/cypress/utils/card-payment-stubs.js, test/fixtures/payment.fixtures.js
Include agreements in charge response stub builder.
Assert that normal payment flows will not include the agreements setup
snippet.
Assert that payment flows with the appropriately flagged save payment
instrument to agreement properties will correctly show the agreements
human readable identifier.
=> PP-9333 Cypress coverage for setup agreements disclaimer

app/assets/javascripts/browsered/helpers.js
- For the `Country` select-  autocomplete attribute
- Replace it from a random number to `country-disabled-autocomplete`
- This is so that it is more descriptive.
- This is a workaround for the Chrome bug which does not respect
`autocomplete=off`
=> PP-9289 Country select - update autocomplete attribute

.stylelintrc.json, app/services/normalise-charge.js, package-lock.json, package.json, test/services/countries.test.js, test/utils/normalise.test.js
Use the GDS Stylelint NPM module.
- Add Stylelint dependencies.
- Add Stylelint config - to extend GDS Stylelint config.
- Stylelint issues will be fixed in a seperate ticket that will be prioritised in the future.
- Want to remove `sass-lint` so that we can remove the `minmist` override.
Remove the `minmist` override
Add `eslint-plugin-import` module
- Had to add this NPM module due to an issue with Standard > Eslint and NPM 8.
=> PP-9357 Remove 'sass-lint' and add 'stylelint'

app/middleware/state-enforcer.js
If the payment provider is Stripe, it seems we want to allow any page to load if the charge status is AUTHORISATION 3DS READY.
The code to do this was permanently pushing the AUTHORISATION 3DS READY state to the shared array of allowed states in `state.service.js`, so the array was growing increasingly larger. This resulted in strange behaviour such as including an array with `AUTHORISATION 3DS READY` repeated hundreds of times in the "State enforcer status doesn't match" log line.
This could have also resulted in allowing the AUTHORISATION 3DS READY state on any page for charges that are not Stripe, even though this was not the intention of the code. It's unclear whether this would have had any negative consequences.
Fix this to make a copy of the array, rather than adding to the shared …
=> BAU Fix state enforcer logging

app/views/charge.njk
Follow components already set on the payment page to make this
disclaimer fit in with the flow of the page.
Add a container border to separate it from entering the above details.
=> PP-9846 Update agreement disclaimer style to match page

app/assets/javascripts/browsered/form-validation.js, app/views/charge.njk, test/cypress/integration/card/moto-mask-payment.cy.test.js, test/cypress/integration/card/payment.cy.test.js
Before error messages: 
Error messages - were overwriting labels which is wrong:
Updated code:
- No longer overwrites labels.
- Error message is a separate element that is no longer embedded in the label element.
- When JS is disabled, make the error messages are not part of the label, make them their own element.
Credit card hint text is too small - make this bigger:
- Update Javascript to add error elements rather than overwrite labels.
- When the error is relaced with a new error - create the element again from scratch so that screen readers are alerted.
- Add the error message outside of the label instead of adding it inside the label.
- This is more semantically correct.
- Also consistent with Design system.
- Make sure the code works with IE11
- Use `removeChild` instead of …
=> PP-10059 DVLA Accessibility - stop overwriting labels with error messages

package-lock.json, package.json
- Bumps product pages to the latest version which includes updates to the roadmap https://github.com/alphagov/pay-product-page/commit/d2fa90f11a697dcb731a12751bcdd0a930de2187
=> PP-10074 Update roadmap

app/assets/javascripts/browsered/form-validation.js, app/assets/javascripts/browsered/helpers.js, app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/worldpay-3ds-flex-ddc.js
Make it so that when we are processing a Google Pay or Apple Pay payment we hide the majority of the page while showing the spinner (currently none of the page is hidden). In addition, disable all the submit buttons when the spinner is shown (currently only the Google Pay or Apple Pay submit button is disabled).
This brings the appearance of the spinner into line with when we do Worldpay 3DS Flex device data collection. Also make it so that when the spinner is shown for DDC we disable all the submit buttons (currently only the card details submit button is disabled).
=> PP-10077 Make Google Pay and Apple Pay spinner cover whole page

app/assets/javascripts/browsered/web-payments/google-pay.js
If the Google Pay Ajax call results in an unexpected HTTP status code, hide the spinner and display the main content (which is the same thing we’d do for other errors).
with @SandorArpa and @kbottla
=> PP-10077 Recover from unexpected Google Pay Ajax response

app/views/charge.njk
If both Google Pay and Worldpay 3DS Flex are enabled, add an additional device data collection iframe to the enter card details page. This iframe is identical to the other one except that it has a different ID and will be used exclusively for device data collection for Google Pay payments.
=> PP-10077 Add Google Pay Worldpay 3DS Flex DDC iframe

.secrets.baseline, app/controllers/charge.controller.js, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, app/controllers/web-payments/payment-auth-request.controller.js, app/utils/logging.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js, test/fixtures/wallet-payment.fixtures.js
When processing a request to `/web-payments-auth-request/google/CHARGE_ID` (sent as an Ajax request from the browser), process the Worldpay 3DS Flex device data collection result and status.
Send the DDC result to `/v1/frontend/charges/CHARGE_ID/wallets/google on connector` as `worldpay_3ds_flex_ddc_result` inside the existing `payment_info` object.
Log the DDC status in the same way we do for a regular card payment for which we performed device data collection.
=> PP-10077 Google Pay: send Worldpay 3DS Flex DDC result to connector

app/utils/response-router.js, test/utils/response-router.test.js
The previous humans.txt message (see https://github.com/alphagov/pay-frontend/pull/3110/files) only mentioned the London office. Also, we're called GOV.UK Pay, not GOV.UK Payments.
=> PP-10204: Revert David's goodbye message, add Bristol/Manchester

app/assets/javascripts/browsered/web-payments/google-pay.js, test/cypress/integration/web-payments/google-pay.cy.test.js
- We are currently modifying the `PaymentResponse` object returned by GooglePay for the Worldpay DDC result. Stop modifying the response object directly (which looks like it is immutable based on testing) and assign it to a new variable to append DDC result/status.
=> PP-10077 Google Pay: Do not modify PaymentResponse

.secrets.baseline, app/assets/javascripts/browsered/web-payments/google-pay.js, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js
When we make the Ajax request to `/web-payments-auth-request/google/CHARGE_ID`, we currently convert the `PaymentResponse` object received from Google Pay to JSON and then add the two new `worldpay3dsFlexDdcResult` and `worldpay3dsFlexDdcStatus` properties to it and then send that as the payload.
Instead, send a JSON payload containing a top-level `paymentResponse` property containing the unmodified `PaymentResponse` object from Google Pay alongside the `worldpay3dsFlexDdcResult` and `worldpay3dsFlexDdcStatus` properties, also at the top-level:
```json
{
"paymentResponse": … the PaymentResponse object from Google Pay …,
"worldpay3dsFlexDdcResult": "the DDC result string",
"worldpay3dsFlexDdcStatus": "the DDC status string"
}
```
This means we are not modifying the `PaymentResponse` object …
=> PP-10077 Nest Google Pay PaymentResponse object in Ajax request

app/controllers/web-payments/google-pay/normalise-google-pay-payload.js
Change how we log selected properties from the Google Pay payload so that it once again more closely mirrors the actual payload we now receive.
=> PP-10077 Tweak selected payload properties logging for Google Pay

.secrets.baseline, test/cypress/integration/web-payments/google-pay.cy.test.js
Update Google Pay Cypress tests to reflect the fact that we now do device data collection when Worldpay 3DS Flex is enabled (which is the standard configuration now).
=> PP-10077 Update Google Pay Cypress tests for device data collection

package-lock.json, package.json
- Bump product page to latest https://github.com/alphagov/pay-product-page/pull/524
=> PP-9648 Bump product page to 4.12.0

package-lock.json, package.json
- Updated product pages to 4.12.3 https://github.com/alphagov/pay-product-page/commit/eb1e69d129ebd7f0227abe4290fcbbc23b0c2b10 (performance stats)
=> BAU: Bump product pages from 4.12.2 to 4.12.3

app/controllers/charge.controller.js, app/controllers/three-d-secure.controller.js, app/controllers/web-payments/handle-auth-response.controller.js, test/controllers/web-payments/handle-auth-response.controller.test.js, test/integration/charge.ft.test.js, test/integration/three-d-secure.ft.test.js
- Handles 402 status code from connector for payments.
- At the moment connector returns a 500 status code for gateway errors for which frontend logs the error "Error communicating with connector.." which is not accurate.
- So, connector is going to return 402 instead for gateway errors. Frontend will continue to show an error page to users.
- https://github.com/alphagov/pay-connector/pull/4145
=> PP-8693 Handle 402 payment response from connector

.secrets.baseline, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js
- We currently log info about GooglePay payload only if all info we use is available.
So updated to log if any field we use is available in the payload.
- Also simplifies handling properties
=> PP-10278 GooglePay payments: Log properties all the time

app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, test/controllers/web-payments/google-pay/normalise-google-pay-payload.test.js
- For some Google Pay payments, `paymentMethodData.info` is not available in the payload and so is the card brand.
- It is causing unchecked exceptions with the error `TypeError: Cannot read properties of undefined (reading 'info')`.
- Throw error if card_brand is not available in the payload as it is mandatory.
=> PP-10278 Throw error if card brand is not available in Google Pay payload

package-lock.json, package.json
Bump pay-js-commons by changing the version in the package.json, then running `npm upgrade pay-js-commons`
=> ZD-5142738: Bump pay-js-commons with npm upgrade pay-js-commons

package-lock.json, package.json
Pulls in additional custom branding updates.
=> ZD-5142783: Bump pay-js-commons to 3.8.5

package-lock.json, package.json
- This will enable the latest content for the `product pages > privacy page`.
=> PP-10242 Product page > Privacy Page - bump product page npm module

package-lock.json, package.json
- bump product-pages `4.12.20` -> `4.12.21`
Archive extension has changed to `.tar`, this is an intentional change.
=> BAU bump product pages 4.12.20 -> 4.12.21

app/middleware/csp.js
- google recently updated guidance for payment handler api usage, we now need to ensure the domains of HTTP requests sent from the browser are added to the connect-src directive
- see this blog post for more information: https://developer.chrome.com/blog/payment-handler-csp-connect-src
=> PP-10839 Update `frontend` csp re google pay changes

app/middleware/csp.js
When a domain included in the content security policy results in a cross-origin redirect, the redirected resource also needs to be included in the policy to allow the connection.
We've seen Google Pay payments work since updating the CSP to allow `google.com/pay` however we're continuing to see CSP violations. If we're continuing to block connects we may see Google Pay payment continue to silently fail, include the redirect address to allow connection to both.
Relates to https://github.com/alphagov/pay-frontend/pull/3368
=> PP-10839 Include Google Pay cross origin redirect in CSP

.github/dependabot.yml
We are now firmly on node16 so the old 'ignore' config for node14/15 is no longer needed. This old config also might be the reason Dependabot is not providing updates for Node base images - the `pay-stream-s3-sqs` repo has the same Dockerfile setup but no Dependabot restrictions, and the updates are appearing as expected (see https://github.com/alphagov/pay-stream-s3-sqs/pull/579 for example).
We may need to put in a new ignore to stop Dependabot trying to bump us to node18, but that doesn't seem to have happened on `pay-stream-s3-sqs` yet.
=> BAU: Remove Docker dependabot version restrictions

app/assets/iframe/worldpay-3ds-flex-ddc.html, app/views/auth-3ds-required-in.njk, app/views/auth-3ds-required-out.njk, app/views/charge.njk, app/views/confirm.njk
Add a `novalidate` attribute to all `form` elements to disable built-in HTML5 browser client-side validation.
The Design System says to do this at https://design-system.service.gov.uk/patterns/validation/:
> HTML5 validation is a type of client side validation built into browsers. Do not use it because:
> 
> • the visual style, placement and content of HTML5 error messages cannot be made consistent with the GOV.UK Design System
> • we know that the GOV.UK Design System error message and error summary components are accessible
> 
> To turn off HTML5 validation, add ‘novalidate’ to your form tags.
Strictly speaking, this only needs to be done for forms that contain validatable fields (and all the ones in frontend seem to have this attribute already) but it’s easiest just to add it to all …
=> PP-10887 Add novalidate to all forms

package-lock.json, package.json
- Remove `eslint` & `eslint-plugin-import` NPM modules.
- We do not use Eslint directly - we use Standard to carry out our JS linting.
=> PP-10947 Remove unused `eslint` NPM modules

app/services/example-card-expiry-date.js, package-lock.json, package.json, test/services/example-card-expiry-date.test.js
- We were using `moment-timezone` NPM module to give us the example expiry year hint
- Which is the current year + 2
- Remove the module and just use core JS functions instead.
=> PP-10947 Remove the `moment-timezone` module - use core JS functions instead

server.js
- When removing the `body-parser` NPM module, switched to using the Express functions instead.
- However, we need to update how we call `express.urlencoded`.  As we were getting deprecation warnings.
- Function call has been updated to explicitely set the `extended: true` option.
- This removes the deprecation warnings.
- More information about this here: https://stackoverflow.com/questions/25471856/express-throws-error-as-body-parser-deprecated-undefined-extended
=> PP-10947 Update deprecated `express.urlencoded`

app/middleware/csp.js
We're seeing CSP rule violations for Google Pay, starting on Friday 26th May and ramping up Tuesday 30th May. Investigating this it looks like Google is now trying to connect to the `www.` subdomain rather than the previously used `google.com`. This observation doesn't come from an official source so we should see reason about if it resolves the issue before locking in the change.
Relates to https://github.com/alphagov/pay-frontend/pull/3370
=> PP-11082 Update google pay CSP to include www subdomain

package-lock.json, package.json, test/cypress/plugins/index.js
- Replaced request library usage in tests with Axios. This is to eventually remove the request library dependency which is not maintained anymore
=> PP-10875 Remove request library usage from tests

app/assets/javascripts/browsered/form-validation.js, app/views/charge.njk, test/cypress/integration/card/card-details-page-validation.cy.test.js
- Update the expiry date inline validation as follows:
- Whenever there is an inline error with the expiry date, when the user goes to another field, then it will show a red outline on both the month and year fields.
- Currently it was only doing it on the year field.
- Add a Cypress test to test this.
=> PP-10966 Fix bugs with inline expiry date validation

test/cypress/integration/card/email-collection.cy.test.js
=> PP-10904 Make email collection Cypress tests standalone

test/cypress/integration/card/footer.cy.test.js
=> PP-10904 Make footer Cypress tests standalone

test/cypress/integration/card/payment-cancellation.cy.test.js
=> PP-10904 Make email payment cancel Cypress tests standalone

test/cypress/integration/epdq-3ds2/payment-with-epdq-3ds2.cy.test.js
=> PP-10904 Make ePDQ Cypress tests standalone

test/cypress/integration/web-payments/apple-pay.cy.test.js
=> PP-10904 Make Apple pay Cypress tests standalone

app/controllers/secure.controller.js, test/controllers/secure.controller.test.js, test/cypress/integration/card/awaiting-auth.cy.test.js, test/cypress/integration/card/billing-address-collection.cy.test.js, test/cypress/integration/card/email-typo.cy.test.js, test/cypress/integration/card/payment.cy.test.js, test/fixtures/payment.fixtures.js, test/unit/charge.controller.test.js, test/unit/clients/connector-client-token.pact.test.js
Want to change the response schema for the connector GET `/v1/frontend/tokens/{chargeTokenId}` endpoint to use the FrontendChargeResponse schema for the embedded charge object in the response, rather than ChargeEntity.
Support both versions of the response temporarily by checking which fields are returned in the response. This will be updated again to remove support for the old response schema after the connector change is made.
This will allow https://github.com/alphagov/pay-connector/pull/4602 to be merged.
=> PP-11244 Prepare for changing find charge by token response

app/controllers/secure.controller.js, test/controllers/secure.controller.test.js, test/cypress/integration/web-payments/apple-pay.cy.test.js, test/cypress/integration/web-payments/google-pay.cy.test.js, test/cypress/utils/card-payment-stubs.js, test/cypress/utils/stub-builders/token-stubs.js, test/fixtures/payment.fixtures.js, test/unit/clients/connector-client-token.pact.test.js
Connector has now been updated so that the GET token response uses the FrontendChargeResponse schema for the embedded charge rather than ChargeEntity.
Remove the handling for the old response.
Update `secure.controller.test.js` for this change, and refactor it slightly to make it easier to understand.
Update the Pact test for the GET token endpoint to validate the embedded charge in the response using the new schema.
=> PP-11244 Remove handling for old GET token response

test/fixtures/payment.fixtures.js
Remove `allow_moto`, `live` and `version` properties from the gateway account object in expected responses in Pact tests.
These properties are not consumed by frontend. This is to allow connector to be updated to use a different model for serialising frontend gateway account responses
=> PP-11244 Remove properties not consumed from pacts

test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.cy.test.js
=> PP-10904 Make Worldpay Cypress tests standalone

test/cypress/integration/card/payment.test.cy.js
- In previous PR https://github.com/alphagov/pay-frontend/pull/3533, the payment Cypress test was updated so that it was not dependent on the `preserveOnce` method.
- However, forgot to remove the actual `preserveOnce` method.
- This PR removes this method - which is required before upgrading to Cypress 12.
=> PP-10904 Make payment Cypress test standalone.

test/cypress/integration/card/awaiting-auth.test.cy.js, test/cypress/integration/card/billing-address-collection.test.cy.js, test/cypress/integration/card/email-collection.test.cy.js, test/cypress/integration/card/email-typo.test.cy.js, test/cypress/integration/card/enforce-views-to-state.test.cy.js, test/cypress/integration/card/moto-mask-payment.test.cy.js, test/cypress/integration/card/payment.test.cy.js, test/cypress/integration/card/token-reuse.test.cy.js, test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.test.cy.js
- `cy.server` and `cy.route` are removed in Cypress 12.
- Replace with `cy.intercept` in preparation for the Cypress 12 upgrade.
=> PP-10904 Cypress 12 upgrade prep - replace `cy.server`, `cy.route` with `cy.intercept`

app/views/charge.njk, test/cypress/integration/web-payments/apple-pay.test.cy.js, test/cypress/integration/web-payments/google-pay.test.cy.js
We currently only offer wallet payments for one-off payments. Although it is possible to use recurring payments (payments taken when setting up agreements), it needs additional backend integration which is not in place for both Stripe/Worldpay.
So we should hide wallet options even if allow_apple_pay / allow_google_pay is true for the gateway account
- do not render wallet payments if the payment is a recurring one (savePaymentInstrumentToAgreement is present)
- add Cypress tests
=> PP-11323 hide wallet options for recurring payments

app/controllers/web-payments/apple-pay/normalise-apple-pay-payload.js, test/controllers/web-payments/apple-pay/normalise-apple-pay-payload.test.js
- Currently, we send Apple Pay token.paymentData as JSON to the connector in the field `encrypted_payment_data`. For Stripe payments, we will need to send `paymentData` as is to Stripe. To avoid any issues, when deserialising encrypted_payment_data and then serialising data, we can send paymentData as a String and let connector deserialise payload if required.
- Added a new field payment_data to send token.paymentData as String. Connector doesn't handle the new field yet
=> PP-11365 Send additional `payment_data` to connector for Apple Pay payments

app/controllers/web-payments/payment-auth-request.controller.js, app/services/clients/connector.client.js, test/controllers/web-payments/payment-auth-request.controller.test.js, test/unit/clients/connector-client-google-authentication.pact.test.js
PP-11393 adds a separate endpoint for authorising Stripe goole pay payments. Rename the existing endpoint to make it clear it is for Worldpay.
- rename calling google pay authorisation URL
- update tests
=> PP-11394 rename google pay endpoint

.vscode/launch.json, app/assets/javascripts/browsered/helpers.js, app/views/charge.njk, package.json, test/cypress/integration/worldpay-3ds-flex-ddc/payment-with-session-id.test.cy.js
In some circumstances, when a user encountered an error during the Google Pay wallet journey they were returned to the card details page and could see Apple Pay as a payment option.
This is because a client-side script modifies the DOM to show/hide wallet options. By wrapping all options in a parent div and applying conditional styling higher up the document tree, we no longer accidentally toggle the visibility of Apple Pay-specific DOM elements.
Additionally, `npm run start:dev` now runs `nodemon` with the `--inspect` flag enabled by default. There's a new launch configuration (vscode only) that can be used to attach to the debugger.
=> PP-11462 fix erroneous apple pay option

app/views/charge.njk
The continue button was not correctly spaced if a service was configured to collect billing addresses but not email addresses. Conditionally apply margin overrides based on `shouldShowEmail`.
Before:
After:
After (all fields enabled):
=> PP-11115 fix frontend layout bug

app/assets/javascripts/browsered/web-payments/google-pay.js, package.json, test/unit/browsered/web-payments/google-pay.test.js
- When the payment reference is long and the Google pay dialog appears, then it does not show the `add` button.  Which the user needs to add contact information.
- This is a bug with Google chrome - it does not wrap the payment description text. So its pushes the button too wide so it is not visible.
- This PR truncates the payment description if it is too long when setting up the Google payment.
=> PP-11463 Fix Google pay description dialog bug

app/controllers/web-payments/handle-auth-response.controller.js, test/controllers/web-payments/handle-auth-response.controller.test.js
We would expect to see an error page when payment was declined after clicking “Pay” in the Google Pay dialog, instead we see a technical problems page.
- refactor auth response controller to handle 400 return code
- add a relevant test
=> PP-11470 show auth rejected page

.secrets.baseline, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/helpers.js, app/controllers/charge.controller.js, app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, app/controllers/web-payments/payment-auth-request.controller.js, app/services/clients/connector.client.js, app/views/includes/scripts.njk, package-lock.json, test/fixtures/wallet-payment.fixtures.js, test/unit/browsered/web-payments/google-pay.test.js, test/unit/clients/connector-client-stripe-google-authentication.pact.test.js, test/unit/clients/connector-client-worldpay-google-authentication.pact.test.js
Implements Google Pay for Stripe accounts:
- `payment_provider` and `stripePublishableKey` are now available in the dom window, we use them in client-side scripts to:
- prevent device data collection from taking place for Stripe Google payments.
- enable a Stripe-specific `tokenizationSpecification` structure when interfacing with Google
- the charge controller determines which Stripe publishable key to use based on the gateway account type
- Stripe-specific `connector` request bodies are handled by `normalise-google-pay-payload.js`
- the `connector` client now understands which provider endpoint to call based on the wallet type of the charge
- new pact testing Stripe-specific Google wallet authorisations
=> PP-11395 frontend stripe google pay impl

app/assets/javascripts/browsered/web-payments/helpers.js, app/views/charge.njk, test/cypress/integration/web-payments/google-pay.test.cy.js
Context: Bug - if a Google Pay payment fails multiple times, the same error message is shown multiple times
- Clear existing error messages before displaying the new error message
=> PP-11582 Fix Google Pay repeated error message bug

app/controllers/web-payments/handle-auth-response.controller.js, test/controllers/web-payments/handle-auth-response.controller.test.js
- During a wallet payment - when calling connector, improve the error handling and logging
- Add a catch all to pick up any unknown status codes returned from connector.
=> PP-11496 Wallet payments - update error handling and logging of the `handle auth response` controller

test/controllers/web-payments/handle-auth-response.controller.test.js
- Update the test that was added previously to use sinon.asserts.calledWith instead of expect.  As it gives better error messages with what is expected vs. actual.
=> PP-11496 Update `handle-auth-response` controller tests

app/controllers/web-payments/payment-auth-request.controller.js, test/controllers/web-payments/payment-auth-request.controller.test.js
- When a wallet payment is made, it gets sent to the `payment auth request` controller.
- This controller will normalise the payload before submitting a request to connector to authorise the payment.
- This PR adds exception handling code for any exceptions that occur while normalising the payload.
=> PP-11496 Wallet payments - add exception handling to `payment auth request` controller

test/unit/clients/connector-client-apple-authentication.pact.test.js
- a pending connector release includes pact states for the new sandbox wallet payment behaviour, existing apple pay pact tests need to be disabled during the switchover
=> PP-11595 temporarily disable apple pay pact tests

app/views/layout.njk
Pay privacy and accessibility statements are no longer hosted on `frontend`, update links to the new location
=> PP-11674 fix broken links

app/assets/sass/modules/_web-payments.scss, app/controllers/web-payments/apple-pay/merchant-validation.controller.js, app/utils/wallet-utils.js, test/controllers/web-payments/apple-pay/merchant-validation.controller.test.js, test/unit/clients/connector-client-apple-authentication.pact.test.js
- fix apple pay button styling
- enable sandbox apple pay payments via worldplay
- switch on pact tests for sandbox wallet payments, see https://github.com/alphagov/pay-connector/pull/4754
=> PP-11577 implement apple pay for sandbox accounts

app/controllers/web-payments/payment-auth-request.controller.js, app/services/clients/connector.client.js, test/controllers/web-payments/payment-auth-request.controller.test.js, test/unit/clients/connector-client-stripe-google-authentication.pact.test.js, test/unit/clients/connector-client-worldpay-google-authentication.pact.test.js
Context: connector's google/worlpay and google/stripe endpoints are being merged into a single endpoint for Google Pay authorisations
- point frontend wallet authorisation requests to the new wallets/google endpoint
- point consumer tests to new connector provider states that include stubbing for Worldpay and Stripe
- remove the decline and error consumer tests, to be reintroduced when sandbox authorisations are enabled.
=> PP-11641 Point to generic Google Pay endpoint

app/controllers/web-payments/google-pay/normalise-google-pay-payload.js, app/services/normalise-charge.js, app/utils/key-camelizer.js, package-lock.json, package.json, test/utils/key-camelizer.test.js
- Removed the `humps` npm module by running `npm uninstall humps` which was being used to either change card detail JSON keys from snake-case to camel-case, or vice versa.
- Added a custom utility which provides the same functionality, albeit without the extra methods in `humps` which we weren't using. This utility changes the keys (including nested keys) using either the `camelize` or `decamelize` methods.
- Added a key-camelizer test.
- Should not encounter any errors when paying using a valid card.
=> PP-11032 Remove Humps module

app/assets/javascripts/browsered/helpers.js, app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/index.js, app/controllers/client-side-logging.controller.js, app/controllers/web-payments/apple-pay/merchant-validation.controller.js, app/paths.js, app/routes.js, package-lock.json, test/controllers/client-side-logging.controller.test.js, test/integration/client-side-logging.ft.test.js
Add a `/log/:chargeId` POST route. This can be called by the client-side JavaScript to do logging.
This accepts a POST request with a body containing a `code`, which maps to a message to be logged. We want to do this rather than accepting any string to be logged to avoid log injection.
This endpoint always returns a 200, even if we do not log due to the `code` being invalid or missing. This is because we do not want to interrupt client-side JavaScript running if this fails.
In the client-side JavaScript call this endpoint to log steps in the wallet payment journeys, such as when the button is clicked to start an Apple Pay or Google Pay payment, and also to log when certain errors are caught. When we call the loggng endpoint, we do not handle the Promise resolving/rejecting as we don't …
=> PP-11638 Add endpoint for client-side logging

app/utils/sentry.js
Prevent Sentry sending error reports for common `connect-src` csp violations.
[ignoreErrors](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-platformidentifier-nameignore-errors-) takes an array of strings which are used to detect partial matches in the error message, the following URLs appear only in the csp errors we want to block:
- 'www.facebook.com'
- 'spay.samsung.com'
Example events (requires Sentry login):
- https://govuk-pay.sentry.io/issues/4013720616/?environment=production-2&project=5494573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=5
- https://govuk-pay.sentry.io/issues/4013720595/?environment=production-2&project=5494573&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=0
=> PP-11714 exclude common `connect-src` csp violations

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/controllers/client-side-logging.controller.js
We log when a Google Pay session is aborted, for completeness also log when an Apple Pay session is aborted.
=> PP-11638 Add logging when Apple Pay session is aborted

app/assets/javascripts/browsered/web-payments/index.js, app/views/charge.njk
We were logging that Google Pay is available fewer times than Google Pay was being selected - which obviously shouldn't be possible.
We think this was happening because we were doing the logging in a DOMContentLoaded event listener, based on the presence of the 'google-pay-available' class on the document body.
The 'google-pay-available' class is added in a callback when the Promise to check whether Google Pay payments are available has resolved. It must be possible for this promise to resolve after the code in the DOMContentLoaded event listener that checks for the presence of the class has executed.
To avoid this, add another DOMContentLoaded event listener to the inline script in `charge.njk`, after the Promise to check whether Google Pay is available has resolved, which will log that …
=> PP-11638 Move client-side logging for wallet available

.secrets.baseline, test/fixtures/wallet-payment.fixtures.js, test/unit/clients/connector-client-apple-authentication.pact.test.js
As part of the review, a Pact test update was requested as per AC.
We recently looked at this in PP-11470: We show a technical problems page when Google Pay payments are declined.
However, we are expecting a 400 to always mean the authorisation was rejected - however, it could also mean that the request to connector has an invalid payload which we should handle by showing an error page.
The original change involves the pay-connector service returning an “error_identifier":"AUTHORISATION_REJECTED" in the error response for declined payments for the authorise wallet payment endpoints so we can be sure the 400 means the payment has been declined.
This change involved updating the Pact test to cover this error handling implementation
Review and run Pact test …
=> PP-11601 Improve how we handle rejected authorisation for wallets.

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/controllers/client-side-logging.controller.js
Add additional client-side logging in places where we were previously sending events to Google Analytics.
For most of these, we could probably get the same information from the server-side logs. However, logging the outcome of authorisation requests in the client-side logging will make it easier to quickly track the outcome of wallet payments and build dashboards to represent the user journey.
=> PP-11638 Add additional client-side logging

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/controllers/client-side-logging.controller.js
Reverts alphagov/pay-frontend#3759
The logging isn't quite accurate - a 200 received from the server side doesn't mean the payment was successfully authorised.
=> Revert "PP-11638 Add additional client-side logging"

app/assets/javascripts/browsered/web-payments/apple-pay.js, app/assets/javascripts/browsered/web-payments/google-pay.js, app/assets/javascripts/browsered/web-payments/index.js, app/controllers/client-side-logging.controller.js, app/controllers/web-payments/handle-auth-response.controller.js, app/middleware/retrieve-charge.js, app/views/includes/scripts.njk
Log the "wallet" on log lines if it is available on the charge. This will only be present post-authorisation.
Log a line when we are handling the authorisation response from connector. This is so we can easily validate that the redirect occurs in the client-side JavaScript after the authorisation is completed.
Stop trying to send a log to the server from the client-side  JavaScript when the authorisation has been processed. There is no guarantee this will complete before the page redirects meaning we were dropping some log lines. We could move the redirect to a `then` clause to execute after the promise to send the log message has resolved, but this would slow down the page redirect, which is undesirable.
Tidy up some of the client-side JavaScript slightly. The `init` function in …
=> PP-11638 Improve logging for handling wallet auth response

test/cypress/integration/web-payments/google-pay.test.cy.js, test/cypress/utils/stub-builders/charge-stubs.js
- The Google Pay Cypress test was not testing the Node endpoint
to authorise and capture a charge for wallet payments.
- Instead, the Cypress test was using `cy.intercept` to stub the call to the
Node endpoint.
- So the test was only covering the client side code.
- This PR removes the `cy.intercept` to the Node endpoint.
- The test will now pass through all calls to the Node endpoint.
- `cy.intercept` is still used for tests that required simulated network errors
- We had to change how error are generated with `cy.intercept`.
- Instead of using `forceNetworkError` - we changed it to specifically send back
a 500 status code.  This works better in the tests.
- Had an issue with the test that checks when the fetch call fails, and the user
tries again with the fetch call …
=>  PP-11468 Update Google Pay Cypress tests

.secrets.baseline, app/middleware/csp.js, app/paths.js, app/routes.js, app/utils/has-substr.js, app/utils/sentry.js, package-lock.json, package.json, server.js, test/middleware/csp.test.js, test/utils/has-substr.test.js
- added a new endpoint to handle csp violation reports
- updated the `cardDetailsCSP` and `worldpayIframeCSP` helmet configurations to send reports to new endpoint
- added new paramterised middleware functions to handle csp reporting and domain exclusions
- hardening measures:
- payload size limit
- rate limiting
- payload shape validation
- tests and helper functions
=> PP-11714 CSP reporting endpoint

app/assets/javascripts/browsered/web-payments/format-card-types.js, app/controllers/web-payments/payment-auth-request.controller.js, app/middleware/retrieve-charge.js, app/paths.js, app/routes.js, test/controllers/web-payments/payment-auth-request.controller.test.js
Relying on getting the wallet_type from the charge when handling the authorisation result isn't reliable - as connector can return a response before it has completed authorisation, in which case the wallet_type is not present.
So stop logging the `wallet` from the `wallet_type` on the charge from connector, as we can't rely on it consistently being there.
Instead, add the wallet type as a path parameter for the /handle-payment-response/:chargeId path, and pass in this wallet type when passing the redirect URL back to the client-side JS in `payment-auth-request.controller.js`. We will use this for logging in `handle-auth-response.controller.js`.
For now, also support the old URL without the wallet as a path parameter so we don't break in-flight payments. Support for this will be removed as …
=> PP-11638 Add wallet path param for logging

app/controllers/web-payments/handle-auth-response.controller.js, app/paths.js, app/routes.js, test/controllers/web-payments/handle-auth-response.controller.test.js
c4ca3a43ec61b017216baa5dc67088e992927c89 added the wallet type as a path parameter to the `/handle-payment-response/:wallet/:chargeId` route. Use this in log lines to log a `wallet` field, which is either "apple" or "google".
Remove the old `/handle-payment-response/:chargeId` route, which was maintained so as not to break in-flight payments when the new route with the path parameter was introduced. New payment journeys will already be directed to the route with the path parameter.
=> PP-11638 Log wallet type when handling auth response

app/views/errors/system-error.njk
- Make the page title and H1 heading match - as this was a WCAG failure.
- This is the only error page that is affected by this.
=> PP-11039 System error nunjucks file - update page title

package-lock.json, package.json
Bump `pay-js-commons` version to 4.0.9. This bump includes the custom branding for Penzance Council.
=> ZD-5569361 bump pay-js-commons version

.github/workflows/run-tests.yml, Dockerfile
Use the reusable workflow in pay-ci to ensure all FROM lines in the Dockerfile are pointing to manifest files
=> PP-12015: Add GHA job to check docker base images are manifests

app/middleware/csp.js
Change Content Security Policy reportUi to reportTo due to the former being deprecated.
See the change under the headers section of the dev tools in browser.
=> Change reportUri to reportTo

app/middleware/csp.js, app/routes.js, server.js
- Missed out the `Reporting-Endpoints` header.
- Required slightly rewriting how we specify the CSP in Helmet.
=> PP-11850 Update CSP > report-to

app/routes.js
- Chrome Reporting API can batch csp violation reports prior to sending, leading to larger than expected payload sizes. To ensure we are receiving all reports we need to increase the max payload size on the `/csp-report` endpoint
=> BAU increase csp request size limit

app/utils/response-router.js, test/utils/response-router.test.js
If we catch an error and render the error page, we do not currently log the error message. The `error` always evaluates as an empty JSON object when we attempt to log it so it is not included. Instead, log the error message.
=> PP-12248 Log error message when rendering error page

app/views/charge.njk, test/cypress/integration/web-payments/apple-pay.test.cy.js, test/cypress/integration/web-payments/google-pay.test.cy.js
- Fixes the Welsh translation of "or" in the divider
- Adds some Cypress tests for Welsh translations on the Charge page when Apple Pay or Google Pay is available
=> PP 12165 Fix Welsh translation of "or" divider under Google Pay & Apple Pay buttons

app/services/clients/connector-axios.client.js
This is the first of many PRS that is breaking up the large PR created to update update the connector client to use Axios:
https://github.com/alphagov/pay-frontend/pull/3824
- Adding this so that we can slowly transition everything to this new version of the connector client using Axios.
- At the moment, nothing is using this for now.
- This is the first PR of many.
- In the following PRs, plan to add updated unit tests.
- Then transition the controllers to start using this new connector Axios client.
- Once everything has transitioned over, the old connector client will be removed.
Best way to see the differences, is by comparing this file to the changes made to it in the large PR:
https://github.com/alphagov/pay-frontend/pull/3824/files#diff-0a8d6b0be878b39296cfff51f4a3c04eef6f05c5a39740 …
=> PP-11682 Add the new connector axios client

test/unit/clients/connector-axios-client-sandbox-google-pay-authentication.pact.test.js
- Updating the existing test to make it work for the new connector Axios client.
=> PP-11682 Add Google Pay sandbox pact test for Axios connector

app/controllers/web-payments/payment-auth-request.controller.js, test/controllers/web-payments/payment-auth-request.controller.test.js
Reverts alphagov/pay-frontend#3836
=> Revert "PP-11682 Update `update payment auth request controller`"

test/unit/clients/adminusers-client-find-service.pact.test.js
- These tests were not running properly, they were using a timeout and inconsistent with the other PACT test.
- Therefore, removed the timeout and made it consistent.
=> PP-11682 Fix admin client PACT test

package-lock.json, package.json
Update to pay-js-commons 5.0.3, which includes custom branding for University Hospital Southampton NHS Foundation Trust.
=> ZD-5842004 Update to pay-js-commons 5.0.3

app/services/clients/adminusers.client.js, app/services/clients/base/config.js, package-lock.json, package.json, test/models/card.test.js, test/unit/clients/adminusers-client-find-service.pact.test.js
- Bump pay-js-commons to v6.0.3
- Update the `axios base client` config to set `acceptAllStatusCodes=true`
- This will mean that all status codes returned from backend API calls will be considered successful.
- The consuming code will then need to decide what to do with those responses.
- Update `admin users` and `card` base client to work with the new `acceptAllStatusCodes=true` setting.
- Update tests
=> PP-11682 - Update pay-js-commons and admins users and card client

test/unit/clients/connector-axios-client-apple-pay-authentication.pact.test.js, test/unit/clients/connector-axios-client-sandbox-google-pay-authentication.pact.test.js
- Update tests to work with the updated `axios-base-client` from pay-js-commons.
- All status codes are now considered successful.  The consuming code will now need to decide how to manage not 2xx responses.
=> PP-11682 - Update axios connect tests

app/controllers/three-d-secure.controller.js
Axios client has status instead of statusCode.
The client was changed to Axios, the switch statement was updated, but we forgot to update the logging.
- Update logging.
=> PP-11682 fix logging

.secrets.baseline, app/controllers/web-payments/apple-pay/merchant-validation.controller.js, package-lock.json, package.json, test/controllers/web-payments/apple-pay/merchant-validation.controller.test.js
With this change, we are removing the use of `requestretry` from the Merchant Validation Controller which currently uses this module.
We are replacing it by using Axios directly.
There is an [Axios bug](https://github.com/axios/axios/issues/4531) when using an SSL proxy.
Therefore, we have had to add the NPM [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) as a workaround.
Note that the previous attempted did not pass our QA on the test environment[1].
Further information in Jira[2].
[1]
https://github.com/alphagov/pay-frontend/pull/3862
[2]
https://payments-platform.atlassian.net/browse/PP-12853
=> PP-12853 Update apple pay merchant validation to use Axios

.secrets.baseline, app/controllers/web-payments/apple-pay/merchant-validation.controller.js, package-lock.json, package.json, test/controllers/web-payments/apple-pay/merchant-validation.controller.test.js
Reverts 2 Apple pay mechant validation fixes that were tried
on the test env but are not working and therefore cannot be released
to PROD.
Revert "PP-12853 Apple pay merchant validation - fix env name"
This reverts commit https://github.com/alphagov/pay-frontend/commit/5450a8e48d48c56cbf1c085796d902db20850c79.
Revert "PP-12853 Update apple pay merchant validation to use Axios"
This reverts commit https://github.com/alphagov/pay-frontend/commit/0c4ab162a38c65a7a7e325135a91fcf4dbc80675.
=> Pp 12853 apple pay merchant validation revert changes

.secrets.baseline, app/controllers/return.controller.js, app/controllers/secure.controller.js, app/middleware/csrf.js, app/models/ChargeState.js, app/routes.js, app/services/clients/connector.client.js, app/utils/cookies.js, app/utils/session.js, server.js, test/controllers/return.controller.test.js, test/controllers/secure.controller.test.js, test/cypress/integration/web-payments/apple-pay.test.cy.js, test/integration/card-details-errors.ft.test.js, test/middleware/csrf.test.js, test/models/ChargeState.test.js, test/test-helpers/session.js, test/test-helpers/test-helpers.js, test/test.env, test/unit/cookies.test.js, test/unit/session.test.js
frontend now holds up to 10 charge objects on the client to allow users
who navigate back to Pay from the service to see the status of their payment
a charge will be removed from the client if 10 charges exist and an 11th payment
is started
the logic for determining which charge to remove is documented in this ADR:
https://github.com/alphagov/pay-architecture/blob/main/adr/026-keep-payments-in-cookie-for-longer.md
- new ChargeState model
- new csrf secret management middleware
- csrf secret is set at the root of the session object as part of a gradual migration of csrf behaviour
- remove used csrf token store from frontend state
- add new cookie functions for handling charge state
- remove unused session code from server
=> PP-12546 hold payments in state after completion

app/middleware/csrf.js, test/middleware/csrf.test.js
this change is part of a wider series that are being merged in sequence to prevent the need for a downtime deployment
- `setCsrfSecret` middle-ware has been deployed and any currently in-flight payments at the time of this deployment should have a top level session csrf secret
- modify the `csrfTokenGeneration` middle-ware to use the top level session csrf secret instead of the charge level csrf secret
- remove redundant log line from `csrfCheck` middle-ware, `fetchAndValidateChargeId` is called ahead of the removed log line and already provides all the necessary logging detail
=> PP-12546 generate tokens from session secret over charge secret

app/controllers/secure.controller.js, app/middleware/csrf.js, test/middleware/csrf.test.js, test/test-helpers/session.js, test/test.env
this change is part of a wider series that are being merged in sequence to prevent the need for a downtime deployment
- do not set charge level csrf secret
- do not validate tokens against charge level csrf secret
- update tests to reflect new behaviour
=> PP-12546 remove csrf secret from charge objects

app/assets/javascripts/browsered/form-validation.js, app/utils/charge-validation-fields.js, app/utils/charge-validation.js, app/views/charge.njk, locales/cy.json, locales/en.json, test/cypress/integration/card/card-details-page-validation.test.cy.js, test/integration/card-details-errors.ft.test.js, test/utils/charge-validation-fields/card-number-field-validation.test.js
Fixing payment page form validation bugs which do not work as per current Design system. Also added are a `<span>` tags with a class of  `"govuk-visually-hidden"` as per GOV.UK Design System.
1. Go to payment page.
2. Submit an empty form and the page shows the error summary at the top. 
3. When you click on each one you should be taken to the corresponding input.
1. Go to the payment page.
2. Enter an invalid card number in the card number field.
3. The error message should appear after the hint text. 
1. Go to the payment page.
2. Enter the following invalid card number in the card number field: 4444333322221111aaa
3. This should show an error.
1. Go to  the payment page
2. Submit an empty form.  The page displays the error summary at the top.
3. In the card number field, enter an …
=> PP-10104 payment page validation bugs

app/assets/javascripts/browsered/form-validation.js, app/views/charge.njk, test/cypress/integration/card/card-details-page-validation.test.cy.js
Fixing same errors appearing multiple times after focus shifts to next item.
1. Submit an empty form.
2. See error messages above both inputs as well as in the summary fields above.
3. Fill out a field, e.g. the card number field, with valid data.
4. Tab out of the field to go to the next. 
5. There should now not be an error message above the data field and the corresponding error message should not be in the error summary at the top of the page. 
N.B. Will squash on merging.
=> PP-10104 remaining payment page validation bug

app/views/charge.njk
- Got rid of redundant div which was causing issues for assistive tech.
=> PP-13164 Update markup around email fieldset

package-lock.json, package.json
Using the latest version of `run-amock` which uses case-sensitive query strings as we no longer have to maintain feature-compatibility with Mountebank.
=> PP-13234: Using latest run-mock

app/services/clients/connector.client.js
- Update logging on `GET` requests to Connector
- this will only log `5xx` responses as errors
- all other non-`200` responses will be logged as warnings
=> PP-12828 Update logging in connector client to only log 5xx responses as errors

README.md, package-lock.json, package.json, test/cypress/plugins/index.js
Also included a tiny `run-amock` version bump.
=> PP-13235: Removed all references to Mountebank

.github/workflows/_run-tests.yml
Upgrade `actions/checkout` to run on Node 20.
=> PP-12244: Upgrade deprecated actions/checkout to v4.2.2

package-lock.json, package.json
Changelog: https://github.com/expressjs/express/releases/tag/4.21.2
Addresses issue with `path-to-regexp` v0.1.10 (see https://github.com/advisories/GHSA-9wv6-86v2-598j). Dependabot was unable to create the pull request automatically in this case.
Also runs `npm audit fix` to upgrade the following:
- `@pact-foundation/pact` 
- `micromatch` and `braces`
- `nanoid`
- `semver`
- `get-func-name`
=> PP-13422: Upgrade express to v4.21.2

app/middleware/csrf.js, app/routes.js, app/utils/response-router.js, package-lock.json, package.json, test/middleware/csrf.test.js
- bump `pay-js-commons` `6.0.18` -> `6.0.22`
- move to `pay-js-commons` csrf middleware impl
- new `handleCsrfError` middleware to retain existing router behaviour
=> PP-13360 move csrf middleware functions to pay-js-commons

app/views/includes/custom.njk, package-lock.json, package.json, test/cypress/integration/card/custom-branding.test.cy.js
- Add Cypress tests for custom branding
- Test white background with dark text.
- Test purple background with white text.
- pay-frontend caches responses from admin users >   find service.
- So each test needs to use a different gateway id or it returns the cached custom branding data.
=> PP-13239 Add Cypress tests for custom branding

app/views/includes/custom.njk
- Bug is caused by an unclosed Cypress attribute that was added for Cypress testing.
- Closing the attribute fixes the issue.
=> PP-13509 Fix custom branding service alignment bug

app/views/auth-waiting.njk, app/views/capture-waiting.njk, app/views/errors/incorrect-state/capture-waiting.njk
- The HTML5 polyfill and IE8 stylesheet files have been removed previously.
- This commit removes the references to those files as they are no longer required
- This is because we no longer provide full support to older that require these files.
=> PP-12475 - Remove HTML5 polyfill and IE8 stylesheet references

package-lock.json, package.json
After undoing a breaking change to Run Amock, this updates to the new latest (non-breaking) release of Run Amock.
This should be compatible with the existing tests.
Related PRs:
The change in Run Amock: https://github.com/alphagov/pay-run-amock/pull/16
Updates to other projects:
https://github.com/alphagov/pay-selfservice/pull/4439
https://github.com/alphagov/pay-products-ui/pull/2742
=> PP-13557: Using the latest release of Run Amock

package-lock.json
[Dev dependencies from pay-js-metrics](https://github.com/alphagov/pay-js-metrics/blob/main/package.json#L28) shouldn't be included.
=> PP-11093: Remove unused dev dependencies from pay-js-metrics

package-lock.json, package.json
With this change, we are updating pay-frontend to use the new pay-js-commons.
We are also updating the version for pay-js-metrics.
=> PP-13984 Upgrade pay-frontend with newest pay-js-commons

app/views/layout.njk, test/cypress/integration/card/footer.test.cy.js
- Updated the footer to use the Nunjucks macro.
- Updated the footer as per new design.
- Removed the reference to the header macro import - as this is automatically imported with the `govuk-frontend` layout.
- Percy results will be added to the PR.
Build: https://percy.io/55ba5e1a/web/pay-frontend/builds/40520702/changed/2179804504?browser=chrome&browser_ids=64&group_snapshots_by=similar_diff&subcategories=approved&test_case_ids=&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280
Percy identified the changes in the footer.
Percy identified the changes in the footer.  Custom branding uses a slightly different font - so the org details appear a few pixels wider
=> PP-14070 - Update footer to new design and use macro

test/cypress/integration/card/footer.test.cy.js
- Adding some more tests to check the colours of the footer when it is using the current branding.
- This is to prepare us for some more work that will be done later where we will need to add code to toggle the new branding.
=> PP-14162 Update Cypress footer tests - check colours

cypress.config.js, package.json, test/cypress/integration/card/rebrand-header-footer.test.cy.rebrand.js
- We now need 2 Cypress test suites temporarily until the new branding is live
- Main test suite
- Rebranding flag ENABLE_REBRAND is undefined.
- Standard Cypress tests with the current branding.
- Custom branding tests.
- These are run with
- npm run cypress:server
- npm run cypress:test
- Rebranding test suite
- Rebranding flag ENABLE_REBRAND = true
- Want to run the test to check the rebranding
- I.e. Check that the header and footer has the new CSS styling.
- This is a new test that is only run when ENABLE_FLAG=true.
- Custom branding tests
- These tests should work whether the ENABLE_REBRAND is true or false/undefined.
- These are run with
- npm run cypress:server-rebrand
- npm run cypress:test-rebrand
- To stop the rebranding test running during the main test suite, it has a …
=> PP-13898 Add tests for rebranding

package.json
- A test to check the error pages containing the new branding was added to the code base.
- This PR is just add this test to the rebrand test suite so that it is only run when testing the new branding.
=> PP-14256 Add rebrand error page test to rebrand test suite

Gruntfile.js
- ensure `stats.html` is no longer copied into `govuk_modules` during the build
=> PP-8287 Remove publicly visible webpack stats page from Frontend
